INSERT INTO `country` VALUES (1,'Afghanistan');
INSERT INTO `country` VALUES (2,'Albania');
INSERT INTO `country` VALUES (3,'Algeria');
INSERT INTO `country` VALUES (4,'American Samoa');
INSERT INTO `country` VALUES (5,'Andorra');
INSERT INTO `country` VALUES (6,'Angola');
INSERT INTO `country` VALUES (7,'Anguilla');
INSERT INTO `country` VALUES (8,'Antarctica');
INSERT INTO `country` VALUES (9,'Antigua and Barbuda');
INSERT INTO `country` VALUES (10,'Argentina');
INSERT INTO `country` VALUES (11,'Armenia');
INSERT INTO `country` VALUES (12,'Aruba');
INSERT INTO `country` VALUES (13,'Australia');
INSERT INTO `country` VALUES (14,'Austria');
INSERT INTO `country` VALUES (15,'Azerbaijan');
INSERT INTO `country` VALUES (16,'Bahamas');
INSERT INTO `country` VALUES (17,'Bahrain');
INSERT INTO `country` VALUES (18,'Bangladesh');
INSERT INTO `country` VALUES (19,'Barbados');
INSERT INTO `country` VALUES (20,'Belarus');
INSERT INTO `country` VALUES (21,'Belgium');
INSERT INTO `country` VALUES (22,'Belize');
INSERT INTO `country` VALUES (23,'Benin');
INSERT INTO `country` VALUES (24,'Bermuda');
INSERT INTO `country` VALUES (25,'Bhutan');
INSERT INTO `country` VALUES (26,'Bolivia');
INSERT INTO `country` VALUES (27,'Bosnia and Herzegovina');
INSERT INTO `country` VALUES (28,'Botswana');
INSERT INTO `country` VALUES (29,'Bouvet Island');
INSERT INTO `country` VALUES (30,'Brazil');
INSERT INTO `country` VALUES (31,'British Indian Ocean Territory');
INSERT INTO `country` VALUES (32,'Brunei Darussalam');
INSERT INTO `country` VALUES (33,'Bulgaria');
INSERT INTO `country` VALUES (34,'Burkina Faso');
INSERT INTO `country` VALUES (35,'Burundi');
INSERT INTO `country` VALUES (36,'Cambodia');
INSERT INTO `country` VALUES (37,'Cameroon');
INSERT INTO `country` VALUES (38,'Canada');
INSERT INTO `country` VALUES (39,'Cape Verde');
INSERT INTO `country` VALUES (40,'Cayman Islands');
INSERT INTO `country` VALUES (41,'Central African Republic');
INSERT INTO `country` VALUES (42,'Chad');
INSERT INTO `country` VALUES (43,'Chile');
INSERT INTO `country` VALUES (44,'China');
INSERT INTO `country` VALUES (45,'Christmas Island');
INSERT INTO `country` VALUES (46,'Cocos (Keeling) Islands');
INSERT INTO `country` VALUES (47,'Colombia');
INSERT INTO `country` VALUES (48,'Comoros');
INSERT INTO `country` VALUES (49,'Congo');
INSERT INTO `country` VALUES (50,'Cook Islands');
INSERT INTO `country` VALUES (51,'Costa Rica');
INSERT INTO `country` VALUES (52,'Croatia (Hrvatska)');
INSERT INTO `country` VALUES (53,'Cuba');
INSERT INTO `country` VALUES (54,'Cyprus');
INSERT INTO `country` VALUES (55,'Czech Republic');
INSERT INTO `country` VALUES (56,'Denmark');
INSERT INTO `country` VALUES (57,'Djibouti');
INSERT INTO `country` VALUES (58,'Dominica');
INSERT INTO `country` VALUES (59,'Dominican Republic');
INSERT INTO `country` VALUES (60,'East Timor');
INSERT INTO `country` VALUES (61,'Ecuador');
INSERT INTO `country` VALUES (62,'Egypt');
INSERT INTO `country` VALUES (63,'El Salvador');
INSERT INTO `country` VALUES (64,'Equatorial Guinea');
INSERT INTO `country` VALUES (65,'Eritrea');
INSERT INTO `country` VALUES (66,'Estonia');
INSERT INTO `country` VALUES (67,'Ethiopia');
INSERT INTO `country` VALUES (68,'Falkland Islands (Malvinas)');
INSERT INTO `country` VALUES (69,'Faroe Islands');
INSERT INTO `country` VALUES (70,'Fiji');
INSERT INTO `country` VALUES (71,'Finland');
INSERT INTO `country` VALUES (72,'France');
INSERT INTO `country` VALUES (73,'France, Metropolitan');
INSERT INTO `country` VALUES (74,'French Guiana');
INSERT INTO `country` VALUES (75,'French Polynesia');
INSERT INTO `country` VALUES (76,'French Southern Territories');
INSERT INTO `country` VALUES (77,'Gabon');
INSERT INTO `country` VALUES (78,'Gambia');
INSERT INTO `country` VALUES (79,'Georgia');
INSERT INTO `country` VALUES (80,'Germany');
INSERT INTO `country` VALUES (81,'Ghana');
INSERT INTO `country` VALUES (82,'Gibraltar');
INSERT INTO `country` VALUES (83,'Guernsey');
INSERT INTO `country` VALUES (84,'Greece');
INSERT INTO `country` VALUES (85,'Greenland');
INSERT INTO `country` VALUES (86,'Grenada');
INSERT INTO `country` VALUES (87,'Guadeloupe');
INSERT INTO `country` VALUES (88,'Guam');
INSERT INTO `country` VALUES (89,'Guatemala');
INSERT INTO `country` VALUES (90,'Guinea');
INSERT INTO `country` VALUES (91,'Guinea-Bissau');
INSERT INTO `country` VALUES (92,'Guyana');
INSERT INTO `country` VALUES (93,'Haiti');
INSERT INTO `country` VALUES (94,'Heard and Mc Donald Islands');
INSERT INTO `country` VALUES (95,'Honduras');
INSERT INTO `country` VALUES (96,'Hong Kong');
INSERT INTO `country` VALUES (97,'Hungary');
INSERT INTO `country` VALUES (98,'Iceland');
INSERT INTO `country` VALUES (99,'India');
INSERT INTO `country` VALUES (100,'Isle of Man');
INSERT INTO `country` VALUES (101,'Indonesia');
INSERT INTO `country` VALUES (102,'Iran (Islamic Republic of)');
INSERT INTO `country` VALUES (103,'Iraq');
INSERT INTO `country` VALUES (104,'Ireland');
INSERT INTO `country` VALUES (105,'Israel');
INSERT INTO `country` VALUES (106,'Italy');
INSERT INTO `country` VALUES (107,'Ivory Coast');
INSERT INTO `country` VALUES (108,'Jersey');
INSERT INTO `country` VALUES (109,'Jamaica');
INSERT INTO `country` VALUES (110,'Japan');
INSERT INTO `country` VALUES (111,'Jordan');
INSERT INTO `country` VALUES (112,'Kazakhstan');
INSERT INTO `country` VALUES (113,'Kenya');
INSERT INTO `country` VALUES (114,'Kiribati');
INSERT INTO `country` VALUES (115,'Korea, Democratic People''s Republic of');
INSERT INTO `country` VALUES (116,'Korea, Republic of');
INSERT INTO `country` VALUES (117,'Kosovo');
INSERT INTO `country` VALUES (118,'Kuwait');
INSERT INTO `country` VALUES (119,'Kyrgyzstan');
INSERT INTO `country` VALUES (120,'Lao People''s Democratic Republic');
INSERT INTO `country` VALUES (121,'Latvia');
INSERT INTO `country` VALUES (122,'Lebanon');
INSERT INTO `country` VALUES (123,'Lesotho');
INSERT INTO `country` VALUES (124,'Liberia');
INSERT INTO `country` VALUES (125,'Libyan Arab Jamahiriya');
INSERT INTO `country` VALUES (126,'Liechtenstein');
INSERT INTO `country` VALUES (127,'Lithuania');
INSERT INTO `country` VALUES (128,'Luxembourg');
INSERT INTO `country` VALUES (129,'Macau');
INSERT INTO `country` VALUES (130,'Macedonia');
INSERT INTO `country` VALUES (131,'Madagascar');
INSERT INTO `country` VALUES (132,'Malawi');
INSERT INTO `country` VALUES (133,'Malaysia');
INSERT INTO `country` VALUES (134,'Maldives');
INSERT INTO `country` VALUES (135,'Mali');
INSERT INTO `country` VALUES (136,'Malta');
INSERT INTO `country` VALUES (137,'Marshall Islands');
INSERT INTO `country` VALUES (138,'Martinique');
INSERT INTO `country` VALUES (139,'Mauritania');
INSERT INTO `country` VALUES (140,'Mauritius');
INSERT INTO `country` VALUES (141,'Mayotte');
INSERT INTO `country` VALUES (142,'Mexico');
INSERT INTO `country` VALUES (143,'Micronesia, Federated States of');
INSERT INTO `country` VALUES (144,'Moldova, Republic of');
INSERT INTO `country` VALUES (145,'Monaco');
INSERT INTO `country` VALUES (146,'Mongolia');
INSERT INTO `country` VALUES (147,'Montenegro');
INSERT INTO `country` VALUES (148,'Montserrat');
INSERT INTO `country` VALUES (149,'Morocco');
INSERT INTO `country` VALUES (150,'Mozambique');
INSERT INTO `country` VALUES (151,'Myanmar');
INSERT INTO `country` VALUES (152,'Namibia');
INSERT INTO `country` VALUES (153,'Nauru');
INSERT INTO `country` VALUES (154,'Nepal');
INSERT INTO `country` VALUES (155,'Netherlands');
INSERT INTO `country` VALUES (156,'Netherlands Antilles');
INSERT INTO `country` VALUES (157,'New Caledonia');
INSERT INTO `country` VALUES (158,'New Zealand');
INSERT INTO `country` VALUES (159,'Nicaragua');
INSERT INTO `country` VALUES (160,'Niger');
INSERT INTO `country` VALUES (161,'Nigeria');
INSERT INTO `country` VALUES (162,'Niue');
INSERT INTO `country` VALUES (163,'Norfolk Island');
INSERT INTO `country` VALUES (164,'Northern Mariana Islands');
INSERT INTO `country` VALUES (165,'Norway');
INSERT INTO `country` VALUES (166,'Oman');
INSERT INTO `country` VALUES (167,'Pakistan');
INSERT INTO `country` VALUES (168,'Palau');
INSERT INTO `country` VALUES (169,'Palestine');
INSERT INTO `country` VALUES (170,'Panama');
INSERT INTO `country` VALUES (171,'Papua New Guinea');
INSERT INTO `country` VALUES (172,'Paraguay');
INSERT INTO `country` VALUES (173,'Peru');
INSERT INTO `country` VALUES (174,'Philippines');
INSERT INTO `country` VALUES (175,'Pitcairn');
INSERT INTO `country` VALUES (176,'Poland');
INSERT INTO `country` VALUES (177,'Portugal');
INSERT INTO `country` VALUES (178,'Puerto Rico');
INSERT INTO `country` VALUES (179,'Qatar');
INSERT INTO `country` VALUES (180,'Reunion');
INSERT INTO `country` VALUES (181,'Romania');
INSERT INTO `country` VALUES (182,'Russian Federation');
INSERT INTO `country` VALUES (183,'Rwanda');
INSERT INTO `country` VALUES (184,'Saint Kitts and Nevis');
INSERT INTO `country` VALUES (185,'Saint Lucia');
INSERT INTO `country` VALUES (186,'Saint Vincent and the Grenadines');
INSERT INTO `country` VALUES (187,'Samoa');
INSERT INTO `country` VALUES (188,'San Marino');
INSERT INTO `country` VALUES (189,'Sao Tome and Principe');
INSERT INTO `country` VALUES (190,'Saudi Arabia');
INSERT INTO `country` VALUES (191,'Senegal');
INSERT INTO `country` VALUES (192,'Serbia');
INSERT INTO `country` VALUES (193,'Seychelles');
INSERT INTO `country` VALUES (194,'Sierra Leone');
INSERT INTO `country` VALUES (195,'Singapore');
INSERT INTO `country` VALUES (196,'Slovakia');
INSERT INTO `country` VALUES (197,'Slovenia');
INSERT INTO `country` VALUES (198,'Solomon Islands');
INSERT INTO `country` VALUES (199,'Somalia');
INSERT INTO `country` VALUES (200,'South Africa');
INSERT INTO `country` VALUES (201,'South Georgia South Sandwich Islands');
INSERT INTO `country` VALUES (202,'Spain');
INSERT INTO `country` VALUES (203,'Sri Lanka');
INSERT INTO `country` VALUES (204,'St. Helena');
INSERT INTO `country` VALUES (205,'St. Pierre and Miquelon');
INSERT INTO `country` VALUES (206,'Sudan');
INSERT INTO `country` VALUES (207,'Suriname');
INSERT INTO `country` VALUES (208,'Svalbard and Jan Mayen Islands');
INSERT INTO `country` VALUES (209,'Swaziland');
INSERT INTO `country` VALUES (210,'Sweden');
INSERT INTO `country` VALUES (211,'Switzerland');
INSERT INTO `country` VALUES (212,'Syrian Arab Republic');
INSERT INTO `country` VALUES (213,'Taiwan');
INSERT INTO `country` VALUES (214,'Tajikistan');
INSERT INTO `country` VALUES (215,'Tanzania, United Republic of');
INSERT INTO `country` VALUES (216,'Thailand');
INSERT INTO `country` VALUES (217,'Togo');
INSERT INTO `country` VALUES (218,'Tokelau');
INSERT INTO `country` VALUES (219,'Tonga');
INSERT INTO `country` VALUES (220,'Trinidad and Tobago');
INSERT INTO `country` VALUES (221,'Tunisia');
INSERT INTO `country` VALUES (222,'Turkey');
INSERT INTO `country` VALUES (223,'Turkmenistan');
INSERT INTO `country` VALUES (224,'Turks and Caicos Islands');
INSERT INTO `country` VALUES (225,'Tuvalu');
INSERT INTO `country` VALUES (226,'Uganda');
INSERT INTO `country` VALUES (227,'Ukraine');
INSERT INTO `country` VALUES (228,'United Arab Emirates');
INSERT INTO `country` VALUES (229,'United Kingdom');
INSERT INTO `country` VALUES (230,'United States');
INSERT INTO `country` VALUES (231,'United States minor outlying islands');
INSERT INTO `country` VALUES (232,'Uruguay');
INSERT INTO `country` VALUES (233,'Uzbekistan');
INSERT INTO `country` VALUES (234,'Vanuatu');
INSERT INTO `country` VALUES (235,'Vatican City State');
INSERT INTO `country` VALUES (236,'Venezuela');
INSERT INTO `country` VALUES (237,'Vietnam');
INSERT INTO `country` VALUES (238,'Virgin Islands (British)');
INSERT INTO `country` VALUES (239,'Virgin Islands (U.S.)');
INSERT INTO `country` VALUES (240,'Wallis and Futuna Islands');
INSERT INTO `country` VALUES (241,'Western Sahara');
INSERT INTO `country` VALUES (242,'Yemen');
INSERT INTO `country` VALUES (243,'Zaire');
INSERT INTO `country` VALUES (244,'Zambia');
INSERT INTO `country` VALUES (245,'Zimbabwe');