INSERT INTO user_role VALUES (1,'SYSTEM_ADMIN');
INSERT INTO user_role VALUES (2,'INSTITUTION_ADMIN');
INSERT INTO user_role VALUES (3,'MENTOR');
INSERT INTO user_role VALUES (4,'MENTEE');

INSERT INTO goal_category VALUES (1,'Leadership and Management Skills');
INSERT INTO goal_category VALUES (2,'Productivity and Time Management Skills');
INSERT INTO goal_category VALUES (3,'Entreprenuership');
INSERT INTO goal_category VALUES (4,'Public Speaking and Communication Skills');

INSERT INTO program_category VALUES (1,'Leadership and Management Skills');
INSERT INTO program_category VALUES (2,'Productivity and Time Management Skills');
INSERT INTO program_category VALUES (3,'Entreprenuership');
INSERT INTO program_category VALUES (4,'Public Speaking and Communication Skills');

INSERT INTO country VALUES (1,'Afganistán');
INSERT INTO country VALUES (2,'Albania');
INSERT INTO country VALUES (3,'Alemania');
INSERT INTO country VALUES (4,'Algeria');
INSERT INTO country VALUES (5,'Andorra');
INSERT INTO country VALUES (6,'Angola');
INSERT INTO country VALUES (7,'Anguila');
INSERT INTO country VALUES (8,'Antártida');
INSERT INTO country VALUES (9,'Antigua y Barbuda');
INSERT INTO country VALUES (10,'Antillas Neerlandesas');
INSERT INTO country VALUES (11,'Arabia Saudita');
INSERT INTO country VALUES (12,'Argentina');
INSERT INTO country VALUES (13,'Armenia');
INSERT INTO country VALUES (14,'Aruba');
INSERT INTO country VALUES (15,'Australia');
INSERT INTO country VALUES (16,'Austria');
INSERT INTO country VALUES (17,'Azerbayán');
INSERT INTO country VALUES (18,'Bélgica');
INSERT INTO country VALUES (19,'Bahamas');
INSERT INTO country VALUES (20,'Bahrein');
INSERT INTO country VALUES (21,'Bangladesh');
INSERT INTO country VALUES (22,'Barbados');
INSERT INTO country VALUES (23,'Belice');
INSERT INTO country VALUES (24,'Benín');
INSERT INTO country VALUES (25,'Bhután');
INSERT INTO country VALUES (26,'Bielorrusia');
INSERT INTO country VALUES (27,'Birmania');
INSERT INTO country VALUES (28,'Bolivia');
INSERT INTO country VALUES (29,'Bosnia y Herzegovina');
INSERT INTO country VALUES (30,'Botsuana');
INSERT INTO country VALUES (31,'Brasil');
INSERT INTO country VALUES (32,'Brunéi');
INSERT INTO country VALUES (33,'Bulgaria');
INSERT INTO country VALUES (34,'Burkina Faso');
INSERT INTO country VALUES (35,'Burundi');
INSERT INTO country VALUES (36,'Cabo Verde');
INSERT INTO country VALUES (37,'Camboya');
INSERT INTO country VALUES (38,'Camerún');
INSERT INTO country VALUES (39,'Canadá');
INSERT INTO country VALUES (40,'Chad');
INSERT INTO country VALUES (41,'Chile');
INSERT INTO country VALUES (42,'China');
INSERT INTO country VALUES (43,'Chipre');
INSERT INTO country VALUES (44,'Ciudad del Vaticano');
INSERT INTO country VALUES (45,'Colombia');
INSERT INTO country VALUES (46,'Comoras');
INSERT INTO country VALUES (47,'Congo');
INSERT INTO country VALUES (48,'Congo');
INSERT INTO country VALUES (49,'Corea del Norte');
INSERT INTO country VALUES (50,'Corea del Sur');
INSERT INTO country VALUES (51,'Costa de Marfil');
INSERT INTO country VALUES (52,'Costa Rica');
INSERT INTO country VALUES (53,'Croacia');
INSERT INTO country VALUES (54,'Cuba');
INSERT INTO country VALUES (55,'Dinamarca');
INSERT INTO country VALUES (56,'Dominica');
INSERT INTO country VALUES (57,'Ecuador');
INSERT INTO country VALUES (58,'Egipto');
INSERT INTO country VALUES (59,'El Salvador');
INSERT INTO country VALUES (60,'Emiratos Árabes Unidos');
INSERT INTO country VALUES (61,'Eritrea');
INSERT INTO country VALUES (62,'Eslovaquia');
INSERT INTO country VALUES (63,'Eslovenia');
INSERT INTO country VALUES (64,'España');
INSERT INTO country VALUES (65,'Estados Unidos de América');
INSERT INTO country VALUES (66,'Estonia');
INSERT INTO country VALUES (67,'Etiopía');
INSERT INTO country VALUES (68,'Filipinas');
INSERT INTO country VALUES (69,'Finlandia');
INSERT INTO country VALUES (70,'Fiyi');
INSERT INTO country VALUES (71,'Francia');
INSERT INTO country VALUES (72,'Gabón');
INSERT INTO country VALUES (73,'Gambia');
INSERT INTO country VALUES (74,'Georgia');
INSERT INTO country VALUES (75,'Ghana');
INSERT INTO country VALUES (76,'Gibraltar');
INSERT INTO country VALUES (77,'Granada');
INSERT INTO country VALUES (78,'Grecia');
INSERT INTO country VALUES (79,'Groenlandia');
INSERT INTO country VALUES (80,'Guadalupe');
INSERT INTO country VALUES (81,'Guam');
INSERT INTO country VALUES (82,'Guatemala');
INSERT INTO country VALUES (83,'Guayana Francesa');
INSERT INTO country VALUES (84,'Guernsey');
INSERT INTO country VALUES (85,'Guinea');
INSERT INTO country VALUES (86,'Guinea Ecuatorial');
INSERT INTO country VALUES (87,'Guinea-Bissau');
INSERT INTO country VALUES (88,'Guyana');
INSERT INTO country VALUES (89,'Haití');
INSERT INTO country VALUES (90,'Honduras');
INSERT INTO country VALUES (91,'Hong kong');
INSERT INTO country VALUES (92,'Hungría');
INSERT INTO country VALUES (93,'India');
INSERT INTO country VALUES (94,'Indonesia');
INSERT INTO country VALUES (95,'Irán');
INSERT INTO country VALUES (96,'Irak');
INSERT INTO country VALUES (97,'Irlanda');
INSERT INTO country VALUES (98,'Isla Bouvet');
INSERT INTO country VALUES (99,'Isla de Man');
INSERT INTO country VALUES (100,'Isla de Navidad');
INSERT INTO country VALUES (101,'Isla Norfolk');
INSERT INTO country VALUES (102,'Islandia');
INSERT INTO country VALUES (103,'Islas Bermudas');
INSERT INTO country VALUES (104,'Islas Caimán');
INSERT INTO country VALUES (105,'Islas Cocos (Keeling)');
INSERT INTO country VALUES (106,'Islas Cook');
INSERT INTO country VALUES (107,'Islas de Åland');
INSERT INTO country VALUES (108,'Islas Feroe');
INSERT INTO country VALUES (109,'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO country VALUES (110,'Islas Heard y McDonald');
INSERT INTO country VALUES (111,'Islas Maldivas');
INSERT INTO country VALUES (112,'Islas Malvinas');
INSERT INTO country VALUES (113,'Islas Marianas del Norte');
INSERT INTO country VALUES (114,'Islas Marshall');
INSERT INTO country VALUES (115,'Islas Pitcairn');
INSERT INTO country VALUES (116,'Islas Salomón');
INSERT INTO country VALUES (117,'Islas Turcas y Caicos');
INSERT INTO country VALUES (118,'Islas Ultramarinas Menores de Estados Unidos');
INSERT INTO country VALUES (119,'Islas Vírgenes Británicas');
INSERT INTO country VALUES (120,'Islas Vírgenes de los Estados Unidos');
INSERT INTO country VALUES (121,'Israel');
INSERT INTO country VALUES (122,'Italia');
INSERT INTO country VALUES (123,'Jamaica');
INSERT INTO country VALUES (124,'Japón');
INSERT INTO country VALUES (125,'Jersey');
INSERT INTO country VALUES (126,'Jordania');
INSERT INTO country VALUES (127,'Kazajistán');
INSERT INTO country VALUES (128,'Kenia');
INSERT INTO country VALUES (129,'Kirgizstán');
INSERT INTO country VALUES (130,'Kiribati');
INSERT INTO country VALUES (131,'Kuwait');
INSERT INTO country VALUES (132,'Líbano');
INSERT INTO country VALUES (133,'Laos');
INSERT INTO country VALUES (134,'Lesoto');
INSERT INTO country VALUES (135,'Letonia');
INSERT INTO country VALUES (136,'Liberia');
INSERT INTO country VALUES (137,'Libia');
INSERT INTO country VALUES (138,'Liechtenstein');
INSERT INTO country VALUES (139,'Lituania');
INSERT INTO country VALUES (140,'Luxemburgo');
INSERT INTO country VALUES (141,'México');
INSERT INTO country VALUES (142,'Mónaco');
INSERT INTO country VALUES (143,'Macao');
INSERT INTO country VALUES (144,'Macedônia');
INSERT INTO country VALUES (145,'Madagascar');
INSERT INTO country VALUES (146,'Malasia');
INSERT INTO country VALUES (147,'Malawi');
INSERT INTO country VALUES (148,'Mali');
INSERT INTO country VALUES (149,'Malta');
INSERT INTO country VALUES (150,'Marruecos');
INSERT INTO country VALUES (151,'Martinica');
INSERT INTO country VALUES (152,'Mauricio');
INSERT INTO country VALUES (153,'Mauritania');
INSERT INTO country VALUES (154,'Mayotte');
INSERT INTO country VALUES (155,'Micronesia');
INSERT INTO country VALUES (156,'Moldavia');
INSERT INTO country VALUES (157,'Mongolia');
INSERT INTO country VALUES (158,'Montenegro');
INSERT INTO country VALUES (159,'Montserrat');
INSERT INTO country VALUES (160,'Mozambique');
INSERT INTO country VALUES (161,'Namibia');
INSERT INTO country VALUES (162,'Nauru');
INSERT INTO country VALUES (163,'Nepal');
INSERT INTO country VALUES (164,'Nicaragua');
INSERT INTO country VALUES (165,'Niger');
INSERT INTO country VALUES (166,'Nigeria');
INSERT INTO country VALUES (167,'Niue');
INSERT INTO country VALUES (168,'Noruega');
INSERT INTO country VALUES (169,'Nueva Caledonia');
INSERT INTO country VALUES (170,'Nueva Zelanda');
INSERT INTO country VALUES (171,'Omán');
INSERT INTO country VALUES (172,'Países Bajos');
INSERT INTO country VALUES (173,'Pakistán');
INSERT INTO country VALUES (174,'Palau');
INSERT INTO country VALUES (175,'Palestina');
INSERT INTO country VALUES (176,'Panamá');
INSERT INTO country VALUES (177,'Papúa Nueva Guinea');
INSERT INTO country VALUES (178,'Paraguay');
INSERT INTO country VALUES (179,'Perú');
INSERT INTO country VALUES (180,'Polinesia Francesa');
INSERT INTO country VALUES (181,'Polonia');
INSERT INTO country VALUES (182,'Portugal');
INSERT INTO country VALUES (183,'Puerto Rico');
INSERT INTO country VALUES (184,'Qatar');
INSERT INTO country VALUES (185,'Reino Unido');
INSERT INTO country VALUES (186,'República Centroafricana');
INSERT INTO country VALUES (187,'República Checa');
INSERT INTO country VALUES (188,'República Dominicana');
INSERT INTO country VALUES (189,'Reunión');
INSERT INTO country VALUES (190,'Ruanda');
INSERT INTO country VALUES (191,'Rumanía');
INSERT INTO country VALUES (192,'Rusia');
INSERT INTO country VALUES (193,'Sahara Occidental');
INSERT INTO country VALUES (194,'Samoa');
INSERT INTO country VALUES (195,'Samoa Americana');
INSERT INTO country VALUES (196,'San Bartolomé');
INSERT INTO country VALUES (197,'San Cristóbal y Nieves');
INSERT INTO country VALUES (198,'San Marino');
INSERT INTO country VALUES (199,'San Martín (Francia)');
INSERT INTO country VALUES (200,'San Pedro y Miquelón');
INSERT INTO country VALUES (201,'San Vicente y las Granadinas');
INSERT INTO country VALUES (202,'Santa Elena');
INSERT INTO country VALUES (203,'Santa Lucía');
INSERT INTO country VALUES (204,'Santo Tomé y Príncipe');
INSERT INTO country VALUES (205,'Senegal');
INSERT INTO country VALUES (206,'Serbia');
INSERT INTO country VALUES (207,'Seychelles');
INSERT INTO country VALUES (208,'Sierra Leona');
INSERT INTO country VALUES (209,'Singapur');
INSERT INTO country VALUES (210,'Siria');
INSERT INTO country VALUES (211,'Somalia');
INSERT INTO country VALUES (212,'Sri lanka');
INSERT INTO country VALUES (213,'Sudáfrica');
INSERT INTO country VALUES (214,'Sudán');
INSERT INTO country VALUES (215,'Suecia');
INSERT INTO country VALUES (216,'Suiza');
INSERT INTO country VALUES (217,'Surinám');
INSERT INTO country VALUES (218,'Svalbard y Jan Mayen');
INSERT INTO country VALUES (219,'Swazilandia');
INSERT INTO country VALUES (220,'Tadjikistán');
INSERT INTO country VALUES (221,'Tailandia');
INSERT INTO country VALUES (222,'Taiwán');
INSERT INTO country VALUES (223,'Tanzania');
INSERT INTO country VALUES (224,'Territorio Británico del Océano Índico');
INSERT INTO country VALUES (225,'Territorios Australes y Antárticas Franceses');
INSERT INTO country VALUES (226,'Timor Oriental');
INSERT INTO country VALUES (227,'Togo');
INSERT INTO country VALUES (228,'Tokelau');
INSERT INTO country VALUES (229,'Tonga');
INSERT INTO country VALUES (230,'Trinidad y Tobago');
INSERT INTO country VALUES (231,'Tunez');
INSERT INTO country VALUES (232,'Turkmenistán');
INSERT INTO country VALUES (233,'Turquía');
INSERT INTO country VALUES (234,'Tuvalu');
INSERT INTO country VALUES (235,'Ucrania');
INSERT INTO country VALUES (236,'Uganda');
INSERT INTO country VALUES (237,'Uruguay');
INSERT INTO country VALUES (238,'Uzbekistán');
INSERT INTO country VALUES (239,'Vanuatu');
INSERT INTO country VALUES (240,'Venezuela');
INSERT INTO country VALUES (241,'Vietnam');
INSERT INTO country VALUES (242,'Wallis y Futuna');
INSERT INTO country VALUES (243,'Yemen');
INSERT INTO country VALUES (244,'Yibuti');
INSERT INTO country VALUES (245,'Zambia');
INSERT INTO country VALUES (246,'Zimbabue');

INSERT INTO state VALUES (1,'Alabama', 65);
INSERT INTO state VALUES (2,'Alaska', 65);
INSERT INTO state VALUES (3,'Arizona', 65);
INSERT INTO state VALUES (4,'Arkansas', 65);
INSERT INTO state VALUES (5,'California', 65);
INSERT INTO state VALUES (6,'Colorado', 65);
INSERT INTO state VALUES (7,'Connecticut', 65);
INSERT INTO state VALUES (8,'Delaware', 65);
INSERT INTO state VALUES (9,'Florida', 65);
INSERT INTO state VALUES (10,'Georgia', 65);
INSERT INTO state VALUES (11,'Hawaii', 65);
INSERT INTO state VALUES (12,'Idaho', 65);
INSERT INTO state VALUES (13,'Illinois', 65);
INSERT INTO state VALUES (14,'Indiana', 65);
INSERT INTO state VALUES (15,'Iowa', 65);
INSERT INTO state VALUES (16,'Kansas', 65);
INSERT INTO state VALUES (17,'Kentucky', 65);
INSERT INTO state VALUES (18,'Louisiana', 65);
INSERT INTO state VALUES (19,'Maine', 65);
INSERT INTO state VALUES (20,'Maryland', 65);
INSERT INTO state VALUES (21,'Massachusetts', 65);
INSERT INTO state VALUES (22,'Michigan', 65);
INSERT INTO state VALUES (23,'Minnesota', 65);
INSERT INTO state VALUES (24,'Mississippi', 65);
INSERT INTO state VALUES (25,'Missouri', 65);
INSERT INTO state VALUES (26,'Montana', 65);
INSERT INTO state VALUES (27,'Nebraska', 65);
INSERT INTO state VALUES (28,'Nevada', 65);
INSERT INTO state VALUES (29,'New Hampshire', 65);
INSERT INTO state VALUES (30,'New Jersey', 65);
INSERT INTO state VALUES (31,'New Mexico', 65);
INSERT INTO state VALUES (32,'New York', 65);
INSERT INTO state VALUES (33,'North Carolina', 65);
INSERT INTO state VALUES (34,'North Dakota', 65);
INSERT INTO state VALUES (35,'Ohio', 65);
INSERT INTO state VALUES (36,'Oklahoma', 65);
INSERT INTO state VALUES (37,'Oregon', 65);
INSERT INTO state VALUES (38,'Pennsylvania', 65);
INSERT INTO state VALUES (39,'Rhode Island', 65);
INSERT INTO state VALUES (40,'South Carolina', 65);
INSERT INTO state VALUES (41,'South Dakota', 65);
INSERT INTO state VALUES (42,'Tennessee', 65);
INSERT INTO state VALUES (43,'Texas', 65);
INSERT INTO state VALUES (44,'Utah', 65);
INSERT INTO state VALUES (45,'Vermont', 65);
INSERT INTO state VALUES (46,'Virginia', 65);
INSERT INTO state VALUES (47,'Washington', 65);
INSERT INTO state VALUES (48,'West Virginia', 65);
INSERT INTO state VALUES (49,'Wisconsin', 65);
INSERT INTO state VALUES (50,'Wyoming', 65);
INSERT INTO state VALUES (51,'Aguascalientes', 141);
INSERT INTO state VALUES (52,'Baja California', 141);
INSERT INTO state VALUES (53,'Baja California Sur', 141);
INSERT INTO state VALUES (54,'Campeche', 141);
INSERT INTO state VALUES (55,'Chiapas', 141);
INSERT INTO state VALUES (56,'Chihuahua', 141);
INSERT INTO state VALUES (57,'Coahuila', 141);
INSERT INTO state VALUES (58,'Colima', 141);
INSERT INTO state VALUES (59,'Durango', 141);
INSERT INTO state VALUES (60,'Guanajuato', 141);
INSERT INTO state VALUES (61,'Guerrero', 141);
INSERT INTO state VALUES (62,'Hidalgo', 141);
INSERT INTO state VALUES (63,'Jalisco', 141);
INSERT INTO state VALUES (64,'México', 141);
INSERT INTO state VALUES (65,'Michoacán', 141);
INSERT INTO state VALUES (66,'Morelos', 141);
INSERT INTO state VALUES (67,'Nayarit', 141);
INSERT INTO state VALUES (68,'Nuevo León', 141);
INSERT INTO state VALUES (69,'Oaxaca', 141);
INSERT INTO state VALUES (70,'Puebla', 141);
INSERT INTO state VALUES (71,'Querétaro', 141);
INSERT INTO state VALUES (72,'Quintana Roo', 141);
INSERT INTO state VALUES (73,'San Luis Potosí', 141);
INSERT INTO state VALUES (74,'Sinaloa', 141);
INSERT INTO state VALUES (75,'Sonora', 141);
INSERT INTO state VALUES (76,'Tabasco', 141);
INSERT INTO state VALUES (77,'Tamaulipas', 141);
INSERT INTO state VALUES (78,'Tlaxcala', 141);
INSERT INTO state VALUES (79,'Veracruz', 141);
INSERT INTO state VALUES (80,'Yucatán', 141);
INSERT INTO state VALUES (81,'Zacatecas', 141);

INSERT INTO user VALUES (1, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'System', 'Admin', 'admin@mentorme.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-01','ACTIVE', NULL, NULL, NULL, false, true, '7583 Classon Avenue', 'Brooklyn',32,65,'11205',-73.9617176,40.6978877, '2016-10-01');

insert into personal_interest(id, value) values(1, 'Artes y Entretenimiento' );                            
insert into personal_interest(id, value) values(2, 'Automotriz' );                                        
insert into personal_interest(id, value) values(3, 'Negocios' );                                           
insert into personal_interest(id, value) values(4, 'Carreras' );                                           
insert into personal_interest(id, value) values(5, 'Educación' );                                        
insert into personal_interest(id, value) values(6, 'Familia y Formación de los Hijos' );                   
insert into personal_interest(id, value) values(7, 'Salud y Acondicionamiento Físico' );                   
insert into personal_interest(id, value) values(8, 'Comida y Bebida' );                                    
insert into personal_interest(id, value) values(9, 'Pasatiempos e Intereses' );                            
insert into personal_interest(id, value) values(10, 'Hogar y Jardinería' );                                 
insert into personal_interest(id, value) values(11, 'Ley, Gobierno y Política' );                           
insert into personal_interest(id, value) values(12, 'Noticias' );                                           
insert into personal_interest(id, value) values(13, 'Finanzas Personales' );                                
insert into personal_interest(id, value) values(14, 'Sociedad' );                                           
insert into personal_interest(id, value) values(15, 'Ciencias' );                                           
insert into personal_interest(id, value) values(16, 'Mascotas' );                                           
insert into personal_interest(id, value) values(17, 'Deportes' );                                           
insert into personal_interest(id, value) values(18, 'Estilo y Moda' );                                      
insert into personal_interest(id, value) values(19, 'Tecnología y Computación' );                          
insert into personal_interest(id, value) values(20, 'Viajes' );                                             
insert into personal_interest(id, value) values(21, 'Bienes Inmuebles' );                                   
insert into personal_interest(id, value) values(22, 'Compras' );                                        
insert into personal_interest(id, value) values(23, 'Religión y Espiritualidad' );                          
insert into personal_interest(id, value) values(24, 'No Categorizado' );                                    
insert into personal_interest(id, value, parent_category_id) values(25, 'Libros y Literatura', 1);            
insert into personal_interest(id, value, parent_category_id) values(26, 'Celebridades', 1 );                    
insert into personal_interest(id, value, parent_category_id) values(27, 'Bellas Artes', 1);
insert into personal_interest(id, value, parent_category_id) values(28, 'Humor', 1);
insert into personal_interest(id, value, parent_category_id) values(29, 'Películas', 1);
insert into personal_interest(id, value, parent_category_id) values(30, 'Música', 1);
insert into personal_interest(id, value, parent_category_id) values(31, 'Televisión', 1);                                         
insert into personal_interest(id, value, parent_category_id) values(32, 'Auto Partes', 2);
insert into personal_interest(id, value, parent_category_id) values(33, 'Reparación Automotriz', 2);
insert into personal_interest(id, value, parent_category_id) values(34, 'Compra-Venta de Autos', 2);
insert into personal_interest(id, value, parent_category_id) values(35, 'Cultura Automotriz', 2);
insert into personal_interest(id, value, parent_category_id) values(36, 'Certificado de Pre-Uso', 2);
insert into personal_interest(id, value, parent_category_id) values(37, 'Convertible', 2);
insert into personal_interest(id, value, parent_category_id) values(38, 'Coupe', 2);
insert into personal_interest(id, value, parent_category_id) values(39, 'Crossover', 2);
insert into personal_interest(id, value, parent_category_id) values(40, 'Diesel', 2);
insert into personal_interest(id, value, parent_category_id) values(41, 'Vehículo Eléctrico', 2);
insert into personal_interest(id, value, parent_category_id) values(42, 'Hatchback', 2);
insert into personal_interest(id, value, parent_category_id) values(43, 'Híbrido', 2);
insert into personal_interest(id, value, parent_category_id) values(44, 'Lujo', 2);
insert into personal_interest(id, value, parent_category_id) values(45, 'MiniVan', 2);
insert into personal_interest(id, value, parent_category_id) values(46, 'Motocicleta', 2);
insert into personal_interest(id, value, parent_category_id) values(47, 'Navegación', 2);
insert into personal_interest(id, value, parent_category_id) values(48, 'Vehículo Todoterreno', 2);
insert into personal_interest(id, value, parent_category_id) values(49, 'Vehículo de Desempeño', 2);
insert into personal_interest(id, value, parent_category_id) values(50, 'Pickup', 2);
insert into personal_interest(id, value, parent_category_id) values(51, 'Asistencia en el Camino', 2);
insert into personal_interest(id, value, parent_category_id) values(52, 'Sedan', 2);
insert into personal_interest(id, value, parent_category_id) values(53, 'Camiones y Accesorios', 2);
insert into personal_interest(id, value, parent_category_id) values(54, 'Autos Antiguos', 2);
insert into personal_interest(id, value, parent_category_id) values(55, 'Vagoneta', 2);
insert into personal_interest(id, value, parent_category_id) values(56, 'Publicidad', 3);
insert into personal_interest(id, value, parent_category_id) values(57, 'Agricultura', 3);
insert into personal_interest(id, value, parent_category_id) values(58, 'Biotecnología/Biomédico', 3);
insert into personal_interest(id, value, parent_category_id) values(59, 'Software de Negocios', 3);
insert into personal_interest(id, value, parent_category_id) values(60, 'Construcción', 3);
insert into personal_interest(id, value, parent_category_id) values(61, 'Ciencias Forstales', 3);
insert into personal_interest(id, value, parent_category_id) values(62, 'Gobierno', 3);
insert into personal_interest(id, value, parent_category_id) values(63, 'Soluciones Verdes', 3);
insert into personal_interest(id, value, parent_category_id) values(64, 'Recursos Humanos', 3);
insert into personal_interest(id, value, parent_category_id) values(65, 'Logística', 3);
insert into personal_interest(id, value, parent_category_id) values(66, 'Mercadotecnia', 3);
insert into personal_interest(id, value, parent_category_id) values(67, 'Metales', 3);
insert into personal_interest(id, value, parent_category_id) values(68, 'Productividad', 3);
insert into personal_interest(id, value, parent_category_id) values(69, 'Planeación de Carrera', 4);
insert into personal_interest(id, value, parent_category_id) values(70, 'Universidad', 4);
insert into personal_interest(id, value, parent_category_id) values(71, 'Ayuda Financiera', 4);
insert into personal_interest(id, value, parent_category_id) values(72, 'Ferias de Trabajo', 4);
insert into personal_interest(id, value, parent_category_id) values(73, 'Búsqueda de Trabajo', 4);
insert into personal_interest(id, value, parent_category_id) values(74, 'Curriculum Escribir/Aconsejar', 4);
insert into personal_interest(id, value, parent_category_id) values(75, 'Enfermería', 4);
insert into personal_interest(id, value, parent_category_id) values(77, 'Trabajo a Distancia', 4);
insert into personal_interest(id, value, parent_category_id) values(78, 'Militar de los Estados Unidos', 4);
insert into personal_interest(id, value, parent_category_id) values(79, 'Consejo de Carrera', 4);
insert into personal_interest(id, value, parent_category_id) values(80, 'Educación Primaria', 5);
insert into personal_interest(id, value, parent_category_id) values(81, 'Educación para Adultos', 5);
insert into personal_interest(id, value, parent_category_id) values(82, 'Historia del Arte', 5);
insert into personal_interest(id, value, parent_category_id) values(83, 'Adminitración Universitaria', 5);
insert into personal_interest(id, value, parent_category_id) values(84, 'Vida Universitaria', 5);
insert into personal_interest(id, value, parent_category_id) values(85, 'Aprendizaje a Distancia', 5);
insert into personal_interest(id, value, parent_category_id) values(86, 'Inglés como Segunda Lengua', 5);
insert into personal_interest(id, value, parent_category_id) values(87, 'Aprendizaje de Lenguajes', 5);
insert into personal_interest(id, value, parent_category_id) values(88, 'Escuela de Posgrado', 5);
insert into personal_interest(id, value, parent_category_id) values(89, 'Educación en el Hogar', 5);
insert into personal_interest(id, value, parent_category_id) values(90, 'Tarea/Consejos de Estudio', 5);
insert into personal_interest(id, value, parent_category_id) values(91, 'Educadores de Primaria', 5);
insert into personal_interest(id, value, parent_category_id) values(92, 'Escuela Privada', 5);
insert into personal_interest(id, value, parent_category_id) values(93, 'Educación Especial', 5);
insert into personal_interest(id, value, parent_category_id) values(94, 'Estudiando Negocios', 5);
insert into personal_interest(id, value, parent_category_id) values(95, 'Adopción', 6);
insert into personal_interest(id, value, parent_category_id) values(96, 'Bebés e Infantes', 6);
insert into personal_interest(id, value, parent_category_id) values(97, 'Guardería/Pre escolar', 6);
insert into personal_interest(id, value, parent_category_id) values(98, 'Internet Familiar', 6);
insert into personal_interest(id, value, parent_category_id) values(99, 'Formación de Hijos en Primaria', 6);
insert into personal_interest(id, value, parent_category_id) values(100, 'Formación de Adolescentes', 6);
insert into personal_interest(id, value, parent_category_id) values(101, 'Embarazo', 6);
insert into personal_interest(id, value, parent_category_id) values(102, 'Niños con Necesidades Especiales', 6);
insert into personal_interest(id, value, parent_category_id) values(103, 'Cuidados a Adultos Mayores', 6);
insert into personal_interest(id, value, parent_category_id) values(104, 'Ejercicio', 7);
insert into personal_interest(id, value, parent_category_id) values(105, 'Síndrome de Déficit de Atención', 7);
insert into personal_interest(id, value, parent_category_id) values(106, 'SIDA/VIH', 7);
insert into personal_interest(id, value, parent_category_id) values(107, 'Alergias', 7);
insert into personal_interest(id, value, parent_category_id) values(108, 'Medicina Alternativa', 7);
insert into personal_interest(id, value, parent_category_id) values(109, 'Artritis', 7);
insert into personal_interest(id, value, parent_category_id) values(110, 'Asma', 7);
insert into personal_interest(id, value, parent_category_id) values(111, 'Autismo/Desórden del Desarrollo', 7);
insert into personal_interest(id, value, parent_category_id) values(112, 'Desorden Bipolar', 7);
insert into personal_interest(id, value, parent_category_id) values(113, 'Tumor Cerebral', 7);
insert into personal_interest(id, value, parent_category_id) values(114, 'Cáncer', 7);
insert into personal_interest(id, value, parent_category_id) values(115, 'Colesterol', 7);
insert into personal_interest(id, value, parent_category_id) values(116, 'Síndrome de Fatiga Crónica', 7);
insert into personal_interest(id, value, parent_category_id) values(117, 'Dolor Crónico', 7);
insert into personal_interest(id, value, parent_category_id) values(118, 'Catarro y Gripe', 7);
insert into personal_interest(id, value, parent_category_id) values(119, 'Sordera', 7);
insert into personal_interest(id, value, parent_category_id) values(120, 'Cuidado Dental', 7);
insert into personal_interest(id, value, parent_category_id) values(121, 'Depresión', 7);
insert into personal_interest(id, value, parent_category_id) values(122, 'Dermatología', 7);
insert into personal_interest(id, value, parent_category_id) values(123, 'Diabetes', 7);
insert into personal_interest(id, value, parent_category_id) values(124, 'Epilepsia', 7);
insert into personal_interest(id, value, parent_category_id) values(125, 'Gastritis/Reflujo', 7);
insert into personal_interest(id, value, parent_category_id) values(126, 'Dolor de Cabeza/Migraña', 7);
insert into personal_interest(id, value, parent_category_id) values(127, 'Enfermedad del Corazón', 7);
insert into personal_interest(id, value, parent_category_id) values(128, 'Hierbas Medicinales', 7);
insert into personal_interest(id, value, parent_category_id) values(129, 'Sanación Holística', 7);
insert into personal_interest(id, value, parent_category_id) values(130  'Síndrome de Intestino Irritable/Enfermedad de Crohn', 7);
insert into personal_interest(id, value, parent_category_id) values(131, 'Soporte para Casos de Incesto/Abuso', 7);
insert into personal_interest(id, value, parent_category_id) values(132, 'Incontinencia', 7);
insert into personal_interest(id, value, parent_category_id) values(133, 'Infertilidad', 7);
insert into personal_interest(id, value, parent_category_id) values(134, 'Salud Masculina', 7);
insert into personal_interest(id, value, parent_category_id) values(135, 'Nutrición', 7);
insert into personal_interest(id, value, parent_category_id) values(136, 'Ortopedia', 7);
insert into personal_interest(id, value, parent_category_id) values(137, 'Pánico/Ansiedad', 7);
insert into personal_interest(id, value, parent_category_id) values(138, 'Desórdenes', 7);
insert into personal_interest(id, value, parent_category_id) values(139, 'Pediatría', 7);
insert into personal_interest(id, value, parent_category_id) values(140, 'Terapia Física', 7);
insert into personal_interest(id, value, parent_category_id) values(141, 'Psicología/Psiquiatría', 7);
insert into personal_interest(id, value, parent_category_id) values(142, 'Salud del Adulto Mayor', 7);
insert into personal_interest(id, value, parent_category_id) values(143, 'Sexualidad', 7);
insert into personal_interest(id, value, parent_category_id) values(144, 'Desórdenes del Sueño', 7);
insert into personal_interest(id, value, parent_category_id) values(145, 'Dejar de Fumar', 7);
insert into personal_interest(id, value, parent_category_id) values(146, 'Abuso de Sustancias', 7);
insert into personal_interest(id, value, parent_category_id) values(147, 'Enfermedad de la Tiroides', 7);
insert into personal_interest(id, value, parent_category_id) values(148, 'Bajar de Peso', 7);
insert into personal_interest(id, value, parent_category_id) values(149, 'Salud Femenina', 7);
insert into personal_interest(id, value, parent_category_id) values(150, 'Cocina Americana', 8);
insert into personal_interest(id, value, parent_category_id) values(151, 'Parrilla y Plancha', 8);
insert into personal_interest(id, value, parent_category_id) values(152, 'Cajun/Creole', 8);
insert into personal_interest(id, value, parent_category_id) values(153, 'Cocina China', 8);
insert into personal_interest(id, value, parent_category_id) values(154, 'Cocteles/Cerveza', 8);
insert into personal_interest(id, value, parent_category_id) values(155, 'Café/Té', 8);
insert into personal_interest(id, value, parent_category_id) values(156, 'Cocina Específica', 8);
insert into personal_interest(id, value, parent_category_id) values(157, 'Postres y Hornear', 8);
insert into personal_interest(id, value, parent_category_id) values(158, 'Cenar Fuera', 8);
insert into personal_interest(id, value, parent_category_id) values(159, 'Alergías Alimenticias', 8);
insert into personal_interest(id, value, parent_category_id) values(160, 'Cocina Francesa', 8);
insert into personal_interest(id, value, parent_category_id) values(161, 'Salud/Cocina Baja en Grsas', 8);
insert into personal_interest(id, value, parent_category_id) values(162, 'Cocina Italiana', 8);
insert into personal_interest(id, value, parent_category_id) values(163, 'Cocina Japonesa', 8);
insert into personal_interest(id, value, parent_category_id) values(164, 'Cocina Mexicana', 8);
insert into personal_interest(id, value, parent_category_id) values(165, 'Vegana', 8);
insert into personal_interest(id, value, parent_category_id) values(166, 'Vegetariana', 8);
insert into personal_interest(id, value, parent_category_id) values(167, 'Vino', 8);
insert into personal_interest(id, value, parent_category_id) values(168, 'Arte/Tecnología', 9);
insert into personal_interest(id, value, parent_category_id) values(169, 'Manualidades', 9);
insert into personal_interest(id, value, parent_category_id) values(170, 'Trabajo con cuentas/chaquira', 9);
insert into personal_interest(id, value, parent_category_id) values(171, 'Observar Aves', 9);
insert into personal_interest(id, value, parent_category_id) values(172, 'Juegos de Mesa/Rompecabezas', 9);
insert into personal_interest(id, value, parent_category_id) values(173, 'Hacer Velas/Jabón', 9);
insert into personal_interest(id, value, parent_category_id) values(174, 'Juegos de Cartas', 9);
insert into personal_interest(id, value, parent_category_id) values(175, 'Ajedrez', 9);
insert into personal_interest(id, value, parent_category_id) values(176, 'Cigarros', 9);
insert into personal_interest(id, value, parent_category_id) values(177, 'Colleccionar', 9);
insert into personal_interest(id, value, parent_category_id) values(178, 'Cómics', 9);
insert into personal_interest(id, value, parent_category_id) values(179, 'Dibujar', 9);
insert into personal_interest(id, value, parent_category_id) values(180, 'Escribir Freelance', 9);
insert into personal_interest(id, value, parent_category_id) values(181, 'Genealogía', 9);
insert into personal_interest(id, value, parent_category_id) values(182, 'Publicaciones', 9);
insert into personal_interest(id, value, parent_category_id) values(183, 'Guitarra', 9);
insert into personal_interest(id, value, parent_category_id) values(184, 'Grabación Casera', 9);
insert into personal_interest(id, value, parent_category_id) values(185, 'Inversionistas y Patentes', 9);
insert into personal_interest(id, value, parent_category_id) values(186, 'Hacer Joyería', 9);
insert into personal_interest(id, value, parent_category_id) values(187, 'Magia e Ilusionismo', 9);
insert into personal_interest(id, value, parent_category_id) values(188, 'Costura/Bordado', 9);
insert into personal_interest(id, value, parent_category_id) values(189, 'Pintura', 9);
insert into personal_interest(id, value, parent_category_id) values(190, 'Fotografía', 9);
insert into personal_interest(id, value, parent_category_id) values(191, 'Radio', 9);
insert into personal_interest(id, value, parent_category_id) values(192, 'Juegos de Actuación', 9);
insert into personal_interest(id, value, parent_category_id) values(193, 'Ciencia Ficción y Fantasía', 9);
insert into personal_interest(id, value, parent_category_id) values(194, 'Scrapbooking', 9);
insert into personal_interest(id, value, parent_category_id) values(195, 'Escribir guiones', 9);
insert into personal_interest(id, value, parent_category_id) values(196, 'Filatelia y Colección de Monedas', 9);
insert into personal_interest(id, value, parent_category_id) values(197, 'Juegos en Computadora', 9);
insert into personal_interest(id, value, parent_category_id) values(198, 'Carpintería', 9);
insert into personal_interest(id, value, parent_category_id) values(199, 'Electrodoméstico', 10);
insert into personal_interest(id, value, parent_category_id) values(200, 'Entretenimiento', 10);
insert into personal_interest(id, value, parent_category_id) values(201, 'Seguridad Ambiental', 10);
insert into personal_interest(id, value, parent_category_id) values(202, 'Jardinería', 10);
insert into personal_interest(id, value, parent_category_id) values(203, 'Reparaciones en el Hogar', 10);
insert into personal_interest(id, value, parent_category_id) values(204, 'Home Theater', 10);
insert into personal_interest(id, value, parent_category_id) values(205, 'Decoración de Interiores', 10);
insert into personal_interest(id, value, parent_category_id) values(206, 'Paisajista', 10);
insert into personal_interest(id, value, parent_category_id) values(207, 'Remodelación y Construcción', 10);
insert into personal_interest(id, value, parent_category_id) values(208, 'Inmigración', 11);
insert into personal_interest(id, value, parent_category_id) values(209, 'Asuntos Legales', 11);
insert into personal_interest(id, value, parent_category_id) values(210, 'Recursos del Gobierno de los Estados Unidos', 11);
insert into personal_interest(id, value, parent_category_id) values(211, 'Política', 11);
insert into personal_interest(id, value, parent_category_id) values(212, 'Comentario', 11);
insert into personal_interest(id, value, parent_category_id) values(213, 'Noticias Internacionales', 12);
insert into personal_interest(id, value, parent_category_id) values(214, 'Noticias Nacionales', 12);
insert into personal_interest(id, value, parent_category_id) values(215, 'Noticias Locales', 12);
insert into personal_interest(id, value, parent_category_id) values(216, 'Inicación a la Inversión', 13);
insert into personal_interest(id, value, parent_category_id) values(217, 'Crédito/Deuda y Préstamos', 13);
insert into personal_interest(id, value, parent_category_id) values(218, 'Noticias Financieras', 13);
insert into personal_interest(id, value, parent_category_id) values(219, 'Planeación Financiera', 13);
insert into personal_interest(id, value, parent_category_id) values(220, 'Fondos de Cobertura', 13);
insert into personal_interest(id, value, parent_category_id) values(221, 'Seguro', 13);
insert into personal_interest(id, value, parent_category_id) values(222, 'Inversión', 13);
insert into personal_interest(id, value, parent_category_id) values(223, 'Fondo Mutual de Inversión', 13);
insert into personal_interest(id, value, parent_category_id) values(224, 'Opciones', 13);
insert into personal_interest(id, value, parent_category_id) values(225, 'Planeación del Retiro', 13);
insert into personal_interest(id, value, parent_category_id) values(226, 'Acciones', 13);
insert into personal_interest(id, value, parent_category_id) values(227, 'Planeación Tributaria', 13);
insert into personal_interest(id, value, parent_category_id) values(228, 'Salir/Andar con', 13);
insert into personal_interest(id, value, parent_category_id) values(229, 'Soporte para Divorcio', 13);
insert into personal_interest(id, value, parent_category_id) values(230, 'Vida Gay', 14);
insert into personal_interest(id, value, parent_category_id) values(231, 'Matrimonio', 14);
insert into personal_interest(id, value, parent_category_id) values(232, 'Vida del Adulto Mayor', 14);
insert into personal_interest(id, value, parent_category_id) values(233, 'Adolescentes', 14);
insert into personal_interest(id, value, parent_category_id) values(234, 'Boda', 14);
insert into personal_interest(id, value, parent_category_id) values(235, 'Específico a una Etnia', 14);
insert into personal_interest(id, value, parent_category_id) values(236, 'Astrología', 14);
insert into personal_interest(id, value, parent_category_id) values(237, 'Biología', 15);
insert into personal_interest(id, value, parent_category_id) values(238, 'Química', 15);
insert into personal_interest(id, value, parent_category_id) values(239, 'Geología', 15);
insert into personal_interest(id, value, parent_category_id) values(240, 'Fenómenos Paranormales', 15);
insert into personal_interest(id, value, parent_category_id) values(241, 'Física', 15);
insert into personal_interest(id, value, parent_category_id) values(242, 'Espacio Exterior/Astronomía', 15);
insert into personal_interest(id, value, parent_category_id) values(243, 'Geografía', 15);
insert into personal_interest(id, value, parent_category_id) values(244, 'Botánica', 15);
insert into personal_interest(id, value, parent_category_id) values(245, 'Clima', 15);
insert into personal_interest(id, value, parent_category_id) values(246, 'Aquarios', 16);
insert into personal_interest(id, value, parent_category_id) values(247, 'Pájaras', 16);
insert into personal_interest(id, value, parent_category_id) values(248, 'Gatos', 16);
insert into personal_interest(id, value, parent_category_id) values(249, 'Perros', 16);
insert into personal_interest(id, value, parent_category_id) values(250, 'Animales Grandes', 16);
insert into personal_interest(id, value, parent_category_id) values(251, 'Reptiles', 16);
insert into personal_interest(id, value, parent_category_id) values(252, 'Medicina Veterinaria', 16);
insert into personal_interest(id, value, parent_category_id) values(253, 'Carreras de Auto', 17);
insert into personal_interest(id, value, parent_category_id) values(254, 'Baseball', 17);
insert into personal_interest(id, value, parent_category_id) values(255, 'Bicicleta', 17);
insert into personal_interest(id, value, parent_category_id) values(256, 'Fisicoculturismo', 17);
insert into personal_interest(id, value, parent_category_id) values(257, 'Boxeo', 17);
insert into personal_interest(id, value, parent_category_id) values(258, 'Canotaje/Kayak', 17);
insert into personal_interest(id, value, parent_category_id) values(259, 'Porrista', 17);
insert into personal_interest(id, value, parent_category_id) values(260, 'Escalada', 17);
insert into personal_interest(id, value, parent_category_id) values(261, 'Cricket', 17);
insert into personal_interest(id, value, parent_category_id) values(262, 'Patinaje en Hielo', 17);
insert into personal_interest(id, value, parent_category_id) values(263, 'Pesca con Mosca', 17);
insert into personal_interest(id, value, parent_category_id) values(264, 'Futbol', 17);
insert into personal_interest(id, value, parent_category_id) values(265, 'Pesca en Agua Dulce', 17);
insert into personal_interest(id, value, parent_category_id) values(266, 'Cacería y Pesca', 17);
insert into personal_interest(id, value, parent_category_id) values(267, 'Golf', 17);
insert into personal_interest(id, value, parent_category_id) values(268, 'Carreras de Caballos', 17);
insert into personal_interest(id, value, parent_category_id) values(269, 'Caballos', 17);
insert into personal_interest(id, value, parent_category_id) values(270, 'Cacería/Tiro', 17);
insert into personal_interest(id, value, parent_category_id) values(271, 'Patinaje Inline', 17);
insert into personal_interest(id, value, parent_category_id) values(272, 'Artes Marciales', 17);
insert into personal_interest(id, value, parent_category_id) values(273, 'Ciclismo de Montaña', 17);
insert into personal_interest(id, value, parent_category_id) values(274, 'Carreras NASCAR', 17);
insert into personal_interest(id, value, parent_category_id) values(275, 'Olimpiadas', 17);
insert into personal_interest(id, value, parent_category_id) values(276, 'Paintball', 17);
insert into personal_interest(id, value, parent_category_id) values(277, 'Poder y Motocicletas', 17);
insert into personal_interest(id, value, parent_category_id) values(278, 'Basketball Profesional', 17);
insert into personal_interest(id, value, parent_category_id) values(279, 'Hockey Profesional', 17);
insert into personal_interest(id, value, parent_category_id) values(280, 'Rodeo', 17);
insert into personal_interest(id, value, parent_category_id) values(281, 'Rugby', 17);
insert into personal_interest(id, value, parent_category_id) values(282, 'Correr/Jogging', 17);
insert into personal_interest(id, value, parent_category_id) values(283, 'Veleo', 17);
insert into personal_interest(id, value, parent_category_id) values(284, 'Pesca en Mar', 17);
insert into personal_interest(id, value, parent_category_id) values(285, 'Buceo', 17);
insert into personal_interest(id, value, parent_category_id) values(286, 'Patineta', 17);
insert into personal_interest(id, value, parent_category_id) values(287, 'Esquiar', 17);
insert into personal_interest(id, value, parent_category_id) values(288, 'Snowboarding', 17);
insert into personal_interest(id, value, parent_category_id) values(289, 'Surfear', 17);
insert into personal_interest(id, value, parent_category_id) values(290, 'Natación', 17);
insert into personal_interest(id, value, parent_category_id) values(291, 'Tenis de Mesa/Ping-Pong', 17);
insert into personal_interest(id, value, parent_category_id) values(292, 'Tenis', 17);
insert into personal_interest(id, value, parent_category_id) values(293, 'Volleyball', 17);
insert into personal_interest(id, value, parent_category_id) values(294, 'Caminata', 17);
insert into personal_interest(id, value, parent_category_id) values(295, 'Esquiar en Agua', 17);
insert into personal_interest(id, value, parent_category_id) values(296, 'Soccer Mundial', 17);
insert into personal_interest(id, value, parent_category_id) values(297, 'Belleza', 18);
insert into personal_interest(id, value, parent_category_id) values(298, 'Arte Corporal', 18);
insert into personal_interest(id, value, parent_category_id) values(299, 'Moda', 18);
insert into personal_interest(id, value, parent_category_id) values(300, 'Joyería', 18);
insert into personal_interest(id, value, parent_category_id) values(301, 'Ropa', 18);
insert into personal_interest(id, value, parent_category_id) values(302, 'Accesorios', 18);
insert into personal_interest(id, value, parent_category_id) values(303, 'Gráficas en 3D', 19);
insert into personal_interest(id, value, parent_category_id) values(304, 'Animación', 19);
insert into personal_interest(id, value, parent_category_id) values(305, 'Software Antivirus', 19);
insert into personal_interest(id, value, parent_category_id) values(306, 'C/C++', 19);
insert into personal_interest(id, value, parent_category_id) values(307, 'Cámaras y Videocámaras', 19);
insert into personal_interest(id, value, parent_category_id) values(308, 'Teléfonos celulares', 19);
insert into personal_interest(id, value, parent_category_id) values(309, 'Vertificación de Computación', 19);
insert into personal_interest(id, value, parent_category_id) values(310, 'Red de Computadoras', 19);
insert into personal_interest(id, value, parent_category_id) values(311, 'Periféricos de Computación', 19);
insert into personal_interest(id, value, parent_category_id) values(312, 'Revista de Computación', 19);
insert into personal_interest(id, value, parent_category_id) values(313, 'Centro de Datos', 19);
insert into personal_interest(id, value, parent_category_id) values(314, 'Base de Datos', 19);
insert into personal_interest(id, value, parent_category_id) values(315, 'Publicaciones en Desktop', 19);
insert into personal_interest(id, value, parent_category_id) values(316, 'Video en Desktop', 19);
insert into personal_interest(id, value, parent_category_id) values(317, 'Correo Electrónico', 19);
insert into personal_interest(id, value, parent_category_id) values(318, 'Software Gráfico', 19);
insert into personal_interest(id, value, parent_category_id) values(319, 'Video/DVD', 19);
insert into personal_interest(id, value, parent_category_id) values(320, 'Tecnología de Internet', 19);
insert into personal_interest(id, value, parent_category_id) values(321, 'Java', 19);
insert into personal_interest(id, value, parent_category_id) values(322, 'Javascript', 19);
insert into personal_interest(id, value, parent_category_id) values(323, 'Linux', 19);
insert into personal_interest(id, value, parent_category_id) values(324, 'Mac OS', 19);
insert into personal_interest(id, value, parent_category_id) values(325, 'Soporte Mac', 19);
insert into personal_interest(id, value, parent_category_id) values(326, 'MP3/MIDI', 19);
insert into personal_interest(id, value, parent_category_id) values(327, 'Conferencia en Red', 19);
insert into personal_interest(id, value, parent_category_id) values(328, 'Redes para Principiantes', 19);
insert into personal_interest(id, value, parent_category_id) values(329, 'Seguridad de la Red', 19);
insert into personal_interest(id, value, parent_category_id) values(330, 'Palmtops/PDAs', 19);
insert into personal_interest(id, value, parent_category_id) values(331, 'Soporte de PCs', 19);
insert into personal_interest(id, value, parent_category_id) values(332, 'Portable', 19);
insert into personal_interest(id, value, parent_category_id) values(333, 'Entretenimiento', 19);
insert into personal_interest(id, value, parent_category_id) values(334, 'Shareware/Freeware', 19);
insert into personal_interest(id, value, parent_category_id) values(335, 'Unix', 19);
insert into personal_interest(id, value, parent_category_id) values(336, 'Visual Basic', 19);
insert into personal_interest(id, value, parent_category_id) values(337, 'Clip Art de la Web', 19);
insert into personal_interest(id, value, parent_category_id) values(338, 'Diseño de Web/HTML', 19);
insert into personal_interest(id, value, parent_category_id) values(339, 'Búsqueda en la Web', 19);
insert into personal_interest(id, value, parent_category_id) values(340, 'Windows', 19);
insert into personal_interest(id, value, parent_category_id) values(341, 'Viajes de Aventura', 20);
insert into personal_interest(id, value, parent_category_id) values(342, 'Africa', 20);
insert into personal_interest(id, value, parent_category_id) values(343, 'Viaje Aéreo', 20);
insert into personal_interest(id, value, parent_category_id) values(344, 'Australia y Nueva Zelanda', 20);
insert into personal_interest(id, value, parent_category_id) values(345, 'Bed & Breakfasts', 20);
insert into personal_interest(id, value, parent_category_id) values(346, 'Viajes Económico', 20);
insert into personal_interest(id, value, parent_category_id) values(347, 'Viaje de Negocios', 20);
insert into personal_interest(id, value, parent_category_id) values(348, 'By US Locale', 20);
insert into personal_interest(id, value, parent_category_id) values(349, 'Campismo', 20);
insert into personal_interest(id, value, parent_category_id) values(350, 'Canada', 20);
insert into personal_interest(id, value, parent_category_id) values(351, 'Caribe', 20);
insert into personal_interest(id, value, parent_category_id) values(352, 'Crusero', 20);
insert into personal_interest(id, value, parent_category_id) values(353, 'Europa del Este', 20);
insert into personal_interest(id, value, parent_category_id) values(354, 'Europa', 20);
insert into personal_interest(id, value, parent_category_id) values(355, 'Francia', 20);
insert into personal_interest(id, value, parent_category_id) values(356, 'Grecia', 20);
insert into personal_interest(id, value, parent_category_id) values(357, 'Luna de Miel', 20);
insert into personal_interest(id, value, parent_category_id) values(358, 'Hoteles', 20);
insert into personal_interest(id, value, parent_category_id) values(359, 'Italia', 20);
insert into personal_interest(id, value, parent_category_id) values(360, 'Japón', 20);
insert into personal_interest(id, value, parent_category_id) values(361, 'México y Centroamérica', 20);
insert into personal_interest(id, value, parent_category_id) values(362, 'Parques Nacionales', 20);
insert into personal_interest(id, value, parent_category_id) values(363, 'Sudamérica', 20);
insert into personal_interest(id, value, parent_category_id) values(364, 'Spas', 20);
insert into personal_interest(id, value, parent_category_id) values(365, 'Parques Temáticos', 20);
insert into personal_interest(id, value, parent_category_id) values(366, 'Viajar con Niños', 20);
insert into personal_interest(id, value, parent_category_id) values(367, 'Reino Unido', 20);
insert into personal_interest(id, value, parent_category_id) values(368, 'Departamento', 21);
insert into personal_interest(id, value, parent_category_id) values(369, 'Arquitectos', 21);
insert into personal_interest(id, value, parent_category_id) values(370, 'Compra/Venta de Casas', 21);
insert into personal_interest(id, value, parent_category_id) values(371, 'Concursos', 22);
insert into personal_interest(id, value, parent_category_id) values(372, 'Cuponeo', 22);
insert into personal_interest(id, value, parent_category_id) values(373, 'Comparativo Motor', 22);
insert into personal_interest(id, value, parent_category_id) values(375, 'Religiones Alternativas', 23);
insert into personal_interest(id, value, parent_category_id) values(376, 'Ateo/Agnóstico', 23);
insert into personal_interest(id, value, parent_category_id) values(377, 'Budismo', 23);
insert into personal_interest(id, value, parent_category_id) values(378, 'Catolicismo', 23);
insert into personal_interest(id, value, parent_category_id) values(379, 'Christianismo', 23);
insert into personal_interest(id, value, parent_category_id) values(380, 'Hinduismo', 23);
insert into personal_interest(id, value, parent_category_id) values(381, 'Islam', 23);
insert into personal_interest(id, value, parent_category_id) values(382, 'Judaismo', 23);
insert into personal_interest(id, value, parent_category_id) values(383, 'Santos de los Últimos Días', 23);
insert into personal_interest(id, value, parent_category_id) values(384, 'Pagano/Wiccano', 23);
insert into personal_interest(id, value, parent_category_id) values(385, 'Social Media', 24);

insert into professional_interest(id, value) values(1, 'Artes y Entretenimiento' );                            
insert into professional_interest(id, value) values(2, 'Automotriz' );                                        
insert into professional_interest(id, value) values(3, 'Negocios' );                                           
insert into professional_interest(id, value) values(4, 'Carreras' );                                           
insert into professional_interest(id, value) values(5, 'Educación' );                                        
insert into professional_interest(id, value) values(6, 'Familia y Formación de los Hijos' );                   
insert into professional_interest(id, value) values(7, 'Salud y Acondicionamiento Físico' );                   
insert into professional_interest(id, value) values(8, 'Comida y Bebida' );                                    
insert into professional_interest(id, value) values(9, 'Pasatiempos e Intereses' );                            
insert into professional_interest(id, value) values(10, 'Hogar y Jardinería' );                                 
insert into professional_interest(id, value) values(11, 'Ley, Gobierno y Política' );                           
insert into professional_interest(id, value) values(12, 'Noticias' );                                           
insert into professional_interest(id, value) values(13, 'Finanzas Personales' );                                
insert into professional_interest(id, value) values(14, 'Sociedad' );                                           
insert into professional_interest(id, value) values(15, 'Ciencias' );                                           
insert into professional_interest(id, value) values(16, 'Mascotas' );                                           
insert into professional_interest(id, value) values(17, 'Deportes' );                                           
insert into professional_interest(id, value) values(18, 'Estilo y Moda' );                                      
insert into professional_interest(id, value) values(19, 'Tecnología y Computación' );                          
insert into professional_interest(id, value) values(20, 'Viajes' );                                             
insert into professional_interest(id, value) values(21, 'Bienes Inmuebles' );                                   
insert into professional_interest(id, value) values(22, 'Compras' );                                        
insert into professional_interest(id, value) values(23, 'Religión y Espiritualidad' );                          
insert into professional_interest(id, value) values(24, 'No Categorizado' );                                    
insert into professional_interest(id, value, parent_category_id) values(25, 'Libros y Literatura', 1);            
insert into professional_interest(id, value, parent_category_id) values(26, 'Celebridades', 1 );                    
insert into professional_interest(id, value, parent_category_id) values(27, 'Bellas Artes', 1);
insert into professional_interest(id, value, parent_category_id) values(28, 'Humor', 1);
insert into professional_interest(id, value, parent_category_id) values(29, 'Películas', 1);
insert into professional_interest(id, value, parent_category_id) values(30, 'Música', 1);
insert into professional_interest(id, value, parent_category_id) values(31, 'Televisión', 1);                                         
insert into professional_interest(id, value, parent_category_id) values(32, 'Auto Partes', 2);
insert into professional_interest(id, value, parent_category_id) values(33, 'Reparación Automotriz', 2);
insert into professional_interest(id, value, parent_category_id) values(34, 'Compra-Venta de Autos', 2);
insert into professional_interest(id, value, parent_category_id) values(35, 'Cultura Automotriz', 2);
insert into professional_interest(id, value, parent_category_id) values(36, 'Certificado de Pre-Uso', 2);
insert into professional_interest(id, value, parent_category_id) values(37, 'Convertible', 2);
insert into professional_interest(id, value, parent_category_id) values(38, 'Coupe', 2);
insert into professional_interest(id, value, parent_category_id) values(39, 'Crossover', 2);
insert into professional_interest(id, value, parent_category_id) values(40, 'Diesel', 2);
insert into professional_interest(id, value, parent_category_id) values(41, 'Vehículo Eléctrico', 2);
insert into professional_interest(id, value, parent_category_id) values(42, 'Hatchback', 2);
insert into professional_interest(id, value, parent_category_id) values(43, 'Híbrido', 2);
insert into professional_interest(id, value, parent_category_id) values(44, 'Lujo', 2);
insert into professional_interest(id, value, parent_category_id) values(45, 'MiniVan', 2);
insert into professional_interest(id, value, parent_category_id) values(46, 'Motocicleta', 2);
insert into professional_interest(id, value, parent_category_id) values(47, 'Navegación', 2);
insert into professional_interest(id, value, parent_category_id) values(48, 'Vehículo Todoterreno', 2);
insert into professional_interest(id, value, parent_category_id) values(49, 'Vehículo de Desempeño', 2);
insert into professional_interest(id, value, parent_category_id) values(50, 'Pickup', 2);
insert into professional_interest(id, value, parent_category_id) values(51, 'Asistencia en el Camino', 2);
insert into professional_interest(id, value, parent_category_id) values(52, 'Sedan', 2);
insert into professional_interest(id, value, parent_category_id) values(53, 'Camiones y Accesorios', 2);
insert into professional_interest(id, value, parent_category_id) values(54, 'Autos Antiguos', 2);
insert into professional_interest(id, value, parent_category_id) values(55, 'Vagoneta', 2);
insert into professional_interest(id, value, parent_category_id) values(56, 'Publicidad', 3);
insert into professional_interest(id, value, parent_category_id) values(57, 'Agricultura', 3);
insert into professional_interest(id, value, parent_category_id) values(58, 'Biotecnología/Biomédico', 3);
insert into professional_interest(id, value, parent_category_id) values(59, 'Software de Negocios', 3);
insert into professional_interest(id, value, parent_category_id) values(60, 'Construcción', 3);
insert into professional_interest(id, value, parent_category_id) values(61, 'Ciencias Forstales', 3);
insert into professional_interest(id, value, parent_category_id) values(62, 'Gobierno', 3);
insert into professional_interest(id, value, parent_category_id) values(63, 'Soluciones Verdes', 3);
insert into professional_interest(id, value, parent_category_id) values(64, 'Recursos Humanos', 3);
insert into professional_interest(id, value, parent_category_id) values(65, 'Logística', 3);
insert into professional_interest(id, value, parent_category_id) values(66, 'Mercadotecnia', 3);
insert into professional_interest(id, value, parent_category_id) values(67, 'Metales', 3);
insert into professional_interest(id, value, parent_category_id) values(68, 'Productividad', 3);
insert into professional_interest(id, value, parent_category_id) values(69, 'Planeación de Carrera', 4);
insert into professional_interest(id, value, parent_category_id) values(70, 'Universidad', 4);
insert into professional_interest(id, value, parent_category_id) values(71, 'Ayuda Financiera', 4);
insert into professional_interest(id, value, parent_category_id) values(72, 'Ferias de Trabajo', 4);
insert into professional_interest(id, value, parent_category_id) values(73, 'Búsqueda de Trabajo', 4);
insert into professional_interest(id, value, parent_category_id) values(74, 'Curriculum Escribir/Aconsejar', 4);
insert into professional_interest(id, value, parent_category_id) values(75, 'Enfermería', 4);
insert into professional_interest(id, value, parent_category_id) values(77, 'Trabajo a Distancia', 4);
insert into professional_interest(id, value, parent_category_id) values(78, 'Militar de los Estados Unidos', 4);
insert into professional_interest(id, value, parent_category_id) values(79, 'Consejo de Carrera', 4);
insert into professional_interest(id, value, parent_category_id) values(80, 'Educación Primaria', 5);
insert into professional_interest(id, value, parent_category_id) values(81, 'Educación para Adultos', 5);
insert into professional_interest(id, value, parent_category_id) values(82, 'Historia del Arte', 5);
insert into professional_interest(id, value, parent_category_id) values(83, 'Adminitración Universitaria', 5);
insert into professional_interest(id, value, parent_category_id) values(84, 'Vida Universitaria', 5);
insert into professional_interest(id, value, parent_category_id) values(85, 'Aprendizaje a Distancia', 5);
insert into professional_interest(id, value, parent_category_id) values(86, 'Inglés como Segunda Lengua', 5);
insert into professional_interest(id, value, parent_category_id) values(87, 'Aprendizaje de Lenguajes', 5);
insert into professional_interest(id, value, parent_category_id) values(88, 'Escuela de Posgrado', 5);
insert into professional_interest(id, value, parent_category_id) values(89, 'Educación en el Hogar', 5);
insert into professional_interest(id, value, parent_category_id) values(90, 'Tarea/Consejos de Estudio', 5);
insert into professional_interest(id, value, parent_category_id) values(91, 'Educadores de Primaria', 5);
insert into professional_interest(id, value, parent_category_id) values(92, 'Escuela Privada', 5);
insert into professional_interest(id, value, parent_category_id) values(93, 'Educación Especial', 5);
insert into professional_interest(id, value, parent_category_id) values(94, 'Estudiando Negocios', 5);
insert into professional_interest(id, value, parent_category_id) values(95, 'Adopción', 6);
insert into professional_interest(id, value, parent_category_id) values(96, 'Bebés e Infantes', 6);
insert into professional_interest(id, value, parent_category_id) values(97, 'Guardería/Pre escolar', 6);
insert into professional_interest(id, value, parent_category_id) values(98, 'Internet Familiar', 6);
insert into professional_interest(id, value, parent_category_id) values(99, 'Formación de Hijos en Primaria', 6);
insert into professional_interest(id, value, parent_category_id) values(100, 'Formación de Adolescentes', 6);
insert into professional_interest(id, value, parent_category_id) values(101, 'Embarazo', 6);
insert into professional_interest(id, value, parent_category_id) values(102, 'Niños con Necesidades Especiales', 6);
insert into professional_interest(id, value, parent_category_id) values(103, 'Cuidados a Adultos Mayores', 6);
insert into professional_interest(id, value, parent_category_id) values(104, 'Ejercicio', 7);
insert into professional_interest(id, value, parent_category_id) values(105, 'Síndrome de Déficit de Atención', 7);
insert into professional_interest(id, value, parent_category_id) values(106, 'SIDA/VIH', 7);
insert into professional_interest(id, value, parent_category_id) values(107, 'Alergias', 7);
insert into professional_interest(id, value, parent_category_id) values(108, 'Medicina Alternativa', 7);
insert into professional_interest(id, value, parent_category_id) values(109, 'Artritis', 7);
insert into professional_interest(id, value, parent_category_id) values(110, 'Asma', 7);
insert into professional_interest(id, value, parent_category_id) values(111, 'Autismo/Desórden del Desarrollo', 7);
insert into professional_interest(id, value, parent_category_id) values(112, 'Desorden Bipolar', 7);
insert into professional_interest(id, value, parent_category_id) values(113, 'Tumor Cerebral', 7);
insert into professional_interest(id, value, parent_category_id) values(114, 'Cáncer', 7);
insert into professional_interest(id, value, parent_category_id) values(115, 'Colesterol', 7);
insert into professional_interest(id, value, parent_category_id) values(116, 'Síndrome de Fatiga Crónica', 7);
insert into professional_interest(id, value, parent_category_id) values(117, 'Dolor Crónico', 7);
insert into professional_interest(id, value, parent_category_id) values(118, 'Catarro y Gripe', 7);
insert into professional_interest(id, value, parent_category_id) values(119, 'Sordera', 7);
insert into professional_interest(id, value, parent_category_id) values(120, 'Cuidado Dental', 7);
insert into professional_interest(id, value, parent_category_id) values(121, 'Depresión', 7);
insert into professional_interest(id, value, parent_category_id) values(122, 'Dermatología', 7);
insert into professional_interest(id, value, parent_category_id) values(123, 'Diabetes', 7);
insert into professional_interest(id, value, parent_category_id) values(124, 'Epilepsia', 7);
insert into professional_interest(id, value, parent_category_id) values(125, 'Gastritis/Reflujo', 7);
insert into professional_interest(id, value, parent_category_id) values(126, 'Dolor de Cabeza/Migraña', 7);
insert into professional_interest(id, value, parent_category_id) values(127, 'Enfermedad del Corazón', 7);
insert into professional_interest(id, value, parent_category_id) values(128, 'Hierbas Medicinales', 7);
insert into professional_interest(id, value, parent_category_id) values(129, 'Sanación Holística', 7);
insert into professional_interest(id, value, parent_category_id) values(130  'Síndrome de Intestino Irritable/Enfermedad de Crohn', 7);
insert into professional_interest(id, value, parent_category_id) values(131, 'Soporte para Casos de Incesto/Abuso', 7);
insert into professional_interest(id, value, parent_category_id) values(132, 'Incontinencia', 7);
insert into professional_interest(id, value, parent_category_id) values(133, 'Infertilidad', 7);
insert into professional_interest(id, value, parent_category_id) values(134, 'Salud Masculina', 7);
insert into professional_interest(id, value, parent_category_id) values(135, 'Nutrición', 7);
insert into professional_interest(id, value, parent_category_id) values(136, 'Ortopedia', 7);
insert into professional_interest(id, value, parent_category_id) values(137, 'Pánico/Ansiedad', 7);
insert into professional_interest(id, value, parent_category_id) values(138, 'Desórdenes', 7);
insert into professional_interest(id, value, parent_category_id) values(139, 'Pediatría', 7);
insert into professional_interest(id, value, parent_category_id) values(140, 'Terapia Física', 7);
insert into professional_interest(id, value, parent_category_id) values(141, 'Psicología/Psiquiatría', 7);
insert into professional_interest(id, value, parent_category_id) values(142, 'Salud del Adulto Mayor', 7);
insert into professional_interest(id, value, parent_category_id) values(143, 'Sexualidad', 7);
insert into professional_interest(id, value, parent_category_id) values(144, 'Desórdenes del Sueño', 7);
insert into professional_interest(id, value, parent_category_id) values(145, 'Dejar de Fumar', 7);
insert into professional_interest(id, value, parent_category_id) values(146, 'Abuso de Sustancias', 7);
insert into professional_interest(id, value, parent_category_id) values(147, 'Enfermedad de la Tiroides', 7);
insert into professional_interest(id, value, parent_category_id) values(148, 'Bajar de Peso', 7);
insert into professional_interest(id, value, parent_category_id) values(149, 'Salud Femenina', 7);
insert into professional_interest(id, value, parent_category_id) values(150, 'Cocina Americana', 8);
insert into professional_interest(id, value, parent_category_id) values(151, 'Parrilla y Plancha', 8);
insert into professional_interest(id, value, parent_category_id) values(152, 'Cajun/Creole', 8);
insert into professional_interest(id, value, parent_category_id) values(153, 'Cocina China', 8);
insert into professional_interest(id, value, parent_category_id) values(154, 'Cocteles/Cerveza', 8);
insert into professional_interest(id, value, parent_category_id) values(155, 'Café/Té', 8);
insert into professional_interest(id, value, parent_category_id) values(156, 'Cocina Específica', 8);
insert into professional_interest(id, value, parent_category_id) values(157, 'Postres y Hornear', 8);
insert into professional_interest(id, value, parent_category_id) values(158, 'Cenar Fuera', 8);
insert into professional_interest(id, value, parent_category_id) values(159, 'Alergías Alimenticias', 8);
insert into professional_interest(id, value, parent_category_id) values(160, 'Cocina Francesa', 8);
insert into professional_interest(id, value, parent_category_id) values(161, 'Salud/Cocina Baja en Grsas', 8);
insert into professional_interest(id, value, parent_category_id) values(162, 'Cocina Italiana', 8);
insert into professional_interest(id, value, parent_category_id) values(163, 'Cocina Japonesa', 8);
insert into professional_interest(id, value, parent_category_id) values(164, 'Cocina Mexicana', 8);
insert into professional_interest(id, value, parent_category_id) values(165, 'Vegana', 8);
insert into professional_interest(id, value, parent_category_id) values(166, 'Vegetariana', 8);
insert into professional_interest(id, value, parent_category_id) values(167, 'Vino', 8);
insert into professional_interest(id, value, parent_category_id) values(168, 'Arte/Tecnología', 9);
insert into professional_interest(id, value, parent_category_id) values(169, 'Manualidades', 9);
insert into professional_interest(id, value, parent_category_id) values(170, 'Trabajo con cuentas/chaquira', 9);
insert into professional_interest(id, value, parent_category_id) values(171, 'Observar Aves', 9);
insert into professional_interest(id, value, parent_category_id) values(172, 'Juegos de Mesa/Rompecabezas', 9);
insert into professional_interest(id, value, parent_category_id) values(173, 'Hacer Velas/Jabón', 9);
insert into professional_interest(id, value, parent_category_id) values(174, 'Juegos de Cartas', 9);
insert into professional_interest(id, value, parent_category_id) values(175, 'Ajedrez', 9);
insert into professional_interest(id, value, parent_category_id) values(176, 'Cigarros', 9);
insert into professional_interest(id, value, parent_category_id) values(177, 'Colleccionar', 9);
insert into professional_interest(id, value, parent_category_id) values(178, 'Cómics', 9);
insert into professional_interest(id, value, parent_category_id) values(179, 'Dibujar', 9);
insert into professional_interest(id, value, parent_category_id) values(180, 'Escribir Freelance', 9);
insert into professional_interest(id, value, parent_category_id) values(181, 'Genealogía', 9);
insert into professional_interest(id, value, parent_category_id) values(182, 'Publicaciones', 9);
insert into professional_interest(id, value, parent_category_id) values(183, 'Guitarra', 9);
insert into professional_interest(id, value, parent_category_id) values(184, 'Grabación Casera', 9);
insert into professional_interest(id, value, parent_category_id) values(185, 'Inversionistas y Patentes', 9);
insert into professional_interest(id, value, parent_category_id) values(186, 'Hacer Joyería', 9);
insert into professional_interest(id, value, parent_category_id) values(187, 'Magia e Ilusionismo', 9);
insert into professional_interest(id, value, parent_category_id) values(188, 'Costura/Bordado', 9);
insert into professional_interest(id, value, parent_category_id) values(189, 'Pintura', 9);
insert into professional_interest(id, value, parent_category_id) values(190, 'Fotografía', 9);
insert into professional_interest(id, value, parent_category_id) values(191, 'Radio', 9);
insert into professional_interest(id, value, parent_category_id) values(192, 'Juegos de Actuación', 9);
insert into professional_interest(id, value, parent_category_id) values(193, 'Ciencia Ficción y Fantasía', 9);
insert into professional_interest(id, value, parent_category_id) values(194, 'Scrapbooking', 9);
insert into professional_interest(id, value, parent_category_id) values(195, 'Escribir guiones', 9);
insert into professional_interest(id, value, parent_category_id) values(196, 'Filatelia y Colección de Monedas', 9);
insert into professional_interest(id, value, parent_category_id) values(197, 'Juegos en Computadora', 9);
insert into professional_interest(id, value, parent_category_id) values(198, 'Carpintería', 9);
insert into professional_interest(id, value, parent_category_id) values(199, 'Electrodoméstico', 10);
insert into professional_interest(id, value, parent_category_id) values(200, 'Entretenimiento', 10);
insert into professional_interest(id, value, parent_category_id) values(201, 'Seguridad Ambiental', 10);
insert into professional_interest(id, value, parent_category_id) values(202, 'Jardinería', 10);
insert into professional_interest(id, value, parent_category_id) values(203, 'Reparaciones en el Hogar', 10);
insert into professional_interest(id, value, parent_category_id) values(204, 'Home Theater', 10);
insert into professional_interest(id, value, parent_category_id) values(205, 'Decoración de Interiores', 10);
insert into professional_interest(id, value, parent_category_id) values(206, 'Paisajista', 10);
insert into professional_interest(id, value, parent_category_id) values(207, 'Remodelación y Construcción', 10);
insert into professional_interest(id, value, parent_category_id) values(208, 'Inmigración', 11);
insert into professional_interest(id, value, parent_category_id) values(209, 'Asuntos Legales', 11);
insert into professional_interest(id, value, parent_category_id) values(210, 'Recursos del Gobierno de los Estados Unidos', 11);
insert into professional_interest(id, value, parent_category_id) values(211, 'Política', 11);
insert into professional_interest(id, value, parent_category_id) values(212, 'Comentario', 11);
insert into professional_interest(id, value, parent_category_id) values(213, 'Noticias Internacionales', 12);
insert into professional_interest(id, value, parent_category_id) values(214, 'Noticias Nacionales', 12);
insert into professional_interest(id, value, parent_category_id) values(215, 'Noticias Locales', 12);
insert into professional_interest(id, value, parent_category_id) values(216, 'Inicación a la Inversión', 13);
insert into professional_interest(id, value, parent_category_id) values(217, 'Crédito/Deuda y Préstamos', 13);
insert into professional_interest(id, value, parent_category_id) values(218, 'Noticias Financieras', 13);
insert into professional_interest(id, value, parent_category_id) values(219, 'Planeación Financiera', 13);
insert into professional_interest(id, value, parent_category_id) values(220, 'Fondos de Cobertura', 13);
insert into professional_interest(id, value, parent_category_id) values(221, 'Seguro', 13);
insert into professional_interest(id, value, parent_category_id) values(222, 'Inversión', 13);
insert into professional_interest(id, value, parent_category_id) values(223, 'Fondo Mutual de Inversión', 13);
insert into professional_interest(id, value, parent_category_id) values(224, 'Opciones', 13);
insert into professional_interest(id, value, parent_category_id) values(225, 'Planeación del Retiro', 13);
insert into professional_interest(id, value, parent_category_id) values(226, 'Acciones', 13);
insert into professional_interest(id, value, parent_category_id) values(227, 'Planeación Tributaria', 13);
insert into professional_interest(id, value, parent_category_id) values(228, 'Salir/Andar con', 13);
insert into professional_interest(id, value, parent_category_id) values(229, 'Soporte para Divorcio', 13);
insert into professional_interest(id, value, parent_category_id) values(230, 'Vida Gay', 14);
insert into professional_interest(id, value, parent_category_id) values(231, 'Matrimonio', 14);
insert into professional_interest(id, value, parent_category_id) values(232, 'Vida del Adulto Mayor', 14);
insert into professional_interest(id, value, parent_category_id) values(233, 'Adolescentes', 14);
insert into professional_interest(id, value, parent_category_id) values(234, 'Boda', 14);
insert into professional_interest(id, value, parent_category_id) values(235, 'Específico a una Etnia', 14);
insert into professional_interest(id, value, parent_category_id) values(236, 'Astrología', 14);
insert into professional_interest(id, value, parent_category_id) values(237, 'Biología', 15);
insert into professional_interest(id, value, parent_category_id) values(238, 'Química', 15);
insert into professional_interest(id, value, parent_category_id) values(239, 'Geología', 15);
insert into professional_interest(id, value, parent_category_id) values(240, 'Fenómenos Paranormales', 15);
insert into professional_interest(id, value, parent_category_id) values(241, 'Física', 15);
insert into professional_interest(id, value, parent_category_id) values(242, 'Espacio Exterior/Astronomía', 15);
insert into professional_interest(id, value, parent_category_id) values(243, 'Geografía', 15);
insert into professional_interest(id, value, parent_category_id) values(244, 'Botánica', 15);
insert into professional_interest(id, value, parent_category_id) values(245, 'Clima', 15);
insert into professional_interest(id, value, parent_category_id) values(246, 'Aquarios', 16);
insert into professional_interest(id, value, parent_category_id) values(247, 'Pájaras', 16);
insert into professional_interest(id, value, parent_category_id) values(248, 'Gatos', 16);
insert into professional_interest(id, value, parent_category_id) values(249, 'Perros', 16);
insert into professional_interest(id, value, parent_category_id) values(250, 'Animales Grandes', 16);
insert into professional_interest(id, value, parent_category_id) values(251, 'Reptiles', 16);
insert into professional_interest(id, value, parent_category_id) values(252, 'Medicina Veterinaria', 16);
insert into professional_interest(id, value, parent_category_id) values(253, 'Carreras de Auto', 17);
insert into professional_interest(id, value, parent_category_id) values(254, 'Baseball', 17);
insert into professional_interest(id, value, parent_category_id) values(255, 'Bicicleta', 17);
insert into professional_interest(id, value, parent_category_id) values(256, 'Fisicoculturismo', 17);
insert into professional_interest(id, value, parent_category_id) values(257, 'Boxeo', 17);
insert into professional_interest(id, value, parent_category_id) values(258, 'Canotaje/Kayak', 17);
insert into professional_interest(id, value, parent_category_id) values(259, 'Porrista', 17);
insert into professional_interest(id, value, parent_category_id) values(260, 'Escalada', 17);
insert into professional_interest(id, value, parent_category_id) values(261, 'Cricket', 17);
insert into professional_interest(id, value, parent_category_id) values(262, 'Patinaje en Hielo', 17);
insert into professional_interest(id, value, parent_category_id) values(263, 'Pesca con Mosca', 17);
insert into professional_interest(id, value, parent_category_id) values(264, 'Futbol', 17);
insert into professional_interest(id, value, parent_category_id) values(265, 'Pesca en Agua Dulce', 17);
insert into professional_interest(id, value, parent_category_id) values(266, 'Cacería y Pesca', 17);
insert into professional_interest(id, value, parent_category_id) values(267, 'Golf', 17);
insert into professional_interest(id, value, parent_category_id) values(268, 'Carreras de Caballos', 17);
insert into professional_interest(id, value, parent_category_id) values(269, 'Caballos', 17);
insert into professional_interest(id, value, parent_category_id) values(270, 'Cacería/Tiro', 17);
insert into professional_interest(id, value, parent_category_id) values(271, 'Patinaje Inline', 17);
insert into professional_interest(id, value, parent_category_id) values(272, 'Artes Marciales', 17);
insert into professional_interest(id, value, parent_category_id) values(273, 'Ciclismo de Montaña', 17);
insert into professional_interest(id, value, parent_category_id) values(274, 'Carreras NASCAR', 17);
insert into professional_interest(id, value, parent_category_id) values(275, 'Olimpiadas', 17);
insert into professional_interest(id, value, parent_category_id) values(276, 'Paintball', 17);
insert into professional_interest(id, value, parent_category_id) values(277, 'Poder y Motocicletas', 17);
insert into professional_interest(id, value, parent_category_id) values(278, 'Basketball Profesional', 17);
insert into professional_interest(id, value, parent_category_id) values(279, 'Hockey Profesional', 17);
insert into professional_interest(id, value, parent_category_id) values(280, 'Rodeo', 17);
insert into professional_interest(id, value, parent_category_id) values(281, 'Rugby', 17);
insert into professional_interest(id, value, parent_category_id) values(282, 'Correr/Jogging', 17);
insert into professional_interest(id, value, parent_category_id) values(283, 'Veleo', 17);
insert into professional_interest(id, value, parent_category_id) values(284, 'Pesca en Mar', 17);
insert into professional_interest(id, value, parent_category_id) values(285, 'Buceo', 17);
insert into professional_interest(id, value, parent_category_id) values(286, 'Patineta', 17);
insert into professional_interest(id, value, parent_category_id) values(287, 'Esquiar', 17);
insert into professional_interest(id, value, parent_category_id) values(288, 'Snowboarding', 17);
insert into professional_interest(id, value, parent_category_id) values(289, 'Surfear', 17);
insert into professional_interest(id, value, parent_category_id) values(290, 'Natación', 17);
insert into professional_interest(id, value, parent_category_id) values(291, 'Tenis de Mesa/Ping-Pong', 17);
insert into professional_interest(id, value, parent_category_id) values(292, 'Tenis', 17);
insert into professional_interest(id, value, parent_category_id) values(293, 'Volleyball', 17);
insert into professional_interest(id, value, parent_category_id) values(294, 'Caminata', 17);
insert into professional_interest(id, value, parent_category_id) values(295, 'Esquiar en Agua', 17);
insert into professional_interest(id, value, parent_category_id) values(296, 'Soccer Mundial', 17);
insert into professional_interest(id, value, parent_category_id) values(297, 'Belleza', 18);
insert into professional_interest(id, value, parent_category_id) values(298, 'Arte Corporal', 18);
insert into professional_interest(id, value, parent_category_id) values(299, 'Moda', 18);
insert into professional_interest(id, value, parent_category_id) values(300, 'Joyería', 18);
insert into professional_interest(id, value, parent_category_id) values(301, 'Ropa', 18);
insert into professional_interest(id, value, parent_category_id) values(302, 'Accesorios', 18);
insert into professional_interest(id, value, parent_category_id) values(303, 'Gráficas en 3D', 19);
insert into professional_interest(id, value, parent_category_id) values(304, 'Animación', 19);
insert into professional_interest(id, value, parent_category_id) values(305, 'Software Antivirus', 19);
insert into professional_interest(id, value, parent_category_id) values(306, 'C/C++', 19);
insert into professional_interest(id, value, parent_category_id) values(307, 'Cámaras y Videocámaras', 19);
insert into professional_interest(id, value, parent_category_id) values(308, 'Teléfonos celulares', 19);
insert into professional_interest(id, value, parent_category_id) values(309, 'Vertificación de Computación', 19);
insert into professional_interest(id, value, parent_category_id) values(310, 'Red de Computadoras', 19);
insert into professional_interest(id, value, parent_category_id) values(311, 'Periféricos de Computación', 19);
insert into professional_interest(id, value, parent_category_id) values(312, 'Revista de Computación', 19);
insert into professional_interest(id, value, parent_category_id) values(313, 'Centro de Datos', 19);
insert into professional_interest(id, value, parent_category_id) values(314, 'Base de Datos', 19);
insert into professional_interest(id, value, parent_category_id) values(315, 'Publicaciones en Desktop', 19);
insert into professional_interest(id, value, parent_category_id) values(316, 'Video en Desktop', 19);
insert into professional_interest(id, value, parent_category_id) values(317, 'Correo Electrónico', 19);
insert into professional_interest(id, value, parent_category_id) values(318, 'Software Gráfico', 19);
insert into professional_interest(id, value, parent_category_id) values(319, 'Video/DVD', 19);
insert into professional_interest(id, value, parent_category_id) values(320, 'Tecnología de Internet', 19);
insert into professional_interest(id, value, parent_category_id) values(321, 'Java', 19);
insert into professional_interest(id, value, parent_category_id) values(322, 'Javascript', 19);
insert into professional_interest(id, value, parent_category_id) values(323, 'Linux', 19);
insert into professional_interest(id, value, parent_category_id) values(324, 'Mac OS', 19);
insert into professional_interest(id, value, parent_category_id) values(325, 'Soporte Mac', 19);
insert into professional_interest(id, value, parent_category_id) values(326, 'MP3/MIDI', 19);
insert into professional_interest(id, value, parent_category_id) values(327, 'Conferencia en Red', 19);
insert into professional_interest(id, value, parent_category_id) values(328, 'Redes para Principiantes', 19);
insert into professional_interest(id, value, parent_category_id) values(329, 'Seguridad de la Red', 19);
insert into professional_interest(id, value, parent_category_id) values(330, 'Palmtops/PDAs', 19);
insert into professional_interest(id, value, parent_category_id) values(331, 'Soporte de PCs', 19);
insert into professional_interest(id, value, parent_category_id) values(332, 'Portable', 19);
insert into professional_interest(id, value, parent_category_id) values(333, 'Entretenimiento', 19);
insert into professional_interest(id, value, parent_category_id) values(334, 'Shareware/Freeware', 19);
insert into professional_interest(id, value, parent_category_id) values(335, 'Unix', 19);
insert into professional_interest(id, value, parent_category_id) values(336, 'Visual Basic', 19);
insert into professional_interest(id, value, parent_category_id) values(337, 'Clip Art de la Web', 19);
insert into professional_interest(id, value, parent_category_id) values(338, 'Diseño de Web/HTML', 19);
insert into professional_interest(id, value, parent_category_id) values(339, 'Búsqueda en la Web', 19);
insert into professional_interest(id, value, parent_category_id) values(340, 'Windows', 19);
insert into professional_interest(id, value, parent_category_id) values(341, 'Viajes de Aventura', 20);
insert into professional_interest(id, value, parent_category_id) values(342, 'Africa', 20);
insert into professional_interest(id, value, parent_category_id) values(343, 'Viaje Aéreo', 20);
insert into professional_interest(id, value, parent_category_id) values(344, 'Australia y Nueva Zelanda', 20);
insert into professional_interest(id, value, parent_category_id) values(345, 'Bed & Breakfasts', 20);
insert into professional_interest(id, value, parent_category_id) values(346, 'Viajes Económico', 20);
insert into professional_interest(id, value, parent_category_id) values(347, 'Viaje de Negocios', 20);
insert into professional_interest(id, value, parent_category_id) values(348, 'By US Locale', 20);
insert into professional_interest(id, value, parent_category_id) values(349, 'Campismo', 20);
insert into professional_interest(id, value, parent_category_id) values(350, 'Canada', 20);
insert into professional_interest(id, value, parent_category_id) values(351, 'Caribe', 20);
insert into professional_interest(id, value, parent_category_id) values(352, 'Crusero', 20);
insert into professional_interest(id, value, parent_category_id) values(353, 'Europa del Este', 20);
insert into professional_interest(id, value, parent_category_id) values(354, 'Europa', 20);
insert into professional_interest(id, value, parent_category_id) values(355, 'Francia', 20);
insert into professional_interest(id, value, parent_category_id) values(356, 'Grecia', 20);
insert into professional_interest(id, value, parent_category_id) values(357, 'Luna de Miel', 20);
insert into professional_interest(id, value, parent_category_id) values(358, 'Hoteles', 20);
insert into professional_interest(id, value, parent_category_id) values(359, 'Italia', 20);
insert into professional_interest(id, value, parent_category_id) values(360, 'Japón', 20);
insert into professional_interest(id, value, parent_category_id) values(361, 'México y Centroamérica', 20);
insert into professional_interest(id, value, parent_category_id) values(362, 'Parques Nacionales', 20);
insert into professional_interest(id, value, parent_category_id) values(363, 'Sudamérica', 20);
insert into professional_interest(id, value, parent_category_id) values(364, 'Spas', 20);
insert into professional_interest(id, value, parent_category_id) values(365, 'Parques Temáticos', 20);
insert into professional_interest(id, value, parent_category_id) values(366, 'Viajar con Niños', 20);
insert into professional_interest(id, value, parent_category_id) values(367, 'Reino Unido', 20);
insert into professional_interest(id, value, parent_category_id) values(368, 'Departamento', 21);
insert into professional_interest(id, value, parent_category_id) values(369, 'Arquitectos', 21);
insert into professional_interest(id, value, parent_category_id) values(370, 'Compra/Venta de Casas', 21);
insert into professional_interest(id, value, parent_category_id) values(371, 'Concursos', 22);
insert into professional_interest(id, value, parent_category_id) values(372, 'Cuponeo', 22);
insert into professional_interest(id, value, parent_category_id) values(373, 'Comparativo Motor', 22);
insert into professional_interest(id, value, parent_category_id) values(375, 'Religiones Alternativas', 23);
insert into professional_interest(id, value, parent_category_id) values(376, 'Ateo/Agnóstico', 23);
insert into professional_interest(id, value, parent_category_id) values(377, 'Budismo', 23);
insert into professional_interest(id, value, parent_category_id) values(378, 'Catolicismo', 23);
insert into professional_interest(id, value, parent_category_id) values(379, 'Christianismo', 23);
insert into professional_interest(id, value, parent_category_id) values(380, 'Hinduismo', 23);
insert into professional_interest(id, value, parent_category_id) values(381, 'Islam', 23);
insert into professional_interest(id, value, parent_category_id) values(382, 'Judaismo', 23);
insert into professional_interest(id, value, parent_category_id) values(383, 'Santos de los Últimos Días', 23);
insert into professional_interest(id, value, parent_category_id) values(384, 'Pagano/Wiccano', 23);
insert into professional_interest(id, value, parent_category_id) values(385, 'Social Media', 24);

INSERT INTO institution VALUES (1, 'Pupilo', 'GTC Consulting' , 'Bahia de Acapulco #2988', 'Tlaquepaque', 63, '45609', 142,'52 133-1221-6072', 'pupilo@gtc.com', 'PUPILO es una innovadora iniciativa sin fines de lucro que crece continuamente gracias al voluntariado de empresarios y profesionales compremetidos con la sociedad.', 'ACTIVE','http://pupilov1/img/logotipos/pupilo-logotipo.svg', '2016-12-13', '2016-12-13');
INSERT INTO institution VALUES (2, 'Lideres del Mañana', 'ITESM' , 'Av. Eugenio Garza Sada 2501 Sur', 'Monterrey', 68, '64849', 142,'52 81-8358-2000', 'paulina.martinez@itesm.mx', ' Líderes del Mañana busca potenciar la formación y el desarrollo de jóvenes mexicanos brillantes y talentosos que, por su condición económica y social, requieren de un apoyo del cien por ciento de beca para estudiar en el Tec.', 'ACTIVE','http://sites/all/themes/lideres/images/logo_lideres.png', '2016-12-13', '2016-12-13');
INSERT INTO institution VALUES (3, 'Incubación de Empresas CIETT', 'UANL' , 'Av. Lázaro Cárdenas 4600 Oriente', 'Monterrey', 68, '64930', 142,'52 81-8329-4000', 'ciett@uanl.mx', 'El objetivo primordial del área de Incubación de Empresas crear y desarrollar micro y pequeñas empresas rentables e innovadoras a través de la asesoría, capacitación, consultoría profesional en cualquier ámbito del quehacer empresarial, así como brindar acompañamiento para facilitar el acceso  a fuentes de financiamiento.', 'ACTIVE','http://ciett.uanl.mx/wp-content/uploads/2016/05/pleca-pags2.jpg', '2016-12-13', '2016-12-13');

INSERT INTO institutional_program VALUES (1, 'Pupilo', 'PUPILO es una  iniciativa innovadora sin fines de lucro que crece continuamente gracias al voluntariado de empresarios y profesionistas compremetidos con la sociedad.', '2016-10-11','2017-10-31',1,1,20, '2016-10-10','http://pupilov1/img/logotipos/pupilo-logotipo.svg', '2016-10-10');
INSERT INTO institutional_program VALUES (2, 'Lideres del Mañana', ' Líderes del Mañana es un programa del Tec de Monterrey que brinda becas del 100% y acompañamiento de mentores exalumnos para guiar a los alumnos en el desarrollo académico, profesional y personal.', '2016-10-11','2017-10-31',2,1,20, '2016-10-10','http://sites/all/themes/lideres/images/logo_lideres.png', '2016-10-10');
INSERT INTO institutional_program VALUES (3, 'Incubación de Empresas CIETT', 'El objetivo primordial del Centro de Innovación y Emprendimiento de Alto Impacto de la UANL es crear y desarrollar micro y pequeñas empresas rentables e innovadoras a través de la asesoría, capacitación y consultoría profesional en cualquier ámbito del quehacer empresarial, así como brindar acompañamiento para facilitar el acceso  a fuentes de financiamiento.', '2016-10-11','2017-10-31',3,1,20, '2016-10-10','http://ciett.uanl.mx/wp-content/uploads/2016/05/pleca-pags2.jpg', '2016-10-10');

insert into institution_affliation_code values (1, 'pupilo', 1, true);
insert into institution_affliation_code values (2, 'lideres', 2, true);
insert into institution_affliation_code values (3, 'biz', 3, true);

INSERT INTO skill(id, value) VALUES (1, 'Liderazgo');
INSERT INTO skill(id, value) VALUES (2, 'Productividad y Administración del tiempo');
INSERT INTO skill(id, value) VALUES (3, 'Emprendimiento');
INSERT INTO skill(id, value) VALUES (4, 'Habilidades de comunicación');

INSERT INTO responsibility VALUES (1, 1, 'Agendar juntas', '2016-12-01', true, true, 1);
INSERT INTO responsibility VALUES (2, 2, 'Dar seguimiento a actividades', '2016-12-01', false, true, 1);
INSERT INTO responsibility VALUES (3, 3, 'Reportar progreso', '2016-12-01', false, true, 1);
INSERT INTO responsibility VALUES (4, 4, 'Evaluar al mentor', '2016-12-01', true, false, 1);
INSERT INTO responsibility VALUES (5, 5, 'Evaluar al mentee', '2016-12-01', false, true, 1);

INSERT INTO goal VALUES (1, 1, 'Estudio de Carrera Universitaria','Investigar sobre el alcance y áreas de conocimiento y oportunidades laborales en las carreras de Ingeniería Química y de Alimentos.', 4, 1, 1, true);
INSERT INTO goal VALUES (2, 2, 'Toma de decisiones','Mejorar el proceso de tomas de decisiones para ser más efectivo.', 1, 1, 1, true);
INSERT INTO goal VALUES (3, 3, 'Nivel de Inglés','Mejorar el nivel actual de inglés escrito y hablado.', 1, 1, 1, true);
INSERT INTO goal VALUES (4, 4, 'Mejorar promedio de calificaciones','Mejorar el promedio actual para poder solicitar becas de universidad.', 1, 1, 1, true);

INSERT INTO task VALUES (1, 'Investigar las áreas de estudio y las oportunidades laborales de las carreras de Ingeniería Química y de Alimentos', 5, true, false, true, 1, 1);
INSERT INTO task VALUES (2, 'Visitar universidades locales que se especialicen en ingenierías Química y de Alimentos', 5, true, false, true, 1, 2);
INSERT INTO task VALUES (3, 'Revisar y explicar el programa de mentoría y sus materiales. Platicar sobre las oportunidades en Ingeniería Química y de Alimentos', 4, false, true, true, 1, 3);
INSERT INTO task VALUES (4, 'Recomendar libros y artículos de planeación de carrera y toma de decisiones.', 7, false, true, true, 2, 4);
INSERT INTO task VALUES (5, 'Leer artículos y recomendar libros sugeridos por el mentor.', 21, true, false, true, 2, 5);
INSERT INTO task VALUES (6, 'Investigar escuelas de inglés y programas', 14, true, false, true, 3, 6);
INSERT INTO task VALUES (7, 'Revisar las escuelas de inglés ique el estudiante haya investigado.', 7, false, true, true, 3, 7);
INSERT INTO task VALUES (8, 'Explicar cómo crear un estrategia de estudio.', 14, false, true, true, 4, 8);
INSERT INTO task VALUES (9, 'Sugerir guías de estudio y estrategias', 7, false, true, true, 4, 9);
INSERT INTO task VALUES (10, 'Sugerir guías de estudio y estrategias', 14, true, false, true, 4, 10);

INSERT INTO useful_link VALUES (1, 'GTC', 'http://gtcconsult.com/', 1, '2016-01-03');
INSERT INTO useful_link VALUES (2, 'ITESM', 'http://tec.mx/', 1, '2016-01-03');
INSERT INTO useful_link VALUES (3, 'UANL', 'http://www.uanl.mx/', 1, '2016-01-03');
INSERT INTO institutional_program_link VALUES (1, 1);
INSERT INTO institutional_program_link VALUES (2, 2);
INSERT INTO institutional_program_link VALUES (3, 3);

INSERT INTO document VALUES (1, 'Escuela ICI', 'https://drive.google.com/file/d/0B4WHaU2mA6WBUEZOUjFMMkRLSmM/view', 1, '2016-12-01', 1, '2016-12-01');
INSERT INTO document VALUES (2, 'CV', 'https://drive.google.com/file/d/0B4WHaU2mA6WBTGJwTWtVZVJzY0k/view', 1, '2016-12-01', 1, '2016-12-01');
INSERT INTO goal_document VALUES (3, 1);
INSERT INTO goal_document VALUES (4, 2);

INSERT INTO useful_link VALUES (4, 'Escuela ICI', 'http://ici.edu.mx/', 1, '2016-01-03');
INSERT INTO useful_link VALUES (5, 'Admisiones Tec', 'http://admision.itesm.mx/programas-academicos', 1, '2016-01-03');
INSERT INTO goal_useful_link VALUES (3, 4);
INSERT INTO goal_useful_link VALUES (4, 5);

INSERT INTO document VALUES (3, 'Presentation', 'https://drive.google.com/file/d/0B4WHaU2mA6WBZUxqV21nallic0U/view', 1, '2016-12-01', 1, '2016-12-01');
INSERT INTO document VALUES (4, 'Banners', 'https://drive.google.com/file/d/0B4WHaU2mA6WBTlpYUG1xcy02OWM/view', 1, '2016-12-01', 1, '2016-12-01');
INSERT INTO document VALUES (5, 'Support Letter ITESM', 'https://drive.google.com/file/d/0B4WHaU2mA6WBb0VvS0lMbWlwZVk/view', 1, '2016-12-01', 1, '2016-12-01');
INSERT INTO program_document VALUES (1, 3);
INSERT INTO program_document VALUES (2, 4);
INSERT INTO program_document VALUES (2, 5);
