INSERT INTO user_role VALUES (1,'SYSTEM_ADMIN');
INSERT INTO user_role VALUES (2,'INSTITUTION_ADMIN');
INSERT INTO user_role VALUES (3,'MENTOR');
INSERT INTO user_role VALUES (4,'MENTEE');

INSERT INTO goal_category VALUES (1,'Leadership and Management Skills');
INSERT INTO goal_category VALUES (2,'Productivity and Time Management Skills');
INSERT INTO goal_category VALUES (3,'Entreprenuership');
INSERT INTO goal_category VALUES (4,'Public Speaking and Communication Skills');

INSERT INTO program_category VALUES (1,'Leadership and Management Skills');
INSERT INTO program_category VALUES (2,'Productivity and Time Management Skills');
INSERT INTO program_category VALUES (3,'Entreprenuership');
INSERT INTO program_category VALUES (4,'Public Speaking and Communication Skills');

INSERT INTO country VALUES (1,'Afghanistan');
INSERT INTO country VALUES (2,'Albania');
INSERT INTO country VALUES (3,'Germany');
INSERT INTO country VALUES (4,'Algeria');
INSERT INTO country VALUES (5,'Andorra');
INSERT INTO country VALUES (6,'Angola');
INSERT INTO country VALUES (7,'Anguilla');
INSERT INTO country VALUES (8,'Antarctica');
INSERT INTO country VALUES (9,'Antigua and Barbuda');
INSERT INTO country VALUES (10,'Netherlands Antilles');
INSERT INTO country VALUES (11,'Saudi Arabia');
INSERT INTO country VALUES (12,'Argentina');
INSERT INTO country VALUES (13,'Armenia');
INSERT INTO country VALUES (14,'Aruba');
INSERT INTO country VALUES (15,'Australia');
INSERT INTO country VALUES (16,'Austria');
INSERT INTO country VALUES (17,'Azerbaijan');
INSERT INTO country VALUES (18,'Belgium');
INSERT INTO country VALUES (19,'Bahamas');
INSERT INTO country VALUES (20,'Bahrain');
INSERT INTO country VALUES (21,'Bangladesh');
INSERT INTO country VALUES (22,'Barbados');
INSERT INTO country VALUES (23,'Belize');
INSERT INTO country VALUES (24,'Benin');
INSERT INTO country VALUES (25,'Bhutan');
INSERT INTO country VALUES (26,'Belarus');
INSERT INTO country VALUES (27,'Myanmar');
INSERT INTO country VALUES (28,'Bolivia');
INSERT INTO country VALUES (29,'Bosnia and Herzegovina');
INSERT INTO country VALUES (30,'Botswana');
INSERT INTO country VALUES (31,'Brazil');
INSERT INTO country VALUES (32,'Brunei');
INSERT INTO country VALUES (33,'Bulgaria');
INSERT INTO country VALUES (34,'Burkina Faso');
INSERT INTO country VALUES (35,'Burundi');
INSERT INTO country VALUES (36,'Cape Verde');
INSERT INTO country VALUES (37,'Cambodia');
INSERT INTO country VALUES (38,'Cameroon');
INSERT INTO country VALUES (39,'Canada');
INSERT INTO country VALUES (40,'Chad');
INSERT INTO country VALUES (41,'Chile');
INSERT INTO country VALUES (42,'China');
INSERT INTO country VALUES (43,'Cyprus');
INSERT INTO country VALUES (44,'Vatican City State');
INSERT INTO country VALUES (45,'Colombia');
INSERT INTO country VALUES (46,'Comoros');
INSERT INTO country VALUES (47,'Congo');
INSERT INTO country VALUES (48,'Congo');
INSERT INTO country VALUES (49,'North Korea');
INSERT INTO country VALUES (50,'South Korea');
INSERT INTO country VALUES (51,'Ivory Coast');
INSERT INTO country VALUES (52,'Costa Rica');
INSERT INTO country VALUES (53,'Croatia');
INSERT INTO country VALUES (54,'Cuba');
INSERT INTO country VALUES (55,'Denmark');
INSERT INTO country VALUES (56,'Dominica');
INSERT INTO country VALUES (57,'Ecuador');
INSERT INTO country VALUES (58,'Egypt');
INSERT INTO country VALUES (59,'El Salvador');
INSERT INTO country VALUES (60,'United Arab Emirates');
INSERT INTO country VALUES (61,'Eritrea');
INSERT INTO country VALUES (62,'Slovakia');
INSERT INTO country VALUES (63,'Slovenia');
INSERT INTO country VALUES (64,'Spain');
INSERT INTO country VALUES (65,'United States of America');
INSERT INTO country VALUES (66,'Estonia');
INSERT INTO country VALUES (67,'Ethiopia');
INSERT INTO country VALUES (68,'Philippines');
INSERT INTO country VALUES (69,'Finland');
INSERT INTO country VALUES (70,'Fiji');
INSERT INTO country VALUES (71,'France');
INSERT INTO country VALUES (72,'Gabon');
INSERT INTO country VALUES (73,'Gambia');
INSERT INTO country VALUES (74,'Georgia');
INSERT INTO country VALUES (75,'Ghana');
INSERT INTO country VALUES (76,'Gibraltar');
INSERT INTO country VALUES (77,'Grenada');
INSERT INTO country VALUES (78,'Greece');
INSERT INTO country VALUES (79,'Greenland');
INSERT INTO country VALUES (80,'Guadeloupe');
INSERT INTO country VALUES (81,'Guam');
INSERT INTO country VALUES (82,'Guatemala');
INSERT INTO country VALUES (83,'French Guiana');
INSERT INTO country VALUES (84,'Guernsey');
INSERT INTO country VALUES (85,'Guinea');
INSERT INTO country VALUES (86,'Equatorial Guinea');
INSERT INTO country VALUES (87,'Guinea-Bissau');
INSERT INTO country VALUES (88,'Guyana');
INSERT INTO country VALUES (89,'Haiti');
INSERT INTO country VALUES (90,'Honduras');
INSERT INTO country VALUES (91,'Hong Kong');
INSERT INTO country VALUES (92,'Hungary');
INSERT INTO country VALUES (93,'India');
INSERT INTO country VALUES (94,'Indonesia');
INSERT INTO country VALUES (95,'Iran');
INSERT INTO country VALUES (96,'Iraq');
INSERT INTO country VALUES (97,'Ireland');
INSERT INTO country VALUES (98,'Bouvet Island');
INSERT INTO country VALUES (99,'Isle of Man');
INSERT INTO country VALUES (100,'Christmas Island');
INSERT INTO country VALUES (101,'Norfolk Island');
INSERT INTO country VALUES (102,'Iceland');
INSERT INTO country VALUES (103,'Bermuda Islands');
INSERT INTO country VALUES (104,'Cayman Islands');
INSERT INTO country VALUES (105,'Cocos (Keeling) Islands');
INSERT INTO country VALUES (106,'Cook Islands');
INSERT INTO country VALUES (107,'Åland Islands');
INSERT INTO country VALUES (108,'Faroe Islands');
INSERT INTO country VALUES (109,'South Georgia and the South Sandwich Islands');
INSERT INTO country VALUES (110,'Heard Island and McDonald Islands');
INSERT INTO country VALUES (111,'Maldives');
INSERT INTO country VALUES (112,'Falkland Islands (Malvinas)');
INSERT INTO country VALUES (113,'Northern Mariana Islands');
INSERT INTO country VALUES (114,'Marshall Islands');
INSERT INTO country VALUES (115,'Pitcairn Islands');
INSERT INTO country VALUES (116,'Solomon Islands');
INSERT INTO country VALUES (117,'Turks and Caicos Islands');
INSERT INTO country VALUES (118,'United States Minor Outlying Islands');
INSERT INTO country VALUES (119,'Virgin Islands');
INSERT INTO country VALUES (120,'United States Virgin Islands');
INSERT INTO country VALUES (121,'Israel');
INSERT INTO country VALUES (122,'Italy');
INSERT INTO country VALUES (123,'Jamaica');
INSERT INTO country VALUES (124,'Japan');
INSERT INTO country VALUES (125,'Jersey');
INSERT INTO country VALUES (126,'Jordan');
INSERT INTO country VALUES (127,'Kazakhstan');
INSERT INTO country VALUES (128,'Kenya');
INSERT INTO country VALUES (129,'Kyrgyzstan');
INSERT INTO country VALUES (130,'Kiribati');
INSERT INTO country VALUES (131,'Kuwait');
INSERT INTO country VALUES (132,'Lebanon');
INSERT INTO country VALUES (133,'Laos');
INSERT INTO country VALUES (134,'Lesotho');
INSERT INTO country VALUES (135,'Latvia');
INSERT INTO country VALUES (136,'Liberia');
INSERT INTO country VALUES (137,'Libya');
INSERT INTO country VALUES (138,'Liechtenstein');
INSERT INTO country VALUES (139,'Lithuania');
INSERT INTO country VALUES (140,'Luxembourg');
INSERT INTO country VALUES (141,'Mexico');
INSERT INTO country VALUES (142,'Monaco');
INSERT INTO country VALUES (143,'Macao');
INSERT INTO country VALUES (144,'Macedonia');
INSERT INTO country VALUES (145,'Madagascar');
INSERT INTO country VALUES (146,'Malaysia');
INSERT INTO country VALUES (147,'Malawi');
INSERT INTO country VALUES (148,'Mali');
INSERT INTO country VALUES (149,'Malta');
INSERT INTO country VALUES (150,'Morocco');
INSERT INTO country VALUES (151,'Martinique');
INSERT INTO country VALUES (152,'Mauritius');
INSERT INTO country VALUES (153,'Mauritania');
INSERT INTO country VALUES (154,'Mayotte');
INSERT INTO country VALUES (155,'Estados Federados de');
INSERT INTO country VALUES (156,'Moldova');
INSERT INTO country VALUES (157,'Mongolia');
INSERT INTO country VALUES (158,'Montenegro');
INSERT INTO country VALUES (159,'Montserrat');
INSERT INTO country VALUES (160,'Mozambique');
INSERT INTO country VALUES (161,'Namibia');
INSERT INTO country VALUES (162,'Nauru');
INSERT INTO country VALUES (163,'Nepal');
INSERT INTO country VALUES (164,'Nicaragua');
INSERT INTO country VALUES (165,'Niger');
INSERT INTO country VALUES (166,'Nigeria');
INSERT INTO country VALUES (167,'Niue');
INSERT INTO country VALUES (168,'Norway');
INSERT INTO country VALUES (169,'New Caledonia');
INSERT INTO country VALUES (170,'New Zealand');
INSERT INTO country VALUES (171,'Oman');
INSERT INTO country VALUES (172,'Netherlands');
INSERT INTO country VALUES (173,'Pakistan');
INSERT INTO country VALUES (174,'Palau');
INSERT INTO country VALUES (175,'Palestine');
INSERT INTO country VALUES (176,'Panama');
INSERT INTO country VALUES (177,'Papua New Guinea');
INSERT INTO country VALUES (178,'Paraguay');
INSERT INTO country VALUES (179,'Peru');
INSERT INTO country VALUES (180,'French Polynesia');
INSERT INTO country VALUES (181,'Poland');
INSERT INTO country VALUES (182,'Portugal');
INSERT INTO country VALUES (183,'Puerto Rico');
INSERT INTO country VALUES (184,'Qatar');
INSERT INTO country VALUES (185,'United Kingdom');
INSERT INTO country VALUES (186,'Central African Republic');
INSERT INTO country VALUES (187,'Czech Republic');
INSERT INTO country VALUES (188,'Dominican Republic');
INSERT INTO country VALUES (189,'Réunion');
INSERT INTO country VALUES (190,'Rwanda');
INSERT INTO country VALUES (191,'Romania');
INSERT INTO country VALUES (192,'Russia');
INSERT INTO country VALUES (193,'Western Sahara');
INSERT INTO country VALUES (194,'Samoa');
INSERT INTO country VALUES (195,'American Samoa');
INSERT INTO country VALUES (196,'Saint Barthélemy');
INSERT INTO country VALUES (197,'Saint Kitts and Nevis');
INSERT INTO country VALUES (198,'San Marino');
INSERT INTO country VALUES (199,'Saint Martin (French part)');
INSERT INTO country VALUES (200,'Saint Pierre and Miquelon');
INSERT INTO country VALUES (201,'Saint Vincent and the Grenadines');
INSERT INTO country VALUES (202,'Ascensión y Tristán de Acuña');
INSERT INTO country VALUES (203,'Saint Lucia');
INSERT INTO country VALUES (204,'Sao Tome and Principe');
INSERT INTO country VALUES (205,'Senegal');
INSERT INTO country VALUES (206,'Serbia');
INSERT INTO country VALUES (207,'Seychelles');
INSERT INTO country VALUES (208,'Sierra Leone');
INSERT INTO country VALUES (209,'Singapore');
INSERT INTO country VALUES (210,'Syria');
INSERT INTO country VALUES (211,'Somalia');
INSERT INTO country VALUES (212,'Sri Lanka');
INSERT INTO country VALUES (213,'South Africa');
INSERT INTO country VALUES (214,'Sudan');
INSERT INTO country VALUES (215,'Sweden');
INSERT INTO country VALUES (216,'Switzerland');
INSERT INTO country VALUES (217,'Suriname');
INSERT INTO country VALUES (218,'Svalbard and Jan Mayen');
INSERT INTO country VALUES (219,'Swaziland');
INSERT INTO country VALUES (220,'Tajikistan');
INSERT INTO country VALUES (221,'Thailand');
INSERT INTO country VALUES (222,'Taiwan');
INSERT INTO country VALUES (223,'Tanzania');
INSERT INTO country VALUES (224,'British Indian Ocean Territory');
INSERT INTO country VALUES (225,'French Southern Territories');
INSERT INTO country VALUES (226,'East Timor');
INSERT INTO country VALUES (227,'Togo');
INSERT INTO country VALUES (228,'Tokelau');
INSERT INTO country VALUES (229,'Tonga');
INSERT INTO country VALUES (230,'Trinidad and Tobago');
INSERT INTO country VALUES (231,'Tunisia');
INSERT INTO country VALUES (232,'Turkmenistan');
INSERT INTO country VALUES (233,'Turkey');
INSERT INTO country VALUES (234,'Tuvalu');
INSERT INTO country VALUES (235,'Ukraine');
INSERT INTO country VALUES (236,'Uganda');
INSERT INTO country VALUES (237,'Uruguay');
INSERT INTO country VALUES (238,'Uzbekistan');
INSERT INTO country VALUES (239,'Vanuatu');
INSERT INTO country VALUES (240,'Venezuela');
INSERT INTO country VALUES (241,'Vietnam');
INSERT INTO country VALUES (242,'Wallis and Futuna');
INSERT INTO country VALUES (243,'Yemen');
INSERT INTO country VALUES (244,'Djibouti');
INSERT INTO country VALUES (245,'Zambia');
INSERT INTO country VALUES (246,'Zimbabwe');

INSERT INTO state VALUES (1,'Alabama',  65);
INSERT INTO state VALUES (2,'Alaska',  65);
INSERT INTO state VALUES (3,'Arizona',  65);
INSERT INTO state VALUES (4,'Arkansas',  65);
INSERT INTO state VALUES (5,'California',  65);
INSERT INTO state VALUES (6,'Colorado',  65);
INSERT INTO state VALUES (7,'Connecticut',  65);
INSERT INTO state VALUES (8,'Delaware',  65);
INSERT INTO state VALUES (9,'Florida',  65);
INSERT INTO state VALUES (10,'Georgia',  65);
INSERT INTO state VALUES (11,'Hawaii',  65);
INSERT INTO state VALUES (12,'Idaho',  65);
INSERT INTO state VALUES (13,'Illinois',  65);
INSERT INTO state VALUES (14,'Indiana',  65);
INSERT INTO state VALUES (15,'Iowa',  65);
INSERT INTO state VALUES (16,'Kansas',  65);
INSERT INTO state VALUES (17,'Kentucky',  65);
INSERT INTO state VALUES (18,'Louisiana',  65);
INSERT INTO state VALUES (19,'Maine',  65);
INSERT INTO state VALUES (20,'Maryland',  65);
INSERT INTO state VALUES (21,'Massachusetts',  65);
INSERT INTO state VALUES (22,'Michigan',  65);
INSERT INTO state VALUES (23,'Minnesota',  65);
INSERT INTO state VALUES (24,'Mississippi',  65);
INSERT INTO state VALUES (25,'Missouri',  65);
INSERT INTO state VALUES (26,'Montana',  65);
INSERT INTO state VALUES (27,'Nebraska',  65);
INSERT INTO state VALUES (28,'Nevada',  65);
INSERT INTO state VALUES (29,'New Hampshire',  65);
INSERT INTO state VALUES (30,'New Jersey',  65);
INSERT INTO state VALUES (31,'New Mexico',  65);
INSERT INTO state VALUES (32,'New York',  65);
INSERT INTO state VALUES (33,'North Carolina',  65);
INSERT INTO state VALUES (34,'North Dakota',  65);
INSERT INTO state VALUES (35,'Ohio',  65);
INSERT INTO state VALUES (36,'Oklahoma',  65);
INSERT INTO state VALUES (37,'Oregon',  65);
INSERT INTO state VALUES (38,'Pennsylvania',  65);
INSERT INTO state VALUES (39,'Rhode Island',  65);
INSERT INTO state VALUES (40,'South Carolina',  65);
INSERT INTO state VALUES (41,'South Dakota',  65);
INSERT INTO state VALUES (42,'Tennessee',  65);
INSERT INTO state VALUES (43,'Texas',  65);
INSERT INTO state VALUES (44,'Utah',  65);
INSERT INTO state VALUES (45,'Vermont',  65);
INSERT INTO state VALUES (46,'Virginia',  65);
INSERT INTO state VALUES (47,'Washington',  65);
INSERT INTO state VALUES (48,'West Virginia',  65);
INSERT INTO state VALUES (49,'Wisconsin',  65);
INSERT INTO state VALUES (50,'Wyoming',  65);

INSERT INTO state VALUES (51,'Aguascalientes', 141);
INSERT INTO state VALUES (52,'Baja California', 141);
INSERT INTO state VALUES (53,'Baja California Sur', 141);
INSERT INTO state VALUES (54,'Campeche', 141);
INSERT INTO state VALUES (55,'Chiapas', 141);
INSERT INTO state VALUES (56,'Chihuahua', 141);
INSERT INTO state VALUES (57,'Coahuila', 141);
INSERT INTO state VALUES (58,'Colima', 141);
INSERT INTO state VALUES (59,'Durango', 141);
INSERT INTO state VALUES (60,'Guanajuato', 141);
INSERT INTO state VALUES (61,'Guerrero', 141);
INSERT INTO state VALUES (62,'Hidalgo', 141);
INSERT INTO state VALUES (63,'Jalisco', 141);
INSERT INTO state VALUES (64,'México', 141);
INSERT INTO state VALUES (65,'Michoacán', 141);
INSERT INTO state VALUES (66,'Morelos', 141);
INSERT INTO state VALUES (67,'Nayarit', 141);
INSERT INTO state VALUES (68,'Nuevo León', 141);
INSERT INTO state VALUES (69,'Oaxaca', 141);
INSERT INTO state VALUES (70,'Puebla', 141);
INSERT INTO state VALUES (71,'Querétaro', 141);
INSERT INTO state VALUES (72,'Quintana Roo', 141);
INSERT INTO state VALUES (73,'San Luis Potosí', 141);
INSERT INTO state VALUES (74,'Sinaloa', 141);
INSERT INTO state VALUES (75,'Sonora', 141);
INSERT INTO state VALUES (76,'Tabasco', 141);
INSERT INTO state VALUES (77,'Tamaulipas', 141);
INSERT INTO state VALUES (78,'Tlaxcala', 141);
INSERT INTO state VALUES (79,'Veracruz', 141);
INSERT INTO state VALUES (80,'Yucatán', 141);
INSERT INTO state VALUES (81,'Zacatecas', 141);

INSERT INTO user VALUES (1, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'System', 'Admin', 'admin@mentorme.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-01','ACTIVE', NULL, NULL, NULL, false, true, '7583 Classon Avenue', 'Brooklyn',32,65,'11205',-73.9617176,40.6978877, '2016-10-01');

INSERT INTO personal_interest(id, value) VALUES (1,'Arts & Entertainment');
INSERT INTO personal_interest(id, value) VALUES (2,'Automotive');
INSERT INTO personal_interest(id, value) VALUES (3,'Business');
INSERT INTO personal_interest(id, value) VALUES (4,'Careers');
INSERT INTO personal_interest(id, value) VALUES (5,'Education');
INSERT INTO personal_interest(id, value) VALUES (6,'Family & Parenting');
INSERT INTO personal_interest(id, value) VALUES (7,'Health & Fitness');
INSERT INTO personal_interest(id, value) VALUES (8,'Food & Drink');
INSERT INTO personal_interest(id, value) VALUES (9,'Hobbies & Interest');
INSERT INTO personal_interest(id, value) VALUES (10,'Home & Garden');
INSERT INTO personal_interest(id, value) VALUES (11,'Law, Gov''t & Politics');
INSERT INTO personal_interest(id, value) VALUES (12,'News');
INSERT INTO personal_interest(id, value) VALUES (13,'Personal Finance');
INSERT INTO personal_interest(id, value) VALUES (14,'Society');
INSERT INTO personal_interest(id, value) VALUES (15,'Science');
INSERT INTO personal_interest(id, value) VALUES (16,'Pets');
INSERT INTO personal_interest(id, value) VALUES (17,'Sports');
INSERT INTO personal_interest(id, value) VALUES (18,'Style & Fashion');
INSERT INTO personal_interest(id, value) VALUES (19,'Technology & Computing');
INSERT INTO personal_interest(id, value) VALUES (20,'Travel');
INSERT INTO personal_interest(id, value) VALUES (21,'Real Estate');
INSERT INTO personal_interest(id, value) VALUES (22,'Shopping');
INSERT INTO personal_interest(id, value) VALUES (23,'Religion & Spirituality');
INSERT INTO personal_interest(id, value) VALUES (24,'Uncategorized');
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (25,'Books & Literature',1);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (26,'Celebrity Fan/Gossip',1);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (27,'Fine Art',1);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (28,'Humor',1);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (29,'Movies',1);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (30,'Music',1);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (31,'Television',1);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (32,'Auto Parts',2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (33,'Auto Repair', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (34,'Buying/Selling Cars', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (35,'Car Culture', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (36,'Certified Pre-Owned', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (37,'Convertible', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (38,'Coupe', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (39,'Crossover', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (40,'Diesel', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (41,'Electric Vehicle', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (42,'Hatchback', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (43,'Hybrid', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (44,'Luxury', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (45,'MiniVan', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (46,'Motorcycles', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (47,'Navigation', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (48,'Off-Road Vehicles', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (49,'Performance Vehicles', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (50,'Pickup', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (51,'Road-Side Assistance', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (52,'Sedan', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (53,'Trucks & Accessories', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (54,'Vintage Cars', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (55,'Wagon', 2);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (56,'Advertising', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (57,'Agriculture', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (58,'Biotech/Biomedical', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (59,'Business Software', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (60,'Construction', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (61,'Forestry', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (62,'Government', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (63,'Green Solutions', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (64,'Human Resources', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (65,'Logistics', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (66,'Marketing', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (67,'Metals', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (68,'Productivity', 3);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (69,'Career Planning', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (70,'College', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (71,'Financial Aid', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (72,'Job Fairs', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (73,'Job Search', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (74,'Resume Writing/Advice', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (75,'Nursing', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (76,'Scholarships', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (77,'Telecommuting', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (78,'U.S. Military', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (79,'Career Advice', 4);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (80,'7-12 Education', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (81,'Adult Education', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (82,'Art History', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (83,'College Administration', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (84,'College Life', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (85,'Distance Learning', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (86,'English as a 2nd Language', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (87,'Language Learning', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (88,'Graduate School', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (89,'Homeschooling', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (90,'Homework/Study Tips', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (91,'K-6 Educators', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (92,'Private School', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (93,'Special Education', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (94,'Studying Business', 5);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (95,'Adoption', 6);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (96,'Babies & Toddlers', 6);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (97,'Daycare/Pre School', 6);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (98,'Family Internet', 6);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (99,'Parenting - K-6 Kids', 6);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (100,'Parenting Teens', 6);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (101,'Pregnancy', 6);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (102,'Special Needs Kids', 6);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (103,'Eldercare', 6);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (104,'Exercise', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (105,'A.D.D.', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (106,'AIDS/HIV', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (107,'Allergies', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (108,'Alternative Medicine', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (109,'Arthritis', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (110,'Asthma', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (111,'Autism/PDD', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (112,'Bipolar Disorder', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (113,'Brain Tumor', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (114,'Cancer', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (115,'Cholesterol', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (116,'Chronic Fatigue Syndrome', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (117,'Chronic Pain', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (118,'Cold & Flu', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (119,'Deafness', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (120,'Dental Care', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (121,'Depression', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (122,'Dermatology', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (123,'Diabetes', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (124,'Epilepsy', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (125,'GERD/Acid Reflux', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (126,'Headaches/Migraines', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (127,'Heart Disease', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (128,'Herbs for Health', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (129,'Holistic Healing', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (130,'IBS/Crohn''s Disease', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (131,'Incest/Abuse Support', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (132,'Incontinence', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (133,'Infertility', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (134,'Men''s Health', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (135,'Nutrition', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (136,'Orthopedics', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (137,'Panic/Anxiety', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (138,'Disorders', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (139,'Pediatrics', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (140,'Physical Therapy', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (141,'Psychology/Psychiatry', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (142,'Senior Health', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (143,'Sexuality', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (144,'Sleep Disorders', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (145,'Smoking Cessation', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (146,'Substance Abuse', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (147,'Thyroid Disease', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (148,'Weight Loss', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (149,'Women''s Health', 7);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (150,'American Cuisine', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (151,'Barbecues & Grilling', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (152,'Cajun/Creole', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (153,'Chinese Cuisine', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (154,'Cocktails/Beer', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (155,'Coffee/Tea', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (156,'Cuisine-Specific', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (157,'Desserts & Baking', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (158,'Dining Out', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (159,'Food Allergies', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (160,'French Cuisine', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (161,'Health/LowFat Cooking', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (162,'Italian Cuisine', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (163,'Japanese Cuisine', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (164,'Mexican Cuisine', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (165,'Vegan', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (166,'Vegetarian', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (167,'Wine', 8);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (168,'Art/Technology', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (169,'Arts & Crafts', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (170,'Beadwork', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (171,'Birdwatching', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (172,'Board Games/Puzzles', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (173,'Candle & Soap Making', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (174,'Card Games', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (175,'Chess', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (176,'Cigars', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (177,'Collecting', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (178,'Comic Books', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (179,'Drawing/Sketching', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (180,'Freelance Writing', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (181,'Genealogy', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (182,'Getting Published', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (183,'Guitar', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (184,'Home Recording', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (185,'Investors & Patents', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (186,'Jewelry Making', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (187,'Magic & Illusion', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (188,'Needlework', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (189,'Painting', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (190,'Photography', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (191,'Radio', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (192,'Roleplaying Games', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (193,'Sci-Fi & Fantasy', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (194,'Scrapbooking', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (195,'Screenwriting', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (196,'Stamps & Coins', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (197,'Video & Computer Games', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (198,'Woodworking', 9);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (199,'Appliances', 10);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (200,'Entertaining', 10);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (201,'Environmental Safety', 10);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (202,'Gardening', 10);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (203,'Home Repair', 10);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (204,'Home Theater', 10);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (205,'Interior Decorating', 10);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (206,'Landscaping', 10);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (207,'Remodeling & Construction', 10);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (208,'Immigration', 11);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (209,'Legal Issues', 11);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (210,'U.S. Government Resources', 11);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (211,'Politics', 11);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (212,'Commentary', 11);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (213,'International News', 12);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (214,'National News', 12);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (215,'Local News', 12);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (216,'Beginning Investing', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (217,'Credit/Debt & Loans', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (218,'Financial News', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (219,'Financial Planning', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (220,'Hedge Fund', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (221,'Insurance', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (222,'Investing', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (223,'Mutual Funds', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (224,'Options', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (225,'Retirement Planning', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (226,'Stocks', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (227,'Tax Planning', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (228,'Dating', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (229,'Divorce Support', 13);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (230,'Gay Life', 14);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (231,'Marriage', 14);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (232,'Senior Living', 14);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (233,'Teens', 14);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (234,'Weddings', 14);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (235,'Ethnic Specific', 14);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (236,'Astrology', 14);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (237,'Biology', 15);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (238,'Chemistry', 15);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (239,'Geology', 15);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (240,'Paranormal Phenomena', 15);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (241,'Physics', 15);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (242,'Space/Astronomy', 15);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (243,'Geography', 15);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (244,'Botany', 15);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (245,'Weather', 15);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (246,'Aquariums', 16);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (247,'Birds', 16);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (248,'Cats', 16);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (249,'Dogs', 16);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (250,'Large Animals', 16);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (251,'Reptiles', 16);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (252,'Veterinary Medicine', 16);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (253,'Auto Racing', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (254,'Baseball', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (255,'Bicycling', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (256,'Bodybuilding', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (257,'Boxing', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (258,'Canoeing/Kayaking', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (259,'Cheerleading', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (260,'Climbing', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (261,'Cricket', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (262,'Figure Skating', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (263,'Fly Fishing', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (264,'Football', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (265,'Freshwater Fishing', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (266,'Game & Fish', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (267,'Golf', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (268,'Horse Racing', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (269,'Horses', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (270,'Hunting/Shooting', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (271,'Inline Skating', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (272,'Martial Arts', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (273,'Mountain Biking', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (274,'NASCAR Racing', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (275,'Olympics', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (276,'Paintball', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (277,'Power & Motorcycles', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (278,'Pro Basketball', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (279,'Pro Ice Hockey', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (280,'Rodeo', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (281,'Rugby', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (282,'Running/Jogging', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (283,'Sailing', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (284,'Saltwater Fishing', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (285,'Scuba Diving', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (286,'Skateboarding', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (287,'Skiing', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (288,'Snowboarding', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (289,'Surfing/Bodyboarding', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (290,'Swimming', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (291,'Table Tennis/Ping-Pong', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (292,'Tennis', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (293,'Volleyball', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (294,'Walking', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (295,'Waterski/Wakeboard', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (296,'World Soccer', 17);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (297,'Beauty', 18);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (298,'Body Art', 18);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (299,'Fashion', 18);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (300,'Jewelry', 18);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (301,'Clothing', 18);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (302,'Accessories', 18);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (303,'3-D Graphics', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (304,'Animation', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (305,'Antivirus Software', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (306,'C/C++', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (307,'Cameras & Camcorders', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (308,'Cell Phones', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (309,'Computer Certification', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (310,'Computer Networking', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (311,'Computer Peripherals', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (312,'Computer Reviews', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (313,'Data Centers', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (314,'Databases', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (315,'Desktop Publishing', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (316,'Desktop Video', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (317,'Email', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (318,'Graphics Software', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (319,'Home Video/DVD', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (320,'Internet Technology', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (321,'Java', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (322,'JavaScript', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (323,'Linux', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (324,'Mac OS', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (325,'Mac Support', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (326,'MP3/MIDI', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (327,'Net Conferencing', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (328,'Net for Beginners', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (329,'Network Security', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (330,'Palmtops/PDAs', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (331,'PC Support', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (332,'Portable', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (333,'Entertainment', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (334,'Shareware/Freeware', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (335,'Unix', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (336,'Visual Basic', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (337,'Web Clip Art', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (338,'Web Design/HTML', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (339,'Web Search', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (340,'Windows', 19);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (341,'Adventure Travel', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (342,'Africa', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (343,'Air Travel', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (344,'Australia & New Zealand', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (345,'Bed & Breakfasts', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (346,'Budget Travel', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (347,'Business Travel', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (348,'By US Locale', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (349,'Camping', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (350,'Canada', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (351,'Caribbean', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (352,'Cruises', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (353,'Eastern Europe', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (354,'Europe', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (355,'France', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (356,'Greece', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (357,'Honeymoons/Getaways', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (358,'Hotels', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (359,'Italy', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (360,'Japan', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (361,'Mexico & Central America', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (362,'National Parks', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (363,'South America', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (364,'Spas', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (365,'Theme Parks', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (366,'Traveling with Kids', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (367,'United Kingdom', 20);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (368,'Apartments', 21);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (369,'Architects', 21);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (370,'Buying/Selling Homes', 21);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (371,'Contests & Freebies', 22);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (372,'Couponing', 22);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (373,'Comparison Engines', 22);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (375,'Alternative Religions', 23);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (376,'Atheism/Agnosticism', 23);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (377,'Buddhism', 23);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (378,'Catholicism', 23);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (379,'Christianity', 23);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (380,'Hinduism', 23);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (381,'Islam', 23);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (382,'Judaism', 23);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (383,'Latter-Day Saints', 23);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (384,'Pagan/Wiccan', 23);
INSERT INTO personal_interest(id, value, parent_category_id) VALUES (385,'Social Media', 24);

INSERT INTO professional_interest(id, value) VALUES (1,'Arts & Entertainment');
INSERT INTO professional_interest(id, value) VALUES (2,'Automotive');
INSERT INTO professional_interest(id, value) VALUES (3,'Business');
INSERT INTO professional_interest(id, value) VALUES (4,'Careers');
INSERT INTO professional_interest(id, value) VALUES (5,'Education');
INSERT INTO professional_interest(id, value) VALUES (6,'Family & Parenting');
INSERT INTO professional_interest(id, value) VALUES (7,'Health & Fitness');
INSERT INTO professional_interest(id, value) VALUES (8,'Food & Drink');
INSERT INTO professional_interest(id, value) VALUES (9,'Hobbies & Interest');
INSERT INTO professional_interest(id, value) VALUES (10,'Home & Garden');
INSERT INTO professional_interest(id, value) VALUES (11,'Law, Gov''t & Politics');
INSERT INTO professional_interest(id, value) VALUES (12,'News');
INSERT INTO professional_interest(id, value) VALUES (13,'Personal Finance');
INSERT INTO professional_interest(id, value) VALUES (14,'Society');
INSERT INTO professional_interest(id, value) VALUES (15,'Science');
INSERT INTO professional_interest(id, value) VALUES (16,'Pets');
INSERT INTO professional_interest(id, value) VALUES (17,'Sports');
INSERT INTO professional_interest(id, value) VALUES (18,'Style & Fashion');
INSERT INTO professional_interest(id, value) VALUES (19,'Technology & Computing');
INSERT INTO professional_interest(id, value) VALUES (20,'Travel');
INSERT INTO professional_interest(id, value) VALUES (21,'Real Estate');
INSERT INTO professional_interest(id, value) VALUES (22,'Shopping');
INSERT INTO professional_interest(id, value) VALUES (23,'Religion & Spirituality');
INSERT INTO professional_interest(id, value) VALUES (24,'Uncategorized');
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (25,'Books & Literature',1);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (26,'Celebrity Fan/Gossip',1);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (27,'Fine Art',1);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (28,'Humor',1);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (29,'Movies',1);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (30,'Music',1);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (31,'Television',1);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (32,'Auto Parts',2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (33,'Auto Repair', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (34,'Buying/Selling Cars', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (35,'Car Culture', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (36,'Certified Pre-Owned', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (37,'Convertible', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (38,'Coupe', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (39,'Crossover', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (40,'Diesel', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (41,'Electric Vehicle', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (42,'Hatchback', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (43,'Hybrid', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (44,'Luxury', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (45,'MiniVan', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (46,'Motorcycles', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (47,'Navigation', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (48,'Off-Road Vehicles', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (49,'Performance Vehicles', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (50,'Pickup', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (51,'Road-Side Assistance', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (52,'Sedan', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (53,'Trucks & Accessories', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (54,'Vintage Cars', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (55,'Wagon', 2);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (56,'Advertising', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (57,'Agriculture', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (58,'Biotech/Biomedical', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (59,'Business Software', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (60,'Construction', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (61,'Forestry', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (62,'Government', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (63,'Green Solutions', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (64,'Human Resources', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (65,'Logistics', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (66,'Marketing', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (67,'Metals', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (68,'Productivity', 3);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (69,'Career Planning', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (70,'College', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (71,'Financial Aid', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (72,'Job Fairs', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (73,'Job Search', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (74,'Resume Writing/Advice', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (75,'Nursing', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (76,'Scholarships', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (77,'Telecommuting', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (78,'U.S. Military', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (79,'Career Advice', 4);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (80,'7-12 Education', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (81,'Adult Education', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (82,'Art History', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (83,'College Administration', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (84,'College Life', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (85,'Distance Learning', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (86,'English as a 2nd Language', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (87,'Language Learning', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (88,'Graduate School', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (89,'Homeschooling', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (90,'Homework/Study Tips', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (91,'K-6 Educators', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (92,'Private School', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (93,'Special Education', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (94,'Studying Business', 5);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (95,'Adoption', 6);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (96,'Babies & Toddlers', 6);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (97,'Daycare/Pre School', 6);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (98,'Family Internet', 6);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (99,'Parenting - K-6 Kids', 6);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (100,'Parenting Teens', 6);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (101,'Pregnancy', 6);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (102,'Special Needs Kids', 6);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (103,'Eldercare', 6);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (104,'Exercise', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (105,'A.D.D.', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (106,'AIDS/HIV', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (107,'Allergies', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (108,'Alternative Medicine', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (109,'Arthritis', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (110,'Asthma', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (111,'Autism/PDD', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (112,'Bipolar Disorder', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (113,'Brain Tumor', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (114,'Cancer', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (115,'Cholesterol', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (116,'Chronic Fatigue Syndrome', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (117,'Chronic Pain', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (118,'Cold & Flu', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (119,'Deafness', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (120,'Dental Care', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (121,'Depression', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (122,'Dermatology', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (123,'Diabetes', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (124,'Epilepsy', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (125,'GERD/Acid Reflux', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (126,'Headaches/Migraines', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (127,'Heart Disease', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (128,'Herbs for Health', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (129,'Holistic Healing', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (130,'IBS/Crohn''s Disease', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (131,'Incest/Abuse Support', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (132,'Incontinence', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (133,'Infertility', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (134,'Men''s Health', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (135,'Nutrition', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (136,'Orthopedics', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (137,'Panic/Anxiety', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (138,'Disorders', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (139,'Pediatrics', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (140,'Physical Therapy', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (141,'Psychology/Psychiatry', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (142,'Senior Health', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (143,'Sexuality', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (144,'Sleep Disorders', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (145,'Smoking Cessation', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (146,'Substance Abuse', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (147,'Thyroid Disease', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (148,'Weight Loss', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (149,'Women''s Health', 7);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (150,'American Cuisine', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (151,'Barbecues & Grilling', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (152,'Cajun/Creole', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (153,'Chinese Cuisine', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (154,'Cocktails/Beer', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (155,'Coffee/Tea', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (156,'Cuisine-Specific', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (157,'Desserts & Baking', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (158,'Dining Out', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (159,'Food Allergies', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (160,'French Cuisine', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (161,'Health/LowFat Cooking', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (162,'Italian Cuisine', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (163,'Japanese Cuisine', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (164,'Mexican Cuisine', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (165,'Vegan', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (166,'Vegetarian', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (167,'Wine', 8);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (168,'Art/Technology', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (169,'Arts & Crafts', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (170,'Beadwork', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (171,'Birdwatching', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (172,'Board Games/Puzzles', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (173,'Candle & Soap Making', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (174,'Card Games', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (175,'Chess', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (176,'Cigars', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (177,'Collecting', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (178,'Comic Books', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (179,'Drawing/Sketching', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (180,'Freelance Writing', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (181,'Genealogy', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (182,'Getting Published', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (183,'Guitar', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (184,'Home Recording', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (185,'Investors & Patents', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (186,'Jewelry Making', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (187,'Magic & Illusion', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (188,'Needlework', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (189,'Painting', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (190,'Photography', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (191,'Radio', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (192,'Roleplaying Games', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (193,'Sci-Fi & Fantasy', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (194,'Scrapbooking', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (195,'Screenwriting', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (196,'Stamps & Coins', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (197,'Video & Computer Games', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (198,'Woodworking', 9);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (199,'Appliances', 10);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (200,'Entertaining', 10);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (201,'Environmental Safety', 10);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (202,'Gardening', 10);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (203,'Home Repair', 10);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (204,'Home Theater', 10);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (205,'Interior Decorating', 10);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (206,'Landscaping', 10);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (207,'Remodeling & Construction', 10);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (208,'Immigration', 11);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (209,'Legal Issues', 11);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (210,'U.S. Government Resources', 11);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (211,'Politics', 11);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (212,'Commentary', 11);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (213,'International News', 12);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (214,'National News', 12);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (215,'Local News', 12);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (216,'Beginning Investing', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (217,'Credit/Debt & Loans', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (218,'Financial News', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (219,'Financial Planning', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (220,'Hedge Fund', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (221,'Insurance', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (222,'Investing', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (223,'Mutual Funds', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (224,'Options', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (225,'Retirement Planning', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (226,'Stocks', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (227,'Tax Planning', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (228,'Dating', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (229,'Divorce Support', 13);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (230,'Gay Life', 14);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (231,'Marriage', 14);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (232,'Senior Living', 14);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (233,'Teens', 14);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (234,'Weddings', 14);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (235,'Ethnic Specific', 14);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (236,'Astrology', 14);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (237,'Biology', 15);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (238,'Chemistry', 15);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (239,'Geology', 15);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (240,'Paranormal Phenomena', 15);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (241,'Physics', 15);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (242,'Space/Astronomy', 15);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (243,'Geography', 15);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (244,'Botany', 15);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (245,'Weather', 15);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (246,'Aquariums', 16);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (247,'Birds', 16);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (248,'Cats', 16);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (249,'Dogs', 16);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (250,'Large Animals', 16);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (251,'Reptiles', 16);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (252,'Veterinary Medicine', 16);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (253,'Auto Racing', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (254,'Baseball', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (255,'Bicycling', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (256,'Bodybuilding', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (257,'Boxing', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (258,'Canoeing/Kayaking', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (259,'Cheerleading', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (260,'Climbing', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (261,'Cricket', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (262,'Figure Skating', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (263,'Fly Fishing', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (264,'Football', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (265,'Freshwater Fishing', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (266,'Game & Fish', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (267,'Golf', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (268,'Horse Racing', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (269,'Horses', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (270,'Hunting/Shooting', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (271,'Inline Skating', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (272,'Martial Arts', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (273,'Mountain Biking', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (274,'NASCAR Racing', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (275,'Olympics', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (276,'Paintball', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (277,'Power & Motorcycles', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (278,'Pro Basketball', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (279,'Pro Ice Hockey', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (280,'Rodeo', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (281,'Rugby', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (282,'Running/Jogging', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (283,'Sailing', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (284,'Saltwater Fishing', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (285,'Scuba Diving', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (286,'Skateboarding', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (287,'Skiing', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (288,'Snowboarding', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (289,'Surfing/Bodyboarding', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (290,'Swimming', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (291,'Table Tennis/Ping-Pong', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (292,'Tennis', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (293,'Volleyball', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (294,'Walking', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (295,'Waterski/Wakeboard', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (296,'World Soccer', 17);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (297,'Beauty', 18);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (298,'Body Art', 18);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (299,'Fashion', 18);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (300,'Jewelry', 18);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (301,'Clothing', 18);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (302,'Accessories', 18);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (303,'3-D Graphics', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (304,'Animation', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (305,'Antivirus Software', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (306,'C/C++', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (307,'Cameras & Camcorders', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (308,'Cell Phones', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (309,'Computer Certification', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (310,'Computer Networking', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (311,'Computer Peripherals', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (312,'Computer Reviews', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (313,'Data Centers', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (314,'Databases', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (315,'Desktop Publishing', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (316,'Desktop Video', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (317,'Email', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (318,'Graphics Software', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (319,'Home Video/DVD', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (320,'Internet Technology', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (321,'Java', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (322,'JavaScript', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (323,'Linux', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (324,'Mac OS', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (325,'Mac Support', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (326,'MP3/MIDI', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (327,'Net Conferencing', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (328,'Net for Beginners', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (329,'Network Security', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (330,'Palmtops/PDAs', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (331,'PC Support', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (332,'Portable', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (333,'Entertainment', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (334,'Shareware/Freeware', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (335,'Unix', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (336,'Visual Basic', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (337,'Web Clip Art', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (338,'Web Design/HTML', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (339,'Web Search', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (340,'Windows', 19);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (341,'Adventure Travel', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (342,'Africa', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (343,'Air Travel', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (344,'Australia & New Zealand', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (345,'Bed & Breakfasts', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (346,'Budget Travel', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (347,'Business Travel', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (348,'By US Locale', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (349,'Camping', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (350,'Canada', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (351,'Caribbean', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (352,'Cruises', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (353,'Eastern Europe', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (354,'Europe', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (355,'France', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (356,'Greece', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (357,'Honeymoons/Getaways', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (358,'Hotels', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (359,'Italy', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (360,'Japan', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (361,'Mexico & Central America', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (362,'National Parks', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (363,'South America', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (364,'Spas', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (365,'Theme Parks', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (366,'Traveling with Kids', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (367,'United Kingdom', 20);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (368,'Apartments', 21);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (369,'Architects', 21);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (370,'Buying/Selling Homes', 21);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (371,'Contests & Freebies', 22);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (372,'Couponing', 22);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (373,'Comparison Engines', 22);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (375,'Alternative Religions', 23);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (376,'Atheism/Agnosticism', 23);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (377,'Buddhism', 23);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (378,'Catholicism', 23);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (379,'Christianity', 23);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (380,'Hinduism', 23);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (381,'Islam', 23);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (382,'Judaism', 23);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (383,'Latter-Day Saints', 23);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (384,'Pagan/Wiccan', 23);
INSERT INTO professional_interest(id, value, parent_category_id) VALUES (385,'Social Media', 24);

INSERT INTO institution VALUES (1, 'Pupilo', 'GTC Consulting' , 'Bahia de Acapulco #2988', 'Tlaquepaque', 63, '45609', 142,'52 133-1221-6072', 'pupilo@gtc.com', 'PUPILO is an innovative no profit initiative that continuously grows thanks to the volunteering of business and professionals that are commited with society', 'ACTIVE','http://pupilov1/img/logotipos/pupilo-logotipo.svg', '2016-12-13', '2016-12-13');
INSERT INTO institution VALUES (2, 'Lideres del Mañana', 'ITESM' , 'Av. Eugenio Garza Sada 2501 Sur', 'Monterrey', 68, '64849', 142,'52 81-8358-2000', 'paulina.martinez@itesm.mx', 'Líderes del Mañana looks to potentializing the formation and development of young talented Mexicans, that due to their econocmic and social condition require a full scholarship to study at the Tec', 'ACTIVE','http://sites/all/themes/lideres/images/logo_lideres.png', '2016-12-13', '2016-12-13');
INSERT INTO institution VALUES (3, 'Incubación de Empresas CIETT', 'UANL' , 'Av. Lázaro Cárdenas 4600 Oriente', 'Monterrey', 68, '64930', 142,'52 81-8329-4000', 'ciett@uanl.mx', 'The main objective of the Business Incubator area is to create and develop micro and small businesses so they are profitable and innovative.  This is done through counseling, training, profesional consulting in any of the business areas as well as follow through to facilitate access to financial sources', 'ACTIVE','http://ciett.uanl.mx/wp-content/uploads/2016/05/pleca-pags2.jpg', '2016-12-13', '2016-12-13');

INSERT INTO institutional_program VALUES (1, 'Pupilo', 'PUPILO is an innovative no profit initiative that continuously grows thanks to the volunteering of business and professionals that are commited with society', '2016-10-11','2017-10-31',1,1,20, '2016-10-10','http://pupilov1/img/logotipos/pupilo-logotipo.svg', '2016-10-10');
INSERT INTO institutional_program VALUES (2, 'Lideres del Mañana', 'Líderes del Mañana looks to potentializing the formation and development of young talented Mexicans, that due to their econocmic and social condition require a full scholarship to study at the Tec', '2016-10-11','2017-10-31',2,1,20, '2016-10-10','http://sites/all/themes/lideres/images/logo_lideres.png', '2016-10-10');
INSERT INTO institutional_program VALUES (3, 'Incubación de Empresas CIETT', 'The main objective of the Business Incubator area is to create and develop micro and small businesses so they are profitable and innovative.  This is done through counseling, training, profesional consulting in any of the business areas as well as follow through to facilitate access to financial sources', '2016-10-11','2017-10-31',3,1,20, '2016-10-10','http://ciett.uanl.mx/wp-content/uploads/2016/05/pleca-pags2.jpg', '2016-10-10');

insert into institution_affliation_code values (1, 'pupilo', 1, true);
insert into institution_affliation_code values (2, 'lideres', 2, true);
insert into institution_affliation_code values (3, 'biz', 3, true);

INSERT INTO skill(id, value) VALUES (1, 'Leadership');
INSERT INTO skill(id, value) VALUES (2, 'Productivity and Time Management');
INSERT INTO skill(id, value) VALUES (3, 'Enterpreneurship');
INSERT INTO skill(id, value) VALUES (4, 'Communication Skills');

INSERT INTO responsibility VALUES (1, 1, 'Book meetings', '2016-12-01', true, true, 1);
INSERT INTO responsibility VALUES (2, 2, 'Followup on activities', '2016-12-01', false, true, 1);
INSERT INTO responsibility VALUES (3, 3, 'Report progress', '2016-12-01', false, true, 1);
INSERT INTO responsibility VALUES (4, 4, 'Evaluate mentor', '2016-12-01', true, false, 1);
INSERT INTO responsibility VALUES (5, 5, 'Evaluate mentee', '2016-12-01', false, true, 1);

INSERT INTO goal VALUES (1, 1, 'Study a University Degree','Research scope and knowledge areas as well as work opportunities for the degree of Chemical and Food Engineering', 4, 1, 1, true);
INSERT INTO goal VALUES (2, 2, 'Taking Decisions','Improve the decision taking process to make it more effective', 1, 1, 1, true);
INSERT INTO goal VALUES (3, 3, 'English proficiency','Improve the current written and spoken English', 1, 1, 1, true);
INSERT INTO goal VALUES (4, 4, 'Improve grade average','Improve current grade average to be able to apply for a university scholarship', 1, 1, 1, true);

INSERT INTO task VALUES (1, 'Research scope and knowledge areas as well as work opportunities for the degree of Chemical and Food Engineering', 5, true, false, true, 1, 1);
INSERT INTO task VALUES (2, 'Visit University which specializes in Chemical or Food Engineering', 5, true, false, true, 1, 2);
INSERT INTO task VALUES (3, 'Review and explain Mentorship program and material.  Discuss career opportunties in Chemical and Food Engineering', 4, false, true, true, 1, 3);
INSERT INTO task VALUES (4, 'Recommend Books and Articles about Career Planning and Decision Making', 7, false, true, true, 2, 4);
INSERT INTO task VALUES (5, 'Read articles and recommended books suggested by Mentors', 21, true, false, true, 2, 5);
INSERT INTO task VALUES (6, 'Research English Language Schools and Programs', 14, true, false, true, 3, 6);
INSERT INTO task VALUES (7, 'Review English Language Schools identified by Mentees', 7, false, true, true, 3, 7);
INSERT INTO task VALUES (8, 'Explain how to create a study strategy', 14, false, true, true, 4, 8);
INSERT INTO task VALUES (9, 'Suggest sample study guides and strategies', 7, false, true, true, 4, 9);
INSERT INTO task VALUES (10, 'Plan a study strategy', 14, true, false, true, 4, 10);

INSERT INTO useful_link VALUES (1, 'GTC', 'http://gtcconsult.com/', 1, '2016-01-03');
INSERT INTO useful_link VALUES (2, 'ITESM', 'http://tec.mx/', 1, '2016-01-03');
INSERT INTO useful_link VALUES (3, 'UANL', 'http://www.uanl.mx/', 1, '2016-01-03');
INSERT INTO institutional_program_link VALUES (1, 1);
INSERT INTO institutional_program_link VALUES (2, 2);
INSERT INTO institutional_program_link VALUES (3, 3);

INSERT INTO document VALUES (1, 'Escuela ICI', 'https://drive.google.com/file/d/0B4WHaU2mA6WBUEZOUjFMMkRLSmM/view', 1, '2016-12-01', 1, '2016-12-01');
INSERT INTO document VALUES (2, 'CV', 'https://drive.google.com/file/d/0B4WHaU2mA6WBTGJwTWtVZVJzY0k/view', 1, '2016-12-01', 1, '2016-12-01');
INSERT INTO goal_document VALUES (3, 1);
INSERT INTO goal_document VALUES (4, 2);

INSERT INTO useful_link VALUES (4, 'Escuela ICI', 'http://ici.edu.mx/', 1, '2016-01-03');
INSERT INTO useful_link VALUES (5, 'Admisiones Tec', 'http://admision.itesm.mx/programas-academicos', 1, '2016-01-03');
INSERT INTO goal_useful_link VALUES (3, 4);
INSERT INTO goal_useful_link VALUES (4, 5);

INSERT INTO document VALUES (3, 'Presentation', 'https://drive.google.com/file/d/0B4WHaU2mA6WBZUxqV21nallic0U/view', 1, '2016-12-01', 1, '2016-12-01');
INSERT INTO document VALUES (4, 'Banners', 'https://drive.google.com/file/d/0B4WHaU2mA6WBTlpYUG1xcy02OWM/view', 1, '2016-12-01', 1, '2016-12-01');
INSERT INTO document VALUES (5, 'Support Letter ITESM', 'https://drive.google.com/file/d/0B4WHaU2mA6WBb0VvS0lMbWlwZVk/view', 1, '2016-12-01', 1, '2016-12-01');
INSERT INTO program_document VALUES (1, 3);
INSERT INTO program_document VALUES (2, 4);
INSERT INTO program_document VALUES (2, 5);
