insert into state values(1,'Alabama');
insert into state values(2,'Alaska');
insert into state values(3,'Arizona');
insert into state values(4,'Arkansas');
insert into state values(5,'California');
insert into state values(6,'Colorado');
insert into state values(7,'Connecticut');
insert into state values(8,'Delaware');
insert into state values(9,'Florida');
insert into state values(10,'Georgia');
insert into state values(11,'Hawaii');
insert into state values(12,'Idaho');
insert into state values(13,'Illinois');
insert into state values(14,'Indiana');
insert into state values(15,'Iowa');
insert into state values(16,'Kansas');
insert into state values(17,'Kentucky');
insert into state values(18,'Louisiana');
insert into state values(19,'Maine');
insert into state values(20,'Maryland');
insert into state values(21,'Massachusetts');	
insert into state values(22,'Michigan');
insert into state values(23,'Minnesota');
insert into state values(24,'Mississippi');
insert into state values(25,'Missouri');
insert into state values(26,'Montana');
insert into state values(27,'Nebraska');
insert into state values(28,'Nevada');
insert into state values(29,'New Hampshire');
insert into state values(30,'New Jersey');
insert into state values(31,'New Mexico');
insert into state values(32,'New York');
insert into state values(33,'North Carolina');
insert into state values(34,'North Dakota');
insert into state values(35,'Ohio');
insert into state values(36,'Oklahoma');
insert into state values(37,'Oregon');
insert into state values(38,'Pennsylvania');
insert into state values(39,'Rhode Island');
insert into state values(40,'South Carolina');
insert into state values(41,'South Dakota');
insert into state values(42,'Tennessee');
insert into state values(43,'Texas');
insert into state values(44,'Utah');
insert into state values(45,'Vermont');
insert into state values(46,'Virginia');
insert into state values(47,'Washington');
insert into state values(48,'West Virginia');
insert into state values(49,'Wisconsin');
insert into state values(50,'Wyoming');
insert into state values(51,'Aguascalientes');
insert into state values(52,'Baja California');
insert into state values(53,'Baja California Sur');
insert into state values(54,'Campeche');
insert into state values(55,'Chiapas');
insert into state values(56,'Chihuahua');
insert into state values(57,'Coahuila');
insert into state values(58,'Colima');
insert into state values(59,'Durango');
insert into state values(60,'Guanajuato');
insert into state values(61,'Guerrero');
insert into state values(62,'Hidalgo');
insert into state values(63,'Jalisco');
insert into state values(64,'México');
insert into state values(65,'Michoacán');
insert into state values(66,'Morelos');
insert into state values(67,'Nayarit');
insert into state values(68,'Nuevo León');
insert into state values(69,'Oaxaca');
insert into state values(70,'Puebla');
insert into state values(71,'Querétaro');
insert into state values(72,'Quintana Roo');
insert into state values(73,'San Luis Potosí');
insert into state values(74,'Sinaloa');
insert into state values(75,'Sonora');
insert into state values(76,'Tabasco');
insert into state values(77,'Tamaulipas');
insert into state values(78,'Tlaxcala');
insert into state values(79,'Veracruz');
insert into state values(80,'Yucatán');
insert into state values(81,'Zacatecas');