insert into user_role values(1,'SYSTEM_ADMIN');
insert into user_role values(2,'INSTITUTION_ADMIN');
insert into user_role values(3,'MENTOR');
insert into user_role values(4,'MENTEE');

insert into country values(1,'Country1');
insert into country values(2,'Country2');
insert into country values(3,'Country3');
insert into country VALUES (230,'United States');

insert into state values(1,'State1', 1);
insert into state values(2,'State2', 2);
insert into state values(3,'State3', 3);
insert into state values(32,'New York', 230);

insert into professional_consultant_area values(1,'ProfessionalConsultantArea1');
insert into professional_consultant_area values(2,'ProfessionalConsultantArea2');
insert into professional_consultant_area values(3,'ProfessionalConsultantArea3');

insert into goal_category values(1,'GoalCategory1');
insert into goal_category values(2,'GoalCategory2');
insert into goal_category values(3,'GoalCategory3');

insert into program_category values(1,'ProgramCategory1');
insert into program_category values(2,'ProgramCategory2');
insert into program_category values(3,'ProgramCategory3');

insert into personal_interest(id, value) values(1,'Arts & Entertainment');
insert into personal_interest(id, value) values(2,'Automotive');
insert into personal_interest(id, value) values(3,'Business');
insert into personal_interest(id, value) values(4,'Careers');
insert into personal_interest(id, value) values(5,'Education');
insert into personal_interest(id, value) values(6,'Family & Parenting');
insert into personal_interest(id, value) values(7,'Health & Fitness');
insert into personal_interest(id, value) values(8,'Food & Drink');
insert into personal_interest(id, value) values(9,'Hobbies & Interest');
insert into personal_interest(id, value) values(10,'Home & Garden');
insert into personal_interest(id, value) values(11,'Law, Gov''t & Politics');
insert into personal_interest(id, value) values(12,'News');
insert into personal_interest(id, value) values(13,'Personal Finance');
insert into personal_interest(id, value) values(14,'Society');
insert into personal_interest(id, value) values(15,'Science');
insert into personal_interest(id, value) values(16,'Pets');
insert into personal_interest(id, value) values(17,'Sports');
insert into personal_interest(id, value) values(18,'Style & Fashion');
insert into personal_interest(id, value) values(19,'Technology & Computing');
insert into personal_interest(id, value) values(20,'Travel');
insert into personal_interest(id, value) values(21,'Real Estate');
insert into personal_interest(id, value) values(22,'Shopping');
insert into personal_interest(id, value) values(23,'Religion & Spirituality');
insert into personal_interest(id, value) values(24,'Uncategorized');
insert into personal_interest(id, value, parent_category_id) values(25,'Books & Literature',1);
insert into personal_interest(id, value, parent_category_id) values(26,'Celebrity Fan/Gossip',1);
insert into personal_interest(id, value, parent_category_id) values(27,'Fine Art',1);
insert into personal_interest(id, value, parent_category_id) values(28,'Humor',1);
insert into personal_interest(id, value, parent_category_id) values(29,'Movies',1);
insert into personal_interest(id, value, parent_category_id) values(30,'Music',1);
insert into personal_interest(id, value, parent_category_id) values(31,'Television',1);
insert into personal_interest(id, value, parent_category_id) values(32,'Auto Parts',2);
insert into personal_interest(id, value, parent_category_id) values(33,'Auto Repair', 2);
insert into personal_interest(id, value, parent_category_id) values(34,'Buying/Selling Cars', 2);
insert into personal_interest(id, value, parent_category_id) values(35,'Car Culture', 2);
insert into personal_interest(id, value, parent_category_id) values(36,'Certified Pre-Owned', 2);
insert into personal_interest(id, value, parent_category_id) values(37,'Convertible', 2);
insert into personal_interest(id, value, parent_category_id) values(38,'Coupe', 2);
insert into personal_interest(id, value, parent_category_id) values(39,'Crossover', 2);
insert into personal_interest(id, value, parent_category_id) values(40,'Diesel', 2);
insert into personal_interest(id, value, parent_category_id) values(41,'Electric Vehicle', 2);
insert into personal_interest(id, value, parent_category_id) values(42,'Hatchback', 2);
insert into personal_interest(id, value, parent_category_id) values(43,'Hybrid', 2);
insert into personal_interest(id, value, parent_category_id) values(44,'Luxury', 2);
insert into personal_interest(id, value, parent_category_id) values(45,'MiniVan', 2);
insert into personal_interest(id, value, parent_category_id) values(46,'Motorcycles', 2);
insert into personal_interest(id, value, parent_category_id) values(47,'Navigation', 2);
insert into personal_interest(id, value, parent_category_id) values(48,'Off-Road Vehicles', 2);
insert into personal_interest(id, value, parent_category_id) values(49,'Performance Vehicles', 2);
insert into personal_interest(id, value, parent_category_id) values(50,'Pickup', 2);
insert into personal_interest(id, value, parent_category_id) values(51,'Road-Side Assistance', 2);
insert into personal_interest(id, value, parent_category_id) values(52,'Sedan', 2);
insert into personal_interest(id, value, parent_category_id) values(53,'Trucks & Accessories', 2);
insert into personal_interest(id, value, parent_category_id) values(54,'Vintage Cars', 2);
insert into personal_interest(id, value, parent_category_id) values(55,'Wagon', 2);
insert into personal_interest(id, value, parent_category_id) values(56,'Advertising', 3);
insert into personal_interest(id, value, parent_category_id) values(57,'Agriculture', 3);
insert into personal_interest(id, value, parent_category_id) values(58,'Biotech/Biomedical', 3);
insert into personal_interest(id, value, parent_category_id) values(59,'Business Software', 3);
insert into personal_interest(id, value, parent_category_id) values(60,'Construction', 3);
insert into personal_interest(id, value, parent_category_id) values(61,'Forestry', 3);
insert into personal_interest(id, value, parent_category_id) values(62,'Government', 3);
insert into personal_interest(id, value, parent_category_id) values(63,'Green Solutions', 3);
insert into personal_interest(id, value, parent_category_id) values(64,'Human Resources', 3);
insert into personal_interest(id, value, parent_category_id) values(65,'Logistics', 3);
insert into personal_interest(id, value, parent_category_id) values(66,'Marketing', 3);
insert into personal_interest(id, value, parent_category_id) values(67,'Metals', 3);
insert into personal_interest(id, value, parent_category_id) values(68,'Productivity', 3);
insert into personal_interest(id, value, parent_category_id) values(69,'Career Planning', 4);
insert into personal_interest(id, value, parent_category_id) values(70,'College', 4);
insert into personal_interest(id, value, parent_category_id) values(71,'Financial Aid', 4);
insert into personal_interest(id, value, parent_category_id) values(72,'Job Fairs', 4);
insert into personal_interest(id, value, parent_category_id) values(73,'Job Search', 4);
insert into personal_interest(id, value, parent_category_id) values(74,'Resume Writing/Advice', 4);
insert into personal_interest(id, value, parent_category_id) values(75,'Nursing', 4);
insert into personal_interest(id, value, parent_category_id) values(76,'Scholarships', 4);
insert into personal_interest(id, value, parent_category_id) values(77,'Telecommuting', 4);
insert into personal_interest(id, value, parent_category_id) values(78,'U.S. Military', 4);
insert into personal_interest(id, value, parent_category_id) values(79,'Career Advice', 4);
insert into personal_interest(id, value, parent_category_id) values(80,'7-12 Education', 5);
insert into personal_interest(id, value, parent_category_id) values(81,'Adult Education', 5);
insert into personal_interest(id, value, parent_category_id) values(82,'Art History', 5);
insert into personal_interest(id, value, parent_category_id) values(83,'College Administration', 5);
insert into personal_interest(id, value, parent_category_id) values(84,'College Life', 5);
insert into personal_interest(id, value, parent_category_id) values(85,'Distance Learning', 5);
insert into personal_interest(id, value, parent_category_id) values(86,'English as a 2nd Language', 5);
insert into personal_interest(id, value, parent_category_id) values(87,'Language Learning', 5);
insert into personal_interest(id, value, parent_category_id) values(88,'Graduate School', 5);
insert into personal_interest(id, value, parent_category_id) values(89,'Homeschooling', 5);
insert into personal_interest(id, value, parent_category_id) values(90,'Homework/Study Tips', 5);
insert into personal_interest(id, value, parent_category_id) values(91,'K-6 Educators', 5);
insert into personal_interest(id, value, parent_category_id) values(92,'Private School', 5);
insert into personal_interest(id, value, parent_category_id) values(93,'Special Education', 5);
insert into personal_interest(id, value, parent_category_id) values(94,'Studying Business', 5);
insert into personal_interest(id, value, parent_category_id) values(95,'Adoption', 6);
insert into personal_interest(id, value, parent_category_id) values(96,'Babies & Toddlers', 6);
insert into personal_interest(id, value, parent_category_id) values(97,'Daycare/Pre School', 6);
insert into personal_interest(id, value, parent_category_id) values(98,'Family Internet', 6);
insert into personal_interest(id, value, parent_category_id) values(99,'Parenting - K-6 Kids', 6);
insert into personal_interest(id, value, parent_category_id) values(100,'Parenting Teens', 6);
insert into personal_interest(id, value, parent_category_id) values(101,'Pregnancy', 6);
insert into personal_interest(id, value, parent_category_id) values(102,'Special Needs Kids', 6);
insert into personal_interest(id, value, parent_category_id) values(103,'Eldercare', 6);
insert into personal_interest(id, value, parent_category_id) values(104,'Exercise', 7);
insert into personal_interest(id, value, parent_category_id) values(105,'A.D.D.', 7);
insert into personal_interest(id, value, parent_category_id) values(106,'AIDS/HIV', 7);
insert into personal_interest(id, value, parent_category_id) values(107,'Allergies', 7);
insert into personal_interest(id, value, parent_category_id) values(108,'Alternative Medicine', 7);
insert into personal_interest(id, value, parent_category_id) values(109,'Arthritis', 7);
insert into personal_interest(id, value, parent_category_id) values(110,'Asthma', 7);
insert into personal_interest(id, value, parent_category_id) values(111,'Autism/PDD', 7);
insert into personal_interest(id, value, parent_category_id) values(112,'Bipolar Disorder', 7);
insert into personal_interest(id, value, parent_category_id) values(113,'Brain Tumor', 7);
insert into personal_interest(id, value, parent_category_id) values(114,'Cancer', 7);
insert into personal_interest(id, value, parent_category_id) values(115,'Cholesterol', 7);
insert into personal_interest(id, value, parent_category_id) values(116,'Chronic Fatigue Syndrome', 7);
insert into personal_interest(id, value, parent_category_id) values(117,'Chronic Pain', 7);
insert into personal_interest(id, value, parent_category_id) values(118,'Cold & Flu', 7);
insert into personal_interest(id, value, parent_category_id) values(119,'Deafness', 7);
insert into personal_interest(id, value, parent_category_id) values(120,'Dental Care', 7);
insert into personal_interest(id, value, parent_category_id) values(121,'Depression', 7);
insert into personal_interest(id, value, parent_category_id) values(122,'Dermatology', 7);
insert into personal_interest(id, value, parent_category_id) values(123,'Diabetes', 7);
insert into personal_interest(id, value, parent_category_id) values(124,'Epilepsy', 7);
insert into personal_interest(id, value, parent_category_id) values(125,'GERD/Acid Reflux', 7);
insert into personal_interest(id, value, parent_category_id) values(126,'Headaches/Migraines', 7);
insert into personal_interest(id, value, parent_category_id) values(127,'Heart Disease', 7);
insert into personal_interest(id, value, parent_category_id) values(128,'Herbs for Health', 7);
insert into personal_interest(id, value, parent_category_id) values(129,'Holistic Healing', 7);
insert into personal_interest(id, value, parent_category_id) values(130,'IBS/Crohn''s Disease', 7);
insert into personal_interest(id, value, parent_category_id) values(131,'Incest/Abuse Support', 7);
insert into personal_interest(id, value, parent_category_id) values(132,'Incontinence', 7);
insert into personal_interest(id, value, parent_category_id) values(133,'Infertility', 7);
insert into personal_interest(id, value, parent_category_id) values(134,'Men''s Health', 7);
insert into personal_interest(id, value, parent_category_id) values(135,'Nutrition', 7);
insert into personal_interest(id, value, parent_category_id) values(136,'Orthopedics', 7);
insert into personal_interest(id, value, parent_category_id) values(137,'Panic/Anxiety', 7);
insert into personal_interest(id, value, parent_category_id) values(138,'Disorders', 7);
insert into personal_interest(id, value, parent_category_id) values(139,'Pediatrics', 7);
insert into personal_interest(id, value, parent_category_id) values(140,'Physical Therapy', 7);
insert into personal_interest(id, value, parent_category_id) values(141,'Psychology/Psychiatry', 7);
insert into personal_interest(id, value, parent_category_id) values(142,'Senior Health', 7);
insert into personal_interest(id, value, parent_category_id) values(143,'Sexuality', 7);
insert into personal_interest(id, value, parent_category_id) values(144,'Sleep Disorders', 7);
insert into personal_interest(id, value, parent_category_id) values(145,'Smoking Cessation', 7);
insert into personal_interest(id, value, parent_category_id) values(146,'Substance Abuse', 7);
insert into personal_interest(id, value, parent_category_id) values(147,'Thyroid Disease', 7);
insert into personal_interest(id, value, parent_category_id) values(148,'Weight Loss', 7);
insert into personal_interest(id, value, parent_category_id) values(149,'Women''s Health', 7);
insert into personal_interest(id, value, parent_category_id) values(150,'American Cuisine', 8);
insert into personal_interest(id, value, parent_category_id) values(151,'Barbecues & Grilling', 8);
insert into personal_interest(id, value, parent_category_id) values(152,'Cajun/Creole', 8);
insert into personal_interest(id, value, parent_category_id) values(153,'Chinese Cuisine', 8);
insert into personal_interest(id, value, parent_category_id) values(154,'Cocktails/Beer', 8);
insert into personal_interest(id, value, parent_category_id) values(155,'Coffee/Tea', 8);
insert into personal_interest(id, value, parent_category_id) values(156,'Cuisine-Specific', 8);
insert into personal_interest(id, value, parent_category_id) values(157,'Desserts & Baking', 8);
insert into personal_interest(id, value, parent_category_id) values(158,'Dining Out', 8);
insert into personal_interest(id, value, parent_category_id) values(159,'Food Allergies', 8);
insert into personal_interest(id, value, parent_category_id) values(160,'French Cuisine', 8);
insert into personal_interest(id, value, parent_category_id) values(161,'Health/LowFat Cooking', 8);
insert into personal_interest(id, value, parent_category_id) values(162,'Italian Cuisine', 8);
insert into personal_interest(id, value, parent_category_id) values(163,'Japanese Cuisine', 8);
insert into personal_interest(id, value, parent_category_id) values(164,'Mexican Cuisine', 8);
insert into personal_interest(id, value, parent_category_id) values(165,'Vegan', 8);
insert into personal_interest(id, value, parent_category_id) values(166,'Vegetarian', 8);
insert into personal_interest(id, value, parent_category_id) values(167,'Wine', 8);
insert into personal_interest(id, value, parent_category_id) values(168,'Art/Technology', 9);
insert into personal_interest(id, value, parent_category_id) values(169,'Arts & Crafts', 9);
insert into personal_interest(id, value, parent_category_id) values(170,'Beadwork', 9);
insert into personal_interest(id, value, parent_category_id) values(171,'Birdwatching', 9);
insert into personal_interest(id, value, parent_category_id) values(172,'Board Games/Puzzles', 9);
insert into personal_interest(id, value, parent_category_id) values(173,'Candle & Soap Making', 9);
insert into personal_interest(id, value, parent_category_id) values(174,'Card Games', 9);
insert into personal_interest(id, value, parent_category_id) values(175,'Chess', 9);
insert into personal_interest(id, value, parent_category_id) values(176,'Cigars', 9);
insert into personal_interest(id, value, parent_category_id) values(177,'Collecting', 9);
insert into personal_interest(id, value, parent_category_id) values(178,'Comic Books', 9);
insert into personal_interest(id, value, parent_category_id) values(179,'Drawing/Sketching', 9);
insert into personal_interest(id, value, parent_category_id) values(180,'Freelance Writing', 9);
insert into personal_interest(id, value, parent_category_id) values(181,'Genealogy', 9);
insert into personal_interest(id, value, parent_category_id) values(182,'Getting Published', 9);
insert into personal_interest(id, value, parent_category_id) values(183,'Guitar', 9);
insert into personal_interest(id, value, parent_category_id) values(184,'Home Recording', 9);
insert into personal_interest(id, value, parent_category_id) values(185,'Investors & Patents', 9);
insert into personal_interest(id, value, parent_category_id) values(186,'Jewelry Making', 9);
insert into personal_interest(id, value, parent_category_id) values(187,'Magic & Illusion', 9);
insert into personal_interest(id, value, parent_category_id) values(188,'Needlework', 9);
insert into personal_interest(id, value, parent_category_id) values(189,'Painting', 9);
insert into personal_interest(id, value, parent_category_id) values(190,'Photography', 9);
insert into personal_interest(id, value, parent_category_id) values(191,'Radio', 9);
insert into personal_interest(id, value, parent_category_id) values(192,'Roleplaying Games', 9);
insert into personal_interest(id, value, parent_category_id) values(193,'Sci-Fi & Fantasy', 9);
insert into personal_interest(id, value, parent_category_id) values(194,'Scrapbooking', 9);
insert into personal_interest(id, value, parent_category_id) values(195,'Screenwriting', 9);
insert into personal_interest(id, value, parent_category_id) values(196,'Stamps & Coins', 9);
insert into personal_interest(id, value, parent_category_id) values(197,'Video & Computer Games', 9);
insert into personal_interest(id, value, parent_category_id) values(198,'Woodworking', 9);
insert into personal_interest(id, value, parent_category_id) values(199,'Appliances', 10);
insert into personal_interest(id, value, parent_category_id) values(200,'Entertaining', 10);
insert into personal_interest(id, value, parent_category_id) values(201,'Environmental Safety', 10);
insert into personal_interest(id, value, parent_category_id) values(202,'Gardening', 10);
insert into personal_interest(id, value, parent_category_id) values(203,'Home Repair', 10);
insert into personal_interest(id, value, parent_category_id) values(204,'Home Theater', 10);
insert into personal_interest(id, value, parent_category_id) values(205,'Interior Decorating', 10);
insert into personal_interest(id, value, parent_category_id) values(206,'Landscaping', 10);
insert into personal_interest(id, value, parent_category_id) values(207,'Remodeling & Construction', 10);
insert into personal_interest(id, value, parent_category_id) values(208,'Immigration', 11);
insert into personal_interest(id, value, parent_category_id) values(209,'Legal Issues', 11);
insert into personal_interest(id, value, parent_category_id) values(210,'U.S. Government Resources', 11);
insert into personal_interest(id, value, parent_category_id) values(211,'Politics', 11);
insert into personal_interest(id, value, parent_category_id) values(212,'Commentary', 11);
insert into personal_interest(id, value, parent_category_id) values(213,'International News', 12);
insert into personal_interest(id, value, parent_category_id) values(214,'National News', 12);
insert into personal_interest(id, value, parent_category_id) values(215,'Local News', 12);
insert into personal_interest(id, value, parent_category_id) values(216,'Beginning Investing', 13);
insert into personal_interest(id, value, parent_category_id) values(217,'Credit/Debt & Loans', 13);
insert into personal_interest(id, value, parent_category_id) values(218,'Financial News', 13);
insert into personal_interest(id, value, parent_category_id) values(219,'Financial Planning', 13);
insert into personal_interest(id, value, parent_category_id) values(220,'Hedge Fund', 13);
insert into personal_interest(id, value, parent_category_id) values(221,'Insurance', 13);
insert into personal_interest(id, value, parent_category_id) values(222,'Investing', 13);
insert into personal_interest(id, value, parent_category_id) values(223,'Mutual Funds', 13);
insert into personal_interest(id, value, parent_category_id) values(224,'Options', 13);
insert into personal_interest(id, value, parent_category_id) values(225,'Retirement Planning', 13);
insert into personal_interest(id, value, parent_category_id) values(226,'Stocks', 13);
insert into personal_interest(id, value, parent_category_id) values(227,'Tax Planning', 13);
insert into personal_interest(id, value, parent_category_id) values(228,'Dating', 13);
insert into personal_interest(id, value, parent_category_id) values(229,'Divorce Support', 13);
insert into personal_interest(id, value, parent_category_id) values(230,'Gay Life', 14);
insert into personal_interest(id, value, parent_category_id) values(231,'Marriage', 14);
insert into personal_interest(id, value, parent_category_id) values(232,'Senior Living', 14);
insert into personal_interest(id, value, parent_category_id) values(233,'Teens', 14);
insert into personal_interest(id, value, parent_category_id) values(234,'Weddings', 14);
insert into personal_interest(id, value, parent_category_id) values(235,'Ethnic Specific', 14);
insert into personal_interest(id, value, parent_category_id) values(236,'Astrology', 14);
insert into personal_interest(id, value, parent_category_id) values(237,'Biology', 15);
insert into personal_interest(id, value, parent_category_id) values(238,'Chemistry', 15);
insert into personal_interest(id, value, parent_category_id) values(239,'Geology', 15);
insert into personal_interest(id, value, parent_category_id) values(240,'Paranormal Phenomena', 15);
insert into personal_interest(id, value, parent_category_id) values(241,'Physics', 15);
insert into personal_interest(id, value, parent_category_id) values(242,'Space/Astronomy', 15);
insert into personal_interest(id, value, parent_category_id) values(243,'Geography', 15);
insert into personal_interest(id, value, parent_category_id) values(244,'Botany', 15);
insert into personal_interest(id, value, parent_category_id) values(245,'Weather', 15);
insert into personal_interest(id, value, parent_category_id) values(246,'Aquariums', 16);
insert into personal_interest(id, value, parent_category_id) values(247,'Birds', 16);
insert into personal_interest(id, value, parent_category_id) values(248,'Cats', 16);
insert into personal_interest(id, value, parent_category_id) values(249,'Dogs', 16);
insert into personal_interest(id, value, parent_category_id) values(250,'Large Animals', 16);
insert into personal_interest(id, value, parent_category_id) values(251,'Reptiles', 16);
insert into personal_interest(id, value, parent_category_id) values(252,'Veterinary Medicine', 16);
insert into personal_interest(id, value, parent_category_id) values(253,'Auto Racing', 17);
insert into personal_interest(id, value, parent_category_id) values(254,'Baseball', 17);
insert into personal_interest(id, value, parent_category_id) values(255,'Bicycling', 17);
insert into personal_interest(id, value, parent_category_id) values(256,'Bodybuilding', 17);
insert into personal_interest(id, value, parent_category_id) values(257,'Boxing', 17);
insert into personal_interest(id, value, parent_category_id) values(258,'Canoeing/Kayaking', 17);
insert into personal_interest(id, value, parent_category_id) values(259,'Cheerleading', 17);
insert into personal_interest(id, value, parent_category_id) values(260,'Climbing', 17);
insert into personal_interest(id, value, parent_category_id) values(261,'Cricket', 17);
insert into personal_interest(id, value, parent_category_id) values(262,'Figure Skating', 17);
insert into personal_interest(id, value, parent_category_id) values(263,'Fly Fishing', 17);
insert into personal_interest(id, value, parent_category_id) values(264,'Football', 17);
insert into personal_interest(id, value, parent_category_id) values(265,'Freshwater Fishing', 17);
insert into personal_interest(id, value, parent_category_id) values(266,'Game & Fish', 17);
insert into personal_interest(id, value, parent_category_id) values(267,'Golf', 17);
insert into personal_interest(id, value, parent_category_id) values(268,'Horse Racing', 17);
insert into personal_interest(id, value, parent_category_id) values(269,'Horses', 17);
insert into personal_interest(id, value, parent_category_id) values(270,'Hunting/Shooting', 17);
insert into personal_interest(id, value, parent_category_id) values(271,'Inline Skating', 17);
insert into personal_interest(id, value, parent_category_id) values(272,'Martial Arts', 17);
insert into personal_interest(id, value, parent_category_id) values(273,'Mountain Biking', 17);
insert into personal_interest(id, value, parent_category_id) values(274,'NASCAR Racing', 17);
insert into personal_interest(id, value, parent_category_id) values(275,'Olympics', 17);
insert into personal_interest(id, value, parent_category_id) values(276,'Paintball', 17);
insert into personal_interest(id, value, parent_category_id) values(277,'Power & Motorcycles', 17);
insert into personal_interest(id, value, parent_category_id) values(278,'Pro Basketball', 17);
insert into personal_interest(id, value, parent_category_id) values(279,'Pro Ice Hockey', 17);
insert into personal_interest(id, value, parent_category_id) values(280,'Rodeo', 17);
insert into personal_interest(id, value, parent_category_id) values(281,'Rugby', 17);
insert into personal_interest(id, value, parent_category_id) values(282,'Running/Jogging', 17);
insert into personal_interest(id, value, parent_category_id) values(283,'Sailing', 17);
insert into personal_interest(id, value, parent_category_id) values(284,'Saltwater Fishing', 17);
insert into personal_interest(id, value, parent_category_id) values(285,'Scuba Diving', 17);
insert into personal_interest(id, value, parent_category_id) values(286,'Skateboarding', 17);
insert into personal_interest(id, value, parent_category_id) values(287,'Skiing', 17);
insert into personal_interest(id, value, parent_category_id) values(288,'Snowboarding', 17);
insert into personal_interest(id, value, parent_category_id) values(289,'Surfing/Bodyboarding', 17);
insert into personal_interest(id, value, parent_category_id) values(290,'Swimming', 17);
insert into personal_interest(id, value, parent_category_id) values(291,'Table Tennis/Ping-Pong', 17);
insert into personal_interest(id, value, parent_category_id) values(292,'Tennis', 17);
insert into personal_interest(id, value, parent_category_id) values(293,'Volleyball', 17);
insert into personal_interest(id, value, parent_category_id) values(294,'Walking', 17);
insert into personal_interest(id, value, parent_category_id) values(295,'Waterski/Wakeboard', 17);
insert into personal_interest(id, value, parent_category_id) values(296,'World Soccer', 17);
insert into personal_interest(id, value, parent_category_id) values(297,'Beauty', 18);
insert into personal_interest(id, value, parent_category_id) values(298,'Body Art', 18);
insert into personal_interest(id, value, parent_category_id) values(299,'Fashion', 18);
insert into personal_interest(id, value, parent_category_id) values(300,'Jewelry', 18);
insert into personal_interest(id, value, parent_category_id) values(301,'Clothing', 18);
insert into personal_interest(id, value, parent_category_id) values(302,'Accessories', 18);
insert into personal_interest(id, value, parent_category_id) values(303,'3-D Graphics', 19);
insert into personal_interest(id, value, parent_category_id) values(304,'Animation', 19);
insert into personal_interest(id, value, parent_category_id) values(305,'Antivirus Software', 19);
insert into personal_interest(id, value, parent_category_id) values(306,'C/C++', 19);
insert into personal_interest(id, value, parent_category_id) values(307,'Cameras & Camcorders', 19);
insert into personal_interest(id, value, parent_category_id) values(308,'Cell Phones', 19);
insert into personal_interest(id, value, parent_category_id) values(309,'Computer Certification', 19);
insert into personal_interest(id, value, parent_category_id) values(310,'Computer Networking', 19);
insert into personal_interest(id, value, parent_category_id) values(311,'Computer Peripherals', 19);
insert into personal_interest(id, value, parent_category_id) values(312,'Computer Reviews', 19);
insert into personal_interest(id, value, parent_category_id) values(313,'Data Centers', 19);
insert into personal_interest(id, value, parent_category_id) values(314,'Databases', 19);
insert into personal_interest(id, value, parent_category_id) values(315,'Desktop Publishing', 19);
insert into personal_interest(id, value, parent_category_id) values(316,'Desktop Video', 19);
insert into personal_interest(id, value, parent_category_id) values(317,'Email', 19);
insert into personal_interest(id, value, parent_category_id) values(318,'Graphics Software', 19);
insert into personal_interest(id, value, parent_category_id) values(319,'Home Video/DVD', 19);
insert into personal_interest(id, value, parent_category_id) values(320,'Internet Technology', 19);
insert into personal_interest(id, value, parent_category_id) values(321,'Java', 19);
insert into personal_interest(id, value, parent_category_id) values(322,'JavaScript', 19);
insert into personal_interest(id, value, parent_category_id) values(323,'Linux', 19);
insert into personal_interest(id, value, parent_category_id) values(324,'Mac OS', 19);
insert into personal_interest(id, value, parent_category_id) values(325,'Mac Support', 19);
insert into personal_interest(id, value, parent_category_id) values(326,'MP3/MIDI', 19);
insert into personal_interest(id, value, parent_category_id) values(327,'Net Conferencing', 19);
insert into personal_interest(id, value, parent_category_id) values(328,'Net for Beginners', 19);
insert into personal_interest(id, value, parent_category_id) values(329,'Network Security', 19);
insert into personal_interest(id, value, parent_category_id) values(330,'Palmtops/PDAs', 19);
insert into personal_interest(id, value, parent_category_id) values(331,'PC Support', 19);
insert into personal_interest(id, value, parent_category_id) values(332,'Portable', 19);
insert into personal_interest(id, value, parent_category_id) values(333,'Entertainment', 19);
insert into personal_interest(id, value, parent_category_id) values(334,'Shareware/Freeware', 19);
insert into personal_interest(id, value, parent_category_id) values(335,'Unix', 19);
insert into personal_interest(id, value, parent_category_id) values(336,'Visual Basic', 19);
insert into personal_interest(id, value, parent_category_id) values(337,'Web Clip Art', 19);
insert into personal_interest(id, value, parent_category_id) values(338,'Web Design/HTML', 19);
insert into personal_interest(id, value, parent_category_id) values(339,'Web Search', 19);
insert into personal_interest(id, value, parent_category_id) values(340,'Windows', 19);
insert into personal_interest(id, value, parent_category_id) values(341,'Adventure Travel', 20);
insert into personal_interest(id, value, parent_category_id) values(342,'Africa', 20);
insert into personal_interest(id, value, parent_category_id) values(343,'Air Travel', 20);
insert into personal_interest(id, value, parent_category_id) values(344,'Australia & New Zealand', 20);
insert into personal_interest(id, value, parent_category_id) values(345,'Bed & Breakfasts', 20);
insert into personal_interest(id, value, parent_category_id) values(346,'Budget Travel', 20);
insert into personal_interest(id, value, parent_category_id) values(347,'Business Travel', 20);
insert into personal_interest(id, value, parent_category_id) values(348,'By US Locale', 20);
insert into personal_interest(id, value, parent_category_id) values(349,'Camping', 20);
insert into personal_interest(id, value, parent_category_id) values(350,'Canada', 20);
insert into personal_interest(id, value, parent_category_id) values(351,'Caribbean', 20);
insert into personal_interest(id, value, parent_category_id) values(352,'Cruises', 20);
insert into personal_interest(id, value, parent_category_id) values(353,'Eastern Europe', 20);
insert into personal_interest(id, value, parent_category_id) values(354,'Europe', 20);
insert into personal_interest(id, value, parent_category_id) values(355,'France', 20);
insert into personal_interest(id, value, parent_category_id) values(356,'Greece', 20);
insert into personal_interest(id, value, parent_category_id) values(357,'Honeymoons/Getaways', 20);
insert into personal_interest(id, value, parent_category_id) values(358,'Hotels', 20);
insert into personal_interest(id, value, parent_category_id) values(359,'Italy', 20);
insert into personal_interest(id, value, parent_category_id) values(360,'Japan', 20);
insert into personal_interest(id, value, parent_category_id) values(361,'Mexico & Central America', 20);
insert into personal_interest(id, value, parent_category_id) values(362,'National Parks', 20);
insert into personal_interest(id, value, parent_category_id) values(363,'South America', 20);
insert into personal_interest(id, value, parent_category_id) values(364,'Spas', 20);
insert into personal_interest(id, value, parent_category_id) values(365,'Theme Parks', 20);
insert into personal_interest(id, value, parent_category_id) values(366,'Traveling with Kids', 20);
insert into personal_interest(id, value, parent_category_id) values(367,'United Kingdom', 20);
insert into personal_interest(id, value, parent_category_id) values(368,'Apartments', 21);
insert into personal_interest(id, value, parent_category_id) values(369,'Architects', 21);
insert into personal_interest(id, value, parent_category_id) values(370,'Buying/Selling Homes', 21);
insert into personal_interest(id, value, parent_category_id) values(371,'Contests & Freebies', 22);
insert into personal_interest(id, value, parent_category_id) values(372,'Couponing', 22);
insert into personal_interest(id, value, parent_category_id) values(373,'Comparison Engines', 22);
insert into personal_interest(id, value, parent_category_id) values(375,'Alternative Religions', 23);
insert into personal_interest(id, value, parent_category_id) values(376,'Atheism/Agnosticism', 23);
insert into personal_interest(id, value, parent_category_id) values(377,'Buddhism', 23);
insert into personal_interest(id, value, parent_category_id) values(378,'Catholicism', 23);
insert into personal_interest(id, value, parent_category_id) values(379,'Christianity', 23);
insert into personal_interest(id, value, parent_category_id) values(380,'Hinduism', 23);
insert into personal_interest(id, value, parent_category_id) values(381,'Islam', 23);
insert into personal_interest(id, value, parent_category_id) values(382,'Judaism', 23);
insert into personal_interest(id, value, parent_category_id) values(383,'Latter-Day Saints', 23);
insert into personal_interest(id, value, parent_category_id) values(384,'Pagan/Wiccan', 23);
insert into personal_interest(id, value, parent_category_id) values(385,'Social Media', 24);

insert into professional_interest(id, value) values(1,'Arts & Entertainment');
insert into professional_interest(id, value) values(2,'Automotive');
insert into professional_interest(id, value) values(3,'Business');
insert into professional_interest(id, value) values(4,'Careers');
insert into professional_interest(id, value) values(5,'Education');
insert into professional_interest(id, value) values(6,'Family & Parenting');
insert into professional_interest(id, value) values(7,'Health & Fitness');
insert into professional_interest(id, value) values(8,'Food & Drink');
insert into professional_interest(id, value) values(9,'Hobbies & Interest');
insert into professional_interest(id, value) values(10,'Home & Garden');
insert into professional_interest(id, value) values(11,'Law, Gov''t & Politics');
insert into professional_interest(id, value) values(12,'News');
insert into professional_interest(id, value) values(13,'Personal Finance');
insert into professional_interest(id, value) values(14,'Society');
insert into professional_interest(id, value) values(15,'Science');
insert into professional_interest(id, value) values(16,'Pets');
insert into professional_interest(id, value) values(17,'Sports');
insert into professional_interest(id, value) values(18,'Style & Fashion');
insert into professional_interest(id, value) values(19,'Technology & Computing');
insert into professional_interest(id, value) values(20,'Travel');
insert into professional_interest(id, value) values(21,'Real Estate');
insert into professional_interest(id, value) values(22,'Shopping');
insert into professional_interest(id, value) values(23,'Religion & Spirituality');
insert into professional_interest(id, value) values(24,'Uncategorized');
insert into professional_interest(id, value, parent_category_id) values(25,'Books & Literature',1);
insert into professional_interest(id, value, parent_category_id) values(26,'Celebrity Fan/Gossip',1);
insert into professional_interest(id, value, parent_category_id) values(27,'Fine Art',1);
insert into professional_interest(id, value, parent_category_id) values(28,'Humor',1);
insert into professional_interest(id, value, parent_category_id) values(29,'Movies',1);
insert into professional_interest(id, value, parent_category_id) values(30,'Music',1);
insert into professional_interest(id, value, parent_category_id) values(31,'Television',1);
insert into professional_interest(id, value, parent_category_id) values(32,'Auto Parts',2);
insert into professional_interest(id, value, parent_category_id) values(33,'Auto Repair', 2);
insert into professional_interest(id, value, parent_category_id) values(34,'Buying/Selling Cars', 2);
insert into professional_interest(id, value, parent_category_id) values(35,'Car Culture', 2);
insert into professional_interest(id, value, parent_category_id) values(36,'Certified Pre-Owned', 2);
insert into professional_interest(id, value, parent_category_id) values(37,'Convertible', 2);
insert into professional_interest(id, value, parent_category_id) values(38,'Coupe', 2);
insert into professional_interest(id, value, parent_category_id) values(39,'Crossover', 2);
insert into professional_interest(id, value, parent_category_id) values(40,'Diesel', 2);
insert into professional_interest(id, value, parent_category_id) values(41,'Electric Vehicle', 2);
insert into professional_interest(id, value, parent_category_id) values(42,'Hatchback', 2);
insert into professional_interest(id, value, parent_category_id) values(43,'Hybrid', 2);
insert into professional_interest(id, value, parent_category_id) values(44,'Luxury', 2);
insert into professional_interest(id, value, parent_category_id) values(45,'MiniVan', 2);
insert into professional_interest(id, value, parent_category_id) values(46,'Motorcycles', 2);
insert into professional_interest(id, value, parent_category_id) values(47,'Navigation', 2);
insert into professional_interest(id, value, parent_category_id) values(48,'Off-Road Vehicles', 2);
insert into professional_interest(id, value, parent_category_id) values(49,'Performance Vehicles', 2);
insert into professional_interest(id, value, parent_category_id) values(50,'Pickup', 2);
insert into professional_interest(id, value, parent_category_id) values(51,'Road-Side Assistance', 2);
insert into professional_interest(id, value, parent_category_id) values(52,'Sedan', 2);
insert into professional_interest(id, value, parent_category_id) values(53,'Trucks & Accessories', 2);
insert into professional_interest(id, value, parent_category_id) values(54,'Vintage Cars', 2);
insert into professional_interest(id, value, parent_category_id) values(55,'Wagon', 2);
insert into professional_interest(id, value, parent_category_id) values(56,'Advertising', 3);
insert into professional_interest(id, value, parent_category_id) values(57,'Agriculture', 3);
insert into professional_interest(id, value, parent_category_id) values(58,'Biotech/Biomedical', 3);
insert into professional_interest(id, value, parent_category_id) values(59,'Business Software', 3);
insert into professional_interest(id, value, parent_category_id) values(60,'Construction', 3);
insert into professional_interest(id, value, parent_category_id) values(61,'Forestry', 3);
insert into professional_interest(id, value, parent_category_id) values(62,'Government', 3);
insert into professional_interest(id, value, parent_category_id) values(63,'Green Solutions', 3);
insert into professional_interest(id, value, parent_category_id) values(64,'Human Resources', 3);
insert into professional_interest(id, value, parent_category_id) values(65,'Logistics', 3);
insert into professional_interest(id, value, parent_category_id) values(66,'Marketing', 3);
insert into professional_interest(id, value, parent_category_id) values(67,'Metals', 3);
insert into professional_interest(id, value, parent_category_id) values(68,'Productivity', 3);
insert into professional_interest(id, value, parent_category_id) values(69,'Career Planning', 4);
insert into professional_interest(id, value, parent_category_id) values(70,'College', 4);
insert into professional_interest(id, value, parent_category_id) values(71,'Financial Aid', 4);
insert into professional_interest(id, value, parent_category_id) values(72,'Job Fairs', 4);
insert into professional_interest(id, value, parent_category_id) values(73,'Job Search', 4);
insert into professional_interest(id, value, parent_category_id) values(74,'Resume Writing/Advice', 4);
insert into professional_interest(id, value, parent_category_id) values(75,'Nursing', 4);
insert into professional_interest(id, value, parent_category_id) values(76,'Scholarships', 4);
insert into professional_interest(id, value, parent_category_id) values(77,'Telecommuting', 4);
insert into professional_interest(id, value, parent_category_id) values(78,'U.S. Military', 4);
insert into professional_interest(id, value, parent_category_id) values(79,'Career Advice', 4);
insert into professional_interest(id, value, parent_category_id) values(80,'7-12 Education', 5);
insert into professional_interest(id, value, parent_category_id) values(81,'Adult Education', 5);
insert into professional_interest(id, value, parent_category_id) values(82,'Art History', 5);
insert into professional_interest(id, value, parent_category_id) values(83,'College Administration', 5);
insert into professional_interest(id, value, parent_category_id) values(84,'College Life', 5);
insert into professional_interest(id, value, parent_category_id) values(85,'Distance Learning', 5);
insert into professional_interest(id, value, parent_category_id) values(86,'English as a 2nd Language', 5);
insert into professional_interest(id, value, parent_category_id) values(87,'Language Learning', 5);
insert into professional_interest(id, value, parent_category_id) values(88,'Graduate School', 5);
insert into professional_interest(id, value, parent_category_id) values(89,'Homeschooling', 5);
insert into professional_interest(id, value, parent_category_id) values(90,'Homework/Study Tips', 5);
insert into professional_interest(id, value, parent_category_id) values(91,'K-6 Educators', 5);
insert into professional_interest(id, value, parent_category_id) values(92,'Private School', 5);
insert into professional_interest(id, value, parent_category_id) values(93,'Special Education', 5);
insert into professional_interest(id, value, parent_category_id) values(94,'Studying Business', 5);
insert into professional_interest(id, value, parent_category_id) values(95,'Adoption', 6);
insert into professional_interest(id, value, parent_category_id) values(96,'Babies & Toddlers', 6);
insert into professional_interest(id, value, parent_category_id) values(97,'Daycare/Pre School', 6);
insert into professional_interest(id, value, parent_category_id) values(98,'Family Internet', 6);
insert into professional_interest(id, value, parent_category_id) values(99,'Parenting - K-6 Kids', 6);
insert into professional_interest(id, value, parent_category_id) values(100,'Parenting Teens', 6);
insert into professional_interest(id, value, parent_category_id) values(101,'Pregnancy', 6);
insert into professional_interest(id, value, parent_category_id) values(102,'Special Needs Kids', 6);
insert into professional_interest(id, value, parent_category_id) values(103,'Eldercare', 6);
insert into professional_interest(id, value, parent_category_id) values(104,'Exercise', 7);
insert into professional_interest(id, value, parent_category_id) values(105,'A.D.D.', 7);
insert into professional_interest(id, value, parent_category_id) values(106,'AIDS/HIV', 7);
insert into professional_interest(id, value, parent_category_id) values(107,'Allergies', 7);
insert into professional_interest(id, value, parent_category_id) values(108,'Alternative Medicine', 7);
insert into professional_interest(id, value, parent_category_id) values(109,'Arthritis', 7);
insert into professional_interest(id, value, parent_category_id) values(110,'Asthma', 7);
insert into professional_interest(id, value, parent_category_id) values(111,'Autism/PDD', 7);
insert into professional_interest(id, value, parent_category_id) values(112,'Bipolar Disorder', 7);
insert into professional_interest(id, value, parent_category_id) values(113,'Brain Tumor', 7);
insert into professional_interest(id, value, parent_category_id) values(114,'Cancer', 7);
insert into professional_interest(id, value, parent_category_id) values(115,'Cholesterol', 7);
insert into professional_interest(id, value, parent_category_id) values(116,'Chronic Fatigue Syndrome', 7);
insert into professional_interest(id, value, parent_category_id) values(117,'Chronic Pain', 7);
insert into professional_interest(id, value, parent_category_id) values(118,'Cold & Flu', 7);
insert into professional_interest(id, value, parent_category_id) values(119,'Deafness', 7);
insert into professional_interest(id, value, parent_category_id) values(120,'Dental Care', 7);
insert into professional_interest(id, value, parent_category_id) values(121,'Depression', 7);
insert into professional_interest(id, value, parent_category_id) values(122,'Dermatology', 7);
insert into professional_interest(id, value, parent_category_id) values(123,'Diabetes', 7);
insert into professional_interest(id, value, parent_category_id) values(124,'Epilepsy', 7);
insert into professional_interest(id, value, parent_category_id) values(125,'GERD/Acid Reflux', 7);
insert into professional_interest(id, value, parent_category_id) values(126,'Headaches/Migraines', 7);
insert into professional_interest(id, value, parent_category_id) values(127,'Heart Disease', 7);
insert into professional_interest(id, value, parent_category_id) values(128,'Herbs for Health', 7);
insert into professional_interest(id, value, parent_category_id) values(129,'Holistic Healing', 7);
insert into professional_interest(id, value, parent_category_id) values(130,'IBS/Crohn''s Disease', 7);
insert into professional_interest(id, value, parent_category_id) values(131,'Incest/Abuse Support', 7);
insert into professional_interest(id, value, parent_category_id) values(132,'Incontinence', 7);
insert into professional_interest(id, value, parent_category_id) values(133,'Infertility', 7);
insert into professional_interest(id, value, parent_category_id) values(134,'Men''s Health', 7);
insert into professional_interest(id, value, parent_category_id) values(135,'Nutrition', 7);
insert into professional_interest(id, value, parent_category_id) values(136,'Orthopedics', 7);
insert into professional_interest(id, value, parent_category_id) values(137,'Panic/Anxiety', 7);
insert into professional_interest(id, value, parent_category_id) values(138,'Disorders', 7);
insert into professional_interest(id, value, parent_category_id) values(139,'Pediatrics', 7);
insert into professional_interest(id, value, parent_category_id) values(140,'Physical Therapy', 7);
insert into professional_interest(id, value, parent_category_id) values(141,'Psychology/Psychiatry', 7);
insert into professional_interest(id, value, parent_category_id) values(142,'Senior Health', 7);
insert into professional_interest(id, value, parent_category_id) values(143,'Sexuality', 7);
insert into professional_interest(id, value, parent_category_id) values(144,'Sleep Disorders', 7);
insert into professional_interest(id, value, parent_category_id) values(145,'Smoking Cessation', 7);
insert into professional_interest(id, value, parent_category_id) values(146,'Substance Abuse', 7);
insert into professional_interest(id, value, parent_category_id) values(147,'Thyroid Disease', 7);
insert into professional_interest(id, value, parent_category_id) values(148,'Weight Loss', 7);
insert into professional_interest(id, value, parent_category_id) values(149,'Women''s Health', 7);
insert into professional_interest(id, value, parent_category_id) values(150,'American Cuisine', 8);
insert into professional_interest(id, value, parent_category_id) values(151,'Barbecues & Grilling', 8);
insert into professional_interest(id, value, parent_category_id) values(152,'Cajun/Creole', 8);
insert into professional_interest(id, value, parent_category_id) values(153,'Chinese Cuisine', 8);
insert into professional_interest(id, value, parent_category_id) values(154,'Cocktails/Beer', 8);
insert into professional_interest(id, value, parent_category_id) values(155,'Coffee/Tea', 8);
insert into professional_interest(id, value, parent_category_id) values(156,'Cuisine-Specific', 8);
insert into professional_interest(id, value, parent_category_id) values(157,'Desserts & Baking', 8);
insert into professional_interest(id, value, parent_category_id) values(158,'Dining Out', 8);
insert into professional_interest(id, value, parent_category_id) values(159,'Food Allergies', 8);
insert into professional_interest(id, value, parent_category_id) values(160,'French Cuisine', 8);
insert into professional_interest(id, value, parent_category_id) values(161,'Health/LowFat Cooking', 8);
insert into professional_interest(id, value, parent_category_id) values(162,'Italian Cuisine', 8);
insert into professional_interest(id, value, parent_category_id) values(163,'Japanese Cuisine', 8);
insert into professional_interest(id, value, parent_category_id) values(164,'Mexican Cuisine', 8);
insert into professional_interest(id, value, parent_category_id) values(165,'Vegan', 8);
insert into professional_interest(id, value, parent_category_id) values(166,'Vegetarian', 8);
insert into professional_interest(id, value, parent_category_id) values(167,'Wine', 8);
insert into professional_interest(id, value, parent_category_id) values(168,'Art/Technology', 9);
insert into professional_interest(id, value, parent_category_id) values(169,'Arts & Crafts', 9);
insert into professional_interest(id, value, parent_category_id) values(170,'Beadwork', 9);
insert into professional_interest(id, value, parent_category_id) values(171,'Birdwatching', 9);
insert into professional_interest(id, value, parent_category_id) values(172,'Board Games/Puzzles', 9);
insert into professional_interest(id, value, parent_category_id) values(173,'Candle & Soap Making', 9);
insert into professional_interest(id, value, parent_category_id) values(174,'Card Games', 9);
insert into professional_interest(id, value, parent_category_id) values(175,'Chess', 9);
insert into professional_interest(id, value, parent_category_id) values(176,'Cigars', 9);
insert into professional_interest(id, value, parent_category_id) values(177,'Collecting', 9);
insert into professional_interest(id, value, parent_category_id) values(178,'Comic Books', 9);
insert into professional_interest(id, value, parent_category_id) values(179,'Drawing/Sketching', 9);
insert into professional_interest(id, value, parent_category_id) values(180,'Freelance Writing', 9);
insert into professional_interest(id, value, parent_category_id) values(181,'Genealogy', 9);
insert into professional_interest(id, value, parent_category_id) values(182,'Getting Published', 9);
insert into professional_interest(id, value, parent_category_id) values(183,'Guitar', 9);
insert into professional_interest(id, value, parent_category_id) values(184,'Home Recording', 9);
insert into professional_interest(id, value, parent_category_id) values(185,'Investors & Patents', 9);
insert into professional_interest(id, value, parent_category_id) values(186,'Jewelry Making', 9);
insert into professional_interest(id, value, parent_category_id) values(187,'Magic & Illusion', 9);
insert into professional_interest(id, value, parent_category_id) values(188,'Needlework', 9);
insert into professional_interest(id, value, parent_category_id) values(189,'Painting', 9);
insert into professional_interest(id, value, parent_category_id) values(190,'Photography', 9);
insert into professional_interest(id, value, parent_category_id) values(191,'Radio', 9);
insert into professional_interest(id, value, parent_category_id) values(192,'Roleplaying Games', 9);
insert into professional_interest(id, value, parent_category_id) values(193,'Sci-Fi & Fantasy', 9);
insert into professional_interest(id, value, parent_category_id) values(194,'Scrapbooking', 9);
insert into professional_interest(id, value, parent_category_id) values(195,'Screenwriting', 9);
insert into professional_interest(id, value, parent_category_id) values(196,'Stamps & Coins', 9);
insert into professional_interest(id, value, parent_category_id) values(197,'Video & Computer Games', 9);
insert into professional_interest(id, value, parent_category_id) values(198,'Woodworking', 9);
insert into professional_interest(id, value, parent_category_id) values(199,'Appliances', 10);
insert into professional_interest(id, value, parent_category_id) values(200,'Entertaining', 10);
insert into professional_interest(id, value, parent_category_id) values(201,'Environmental Safety', 10);
insert into professional_interest(id, value, parent_category_id) values(202,'Gardening', 10);
insert into professional_interest(id, value, parent_category_id) values(203,'Home Repair', 10);
insert into professional_interest(id, value, parent_category_id) values(204,'Home Theater', 10);
insert into professional_interest(id, value, parent_category_id) values(205,'Interior Decorating', 10);
insert into professional_interest(id, value, parent_category_id) values(206,'Landscaping', 10);
insert into professional_interest(id, value, parent_category_id) values(207,'Remodeling & Construction', 10);
insert into professional_interest(id, value, parent_category_id) values(208,'Immigration', 11);
insert into professional_interest(id, value, parent_category_id) values(209,'Legal Issues', 11);
insert into professional_interest(id, value, parent_category_id) values(210,'U.S. Government Resources', 11);
insert into professional_interest(id, value, parent_category_id) values(211,'Politics', 11);
insert into professional_interest(id, value, parent_category_id) values(212,'Commentary', 11);
insert into professional_interest(id, value, parent_category_id) values(213,'International News', 12);
insert into professional_interest(id, value, parent_category_id) values(214,'National News', 12);
insert into professional_interest(id, value, parent_category_id) values(215,'Local News', 12);
insert into professional_interest(id, value, parent_category_id) values(216,'Beginning Investing', 13);
insert into professional_interest(id, value, parent_category_id) values(217,'Credit/Debt & Loans', 13);
insert into professional_interest(id, value, parent_category_id) values(218,'Financial News', 13);
insert into professional_interest(id, value, parent_category_id) values(219,'Financial Planning', 13);
insert into professional_interest(id, value, parent_category_id) values(220,'Hedge Fund', 13);
insert into professional_interest(id, value, parent_category_id) values(221,'Insurance', 13);
insert into professional_interest(id, value, parent_category_id) values(222,'Investing', 13);
insert into professional_interest(id, value, parent_category_id) values(223,'Mutual Funds', 13);
insert into professional_interest(id, value, parent_category_id) values(224,'Options', 13);
insert into professional_interest(id, value, parent_category_id) values(225,'Retirement Planning', 13);
insert into professional_interest(id, value, parent_category_id) values(226,'Stocks', 13);
insert into professional_interest(id, value, parent_category_id) values(227,'Tax Planning', 13);
insert into professional_interest(id, value, parent_category_id) values(228,'Dating', 13);
insert into professional_interest(id, value, parent_category_id) values(229,'Divorce Support', 13);
insert into professional_interest(id, value, parent_category_id) values(230,'Gay Life', 14);
insert into professional_interest(id, value, parent_category_id) values(231,'Marriage', 14);
insert into professional_interest(id, value, parent_category_id) values(232,'Senior Living', 14);
insert into professional_interest(id, value, parent_category_id) values(233,'Teens', 14);
insert into professional_interest(id, value, parent_category_id) values(234,'Weddings', 14);
insert into professional_interest(id, value, parent_category_id) values(235,'Ethnic Specific', 14);
insert into professional_interest(id, value, parent_category_id) values(236,'Astrology', 14);
insert into professional_interest(id, value, parent_category_id) values(237,'Biology', 15);
insert into professional_interest(id, value, parent_category_id) values(238,'Chemistry', 15);
insert into professional_interest(id, value, parent_category_id) values(239,'Geology', 15);
insert into professional_interest(id, value, parent_category_id) values(240,'Paranormal Phenomena', 15);
insert into professional_interest(id, value, parent_category_id) values(241,'Physics', 15);
insert into professional_interest(id, value, parent_category_id) values(242,'Space/Astronomy', 15);
insert into professional_interest(id, value, parent_category_id) values(243,'Geography', 15);
insert into professional_interest(id, value, parent_category_id) values(244,'Botany', 15);
insert into professional_interest(id, value, parent_category_id) values(245,'Weather', 15);
insert into professional_interest(id, value, parent_category_id) values(246,'Aquariums', 16);
insert into professional_interest(id, value, parent_category_id) values(247,'Birds', 16);
insert into professional_interest(id, value, parent_category_id) values(248,'Cats', 16);
insert into professional_interest(id, value, parent_category_id) values(249,'Dogs', 16);
insert into professional_interest(id, value, parent_category_id) values(250,'Large Animals', 16);
insert into professional_interest(id, value, parent_category_id) values(251,'Reptiles', 16);
insert into professional_interest(id, value, parent_category_id) values(252,'Veterinary Medicine', 16);
insert into professional_interest(id, value, parent_category_id) values(253,'Auto Racing', 17);
insert into professional_interest(id, value, parent_category_id) values(254,'Baseball', 17);
insert into professional_interest(id, value, parent_category_id) values(255,'Bicycling', 17);
insert into professional_interest(id, value, parent_category_id) values(256,'Bodybuilding', 17);
insert into professional_interest(id, value, parent_category_id) values(257,'Boxing', 17);
insert into professional_interest(id, value, parent_category_id) values(258,'Canoeing/Kayaking', 17);
insert into professional_interest(id, value, parent_category_id) values(259,'Cheerleading', 17);
insert into professional_interest(id, value, parent_category_id) values(260,'Climbing', 17);
insert into professional_interest(id, value, parent_category_id) values(261,'Cricket', 17);
insert into professional_interest(id, value, parent_category_id) values(262,'Figure Skating', 17);
insert into professional_interest(id, value, parent_category_id) values(263,'Fly Fishing', 17);
insert into professional_interest(id, value, parent_category_id) values(264,'Football', 17);
insert into professional_interest(id, value, parent_category_id) values(265,'Freshwater Fishing', 17);
insert into professional_interest(id, value, parent_category_id) values(266,'Game & Fish', 17);
insert into professional_interest(id, value, parent_category_id) values(267,'Golf', 17);
insert into professional_interest(id, value, parent_category_id) values(268,'Horse Racing', 17);
insert into professional_interest(id, value, parent_category_id) values(269,'Horses', 17);
insert into professional_interest(id, value, parent_category_id) values(270,'Hunting/Shooting', 17);
insert into professional_interest(id, value, parent_category_id) values(271,'Inline Skating', 17);
insert into professional_interest(id, value, parent_category_id) values(272,'Martial Arts', 17);
insert into professional_interest(id, value, parent_category_id) values(273,'Mountain Biking', 17);
insert into professional_interest(id, value, parent_category_id) values(274,'NASCAR Racing', 17);
insert into professional_interest(id, value, parent_category_id) values(275,'Olympics', 17);
insert into professional_interest(id, value, parent_category_id) values(276,'Paintball', 17);
insert into professional_interest(id, value, parent_category_id) values(277,'Power & Motorcycles', 17);
insert into professional_interest(id, value, parent_category_id) values(278,'Pro Basketball', 17);
insert into professional_interest(id, value, parent_category_id) values(279,'Pro Ice Hockey', 17);
insert into professional_interest(id, value, parent_category_id) values(280,'Rodeo', 17);
insert into professional_interest(id, value, parent_category_id) values(281,'Rugby', 17);
insert into professional_interest(id, value, parent_category_id) values(282,'Running/Jogging', 17);
insert into professional_interest(id, value, parent_category_id) values(283,'Sailing', 17);
insert into professional_interest(id, value, parent_category_id) values(284,'Saltwater Fishing', 17);
insert into professional_interest(id, value, parent_category_id) values(285,'Scuba Diving', 17);
insert into professional_interest(id, value, parent_category_id) values(286,'Skateboarding', 17);
insert into professional_interest(id, value, parent_category_id) values(287,'Skiing', 17);
insert into professional_interest(id, value, parent_category_id) values(288,'Snowboarding', 17);
insert into professional_interest(id, value, parent_category_id) values(289,'Surfing/Bodyboarding', 17);
insert into professional_interest(id, value, parent_category_id) values(290,'Swimming', 17);
insert into professional_interest(id, value, parent_category_id) values(291,'Table Tennis/Ping-Pong', 17);
insert into professional_interest(id, value, parent_category_id) values(292,'Tennis', 17);
insert into professional_interest(id, value, parent_category_id) values(293,'Volleyball', 17);
insert into professional_interest(id, value, parent_category_id) values(294,'Walking', 17);
insert into professional_interest(id, value, parent_category_id) values(295,'Waterski/Wakeboard', 17);
insert into professional_interest(id, value, parent_category_id) values(296,'World Soccer', 17);
insert into professional_interest(id, value, parent_category_id) values(297,'Beauty', 18);
insert into professional_interest(id, value, parent_category_id) values(298,'Body Art', 18);
insert into professional_interest(id, value, parent_category_id) values(299,'Fashion', 18);
insert into professional_interest(id, value, parent_category_id) values(300,'Jewelry', 18);
insert into professional_interest(id, value, parent_category_id) values(301,'Clothing', 18);
insert into professional_interest(id, value, parent_category_id) values(302,'Accessories', 18);
insert into professional_interest(id, value, parent_category_id) values(303,'3-D Graphics', 19);
insert into professional_interest(id, value, parent_category_id) values(304,'Animation', 19);
insert into professional_interest(id, value, parent_category_id) values(305,'Antivirus Software', 19);
insert into professional_interest(id, value, parent_category_id) values(306,'C/C++', 19);
insert into professional_interest(id, value, parent_category_id) values(307,'Cameras & Camcorders', 19);
insert into professional_interest(id, value, parent_category_id) values(308,'Cell Phones', 19);
insert into professional_interest(id, value, parent_category_id) values(309,'Computer Certification', 19);
insert into professional_interest(id, value, parent_category_id) values(310,'Computer Networking', 19);
insert into professional_interest(id, value, parent_category_id) values(311,'Computer Peripherals', 19);
insert into professional_interest(id, value, parent_category_id) values(312,'Computer Reviews', 19);
insert into professional_interest(id, value, parent_category_id) values(313,'Data Centers', 19);
insert into professional_interest(id, value, parent_category_id) values(314,'Databases', 19);
insert into professional_interest(id, value, parent_category_id) values(315,'Desktop Publishing', 19);
insert into professional_interest(id, value, parent_category_id) values(316,'Desktop Video', 19);
insert into professional_interest(id, value, parent_category_id) values(317,'Email', 19);
insert into professional_interest(id, value, parent_category_id) values(318,'Graphics Software', 19);
insert into professional_interest(id, value, parent_category_id) values(319,'Home Video/DVD', 19);
insert into professional_interest(id, value, parent_category_id) values(320,'Internet Technology', 19);
insert into professional_interest(id, value, parent_category_id) values(321,'Java', 19);
insert into professional_interest(id, value, parent_category_id) values(322,'JavaScript', 19);
insert into professional_interest(id, value, parent_category_id) values(323,'Linux', 19);
insert into professional_interest(id, value, parent_category_id) values(324,'Mac OS', 19);
insert into professional_interest(id, value, parent_category_id) values(325,'Mac Support', 19);
insert into professional_interest(id, value, parent_category_id) values(326,'MP3/MIDI', 19);
insert into professional_interest(id, value, parent_category_id) values(327,'Net Conferencing', 19);
insert into professional_interest(id, value, parent_category_id) values(328,'Net for Beginners', 19);
insert into professional_interest(id, value, parent_category_id) values(329,'Network Security', 19);
insert into professional_interest(id, value, parent_category_id) values(330,'Palmtops/PDAs', 19);
insert into professional_interest(id, value, parent_category_id) values(331,'PC Support', 19);
insert into professional_interest(id, value, parent_category_id) values(332,'Portable', 19);
insert into professional_interest(id, value, parent_category_id) values(333,'Entertainment', 19);
insert into professional_interest(id, value, parent_category_id) values(334,'Shareware/Freeware', 19);
insert into professional_interest(id, value, parent_category_id) values(335,'Unix', 19);
insert into professional_interest(id, value, parent_category_id) values(336,'Visual Basic', 19);
insert into professional_interest(id, value, parent_category_id) values(337,'Web Clip Art', 19);
insert into professional_interest(id, value, parent_category_id) values(338,'Web Design/HTML', 19);
insert into professional_interest(id, value, parent_category_id) values(339,'Web Search', 19);
insert into professional_interest(id, value, parent_category_id) values(340,'Windows', 19);
insert into professional_interest(id, value, parent_category_id) values(341,'Adventure Travel', 20);
insert into professional_interest(id, value, parent_category_id) values(342,'Africa', 20);
insert into professional_interest(id, value, parent_category_id) values(343,'Air Travel', 20);
insert into professional_interest(id, value, parent_category_id) values(344,'Australia & New Zealand', 20);
insert into professional_interest(id, value, parent_category_id) values(345,'Bed & Breakfasts', 20);
insert into professional_interest(id, value, parent_category_id) values(346,'Budget Travel', 20);
insert into professional_interest(id, value, parent_category_id) values(347,'Business Travel', 20);
insert into professional_interest(id, value, parent_category_id) values(348,'By US Locale', 20);
insert into professional_interest(id, value, parent_category_id) values(349,'Camping', 20);
insert into professional_interest(id, value, parent_category_id) values(350,'Canada', 20);
insert into professional_interest(id, value, parent_category_id) values(351,'Caribbean', 20);
insert into professional_interest(id, value, parent_category_id) values(352,'Cruises', 20);
insert into professional_interest(id, value, parent_category_id) values(353,'Eastern Europe', 20);
insert into professional_interest(id, value, parent_category_id) values(354,'Europe', 20);
insert into professional_interest(id, value, parent_category_id) values(355,'France', 20);
insert into professional_interest(id, value, parent_category_id) values(356,'Greece', 20);
insert into professional_interest(id, value, parent_category_id) values(357,'Honeymoons/Getaways', 20);
insert into professional_interest(id, value, parent_category_id) values(358,'Hotels', 20);
insert into professional_interest(id, value, parent_category_id) values(359,'Italy', 20);
insert into professional_interest(id, value, parent_category_id) values(360,'Japan', 20);
insert into professional_interest(id, value, parent_category_id) values(361,'Mexico & Central America', 20);
insert into professional_interest(id, value, parent_category_id) values(362,'National Parks', 20);
insert into professional_interest(id, value, parent_category_id) values(363,'South America', 20);
insert into professional_interest(id, value, parent_category_id) values(364,'Spas', 20);
insert into professional_interest(id, value, parent_category_id) values(365,'Theme Parks', 20);
insert into professional_interest(id, value, parent_category_id) values(366,'Traveling with Kids', 20);
insert into professional_interest(id, value, parent_category_id) values(367,'United Kingdom', 20);
insert into professional_interest(id, value, parent_category_id) values(368,'Apartments', 21);
insert into professional_interest(id, value, parent_category_id) values(369,'Architects', 21);
insert into professional_interest(id, value, parent_category_id) values(370,'Buying/Selling Homes', 21);
insert into professional_interest(id, value, parent_category_id) values(371,'Contests & Freebies', 22);
insert into professional_interest(id, value, parent_category_id) values(372,'Couponing', 22);
insert into professional_interest(id, value, parent_category_id) values(373,'Comparison Engines', 22);
insert into professional_interest(id, value, parent_category_id) values(375,'Alternative Religions', 23);
insert into professional_interest(id, value, parent_category_id) values(376,'Atheism/Agnosticism', 23);
insert into professional_interest(id, value, parent_category_id) values(377,'Buddhism', 23);
insert into professional_interest(id, value, parent_category_id) values(378,'Catholicism', 23);
insert into professional_interest(id, value, parent_category_id) values(379,'Christianity', 23);
insert into professional_interest(id, value, parent_category_id) values(380,'Hinduism', 23);
insert into professional_interest(id, value, parent_category_id) values(381,'Islam', 23);
insert into professional_interest(id, value, parent_category_id) values(382,'Judaism', 23);
insert into professional_interest(id, value, parent_category_id) values(383,'Latter-Day Saints', 23);
insert into professional_interest(id, value, parent_category_id) values(384,'Pagan/Wiccan', 23);
insert into professional_interest(id, value, parent_category_id) values(385,'Social Media', 24);

insert into document_type values(1,'DocumentType1', 'iconPath1');
insert into document_type values(2,'DocumentType2', 'iconPath2');
insert into document_type values(3,'DocumentType3', 'iconPath3');

insert into user values(1, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname1', 'lastname1', 'email1@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-01','ACTIVE', NULL, NULL, NULL, false, true, '7583 Classon Avenue', 'Brooklyn',32,230,'11205',-73.9617176,40.6978877, '2016-10-01');
insert into user values(2, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname2', 'lastname2', 'email2@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-02','ACTIVE', NULL, NULL, NULL, true, true, '215 Park Ave', 'Brooklyn',32,230,'11205',-73.9702619,40.6962729, '2016-10-02');
insert into user values(3, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname3', 'lastname3', 'email3@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-03','ACTIVE', NULL, NULL, NULL, false, true, '261 Moore St', 'Brooklyn',32,230,'11206',-73.9335866,40.7050622, '2016-10-03');
insert into user values(4, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname4', 'lastname4', 'email4@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-04','ACTIVE', NULL, NULL, NULL, true, true, '54-29 Metropolitan Ave', 'Ridgewood',32,230,'11385',-73.9095494,40.7131197, '2016-10-04');
insert into user values(5, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname5', 'lastname5', 'email5@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-05','INACTIVE', NULL, NULL, NULL, false, true, 'Suydam St', 'Ridgewood',32,230,'11385',-73.916849,40.708976, '2016-10-05');
insert into user values(6, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname6', 'lastname6', 'email6@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-06','ACTIVE', NULL, NULL, NULL, true, true, '65-40 Grand Ave', 'Flushing',32,230,'11378',-73.8992662,40.7229976, '2016-10-06');
insert into user values(7, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname7', 'lastname7', 'email7@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-07','ACTIVE', NULL, NULL, NULL, false, true, '59-63 54th Ave', 'Maspeth',32,230,'11378',-73.9065762,40.7306847, '2016-10-07');
insert into user values(8, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname8', 'lastname8', 'email8@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-08','ACTIVE', NULL, NULL, NULL, true, true, '34-02 Greenpoint Ave', 'Maspeth',32,230,'11378',-73.9307031,40.7329573, '2016-10-08');
insert into user values(9, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname9', 'lastname9', 'email9@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-09','ACTIVE', NULL, NULL, NULL, false, true, null, 'Brooklyn',32,230,'11222',-73.9506774,40.7282702, '2016-10-09');
insert into user values(10, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname10', 'lastname10', 'email10@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-10','ACTIVE', NULL, NULL, NULL, true, true, null, 'Queens',32,230,'11101',-73.9418603,40.7443091, '2016-10-10');
insert into user values(11, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname11', 'lastname11', 'email11@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-11','INACTIVE', NULL, NULL, NULL, false, true, '50-10 Northern Blvd', 'Long Island City',32,230,'11101',-73.91225,40.75210900, '2016-10-11');
insert into user values(12, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname12', 'lastname12', 'email12@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-12','ACTIVE', NULL, NULL, NULL, true, true, '61-11 Fresh Pond Rd', 'Middle Village',32,230,'11379',-73.9010345,40.7142633, '2016-10-12');
insert into user values(13, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname13', 'lastname13', 'email13@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-13','ACTIVE', NULL, NULL, NULL, false, true, '5602 31st Ave', 'Flushing',32,230,'11377',-73.905135,40.75681, '2016-10-13');
insert into user values(14, '$2a$10$x89u76j2IgiINI/LzVeXzOEq63VprctUKupS0QtPYGFd6JhzkBgke', 'firstname14', 'lastname14', 'email14@test.com', 'http://img4.imgtn.bdimg.com/it/u=3514646889,3827435585&fm=23&gp=0.jpg', '2016-10-14','ACTIVE', NULL, NULL, NULL, false, true, '54-19 Flushing Ave', 'Flushing',32,230,'11378',-73.913122,40.71549, '2016-10-14');

insert into user_user_role values(1,1);
insert into user_user_role values(2,2);
insert into user_user_role values(3,3);
insert into user_user_role values(4,4);
insert into user_user_role values(5,3);
insert into user_user_role values(6,3);
insert into user_user_role values(7,3);
insert into user_user_role values(8,3);
insert into user_user_role values(9,3);
insert into user_user_role values(10,4);
insert into user_user_role values(11,4);
insert into user_user_role values(12,4);
insert into user_user_role values(13,4);
insert into user_user_role values(14,4);

insert into institution values(1, 'institutionName1', 'parentOrganization1' , 'streetAddress1', 'city1', 1, 'zip1', 1,'phone1', 'institution1@test.com', 'description1', 'ACTIVE','https://slice.mit.edu/wp-content/uploads/2010/04/mitseal.gif', '2016-10-01', '2016-10-01');
insert into institution values(2, 'institutionName2', NUlL , 'streetAddress2', 'city2', 2, 'zip2', 2,'phone2', 'institution2@test.com', 'description2', 'INACTIVE','https://slice.mit.edu/wp-content/uploads/2010/04/mitseal.gif', '2016-10-02', '2016-10-02');
insert into institution values(3, 'institutionName3', 'parentOrganization3' , 'streetAddress3', 'city3', 2, 'zip3', 1,'phone3', 'institution3@test.com', 'description3', 'ACTIVE','https://slice.mit.edu/wp-content/uploads/2010/04/mitseal.gif', '2016-10-03', '2016-10-03');
insert into institution values(4, 'institutionName4', 'parentOrganization4' , 'streetAddress4', 'city4', 2, 'zip4', 2,'phone4', 'institution4@test.com', 'description4', 'ACTIVE','https://slice.mit.edu/wp-content/uploads/2010/04/mitseal.gif', '2016-10-04', '2016-10-04');
insert into institution values(5, 'institutionName5', 'parentOrganization5' , 'streetAddress5', 'city5', 2, 'zip5', 1,'phone5', 'institution5@test.com', 'description5', 'ACTIVE','https://slice.mit.edu/wp-content/uploads/2010/04/mitseal.gif', '2016-10-05', '2016-10-05');
insert into institution values(6, 'institutionName6', 'parentOrganization6' , 'streetAddress6', 'city6', 2, 'zip6', 2,'phone6', 'institution6@test.com', 'description6', 'ACTIVE','https://slice.mit.edu/wp-content/uploads/2010/04/mitseal.gif', '2016-10-06', '2016-10-06');

insert into institution_contact values(1, 'title1', 'firstName1', 'lastName1', 'institutionContact1@test.com', 'phoneNumber1', true, 1);
insert into institution_contact values(2, 'title2', 'firstName2', 'lastName2', 'institutionContact2@test.com', 'phoneNumber2', false, 1);
insert into institution_contact values(3, 'title3', 'firstName3', 'lastName3', 'institutionContact3@test.com', 'phoneNumber3', true, 2);

insert into mentor values(3, 1, true, '1988-08-01', 'phone1', 'skypeUsername1','introVideoLink1','description1',0,'MENTEE_PAIRED', 'companyName1','linkedInUrl1', 'whatsapp1');
insert into mentor values(5, 2, false, '1988-08-02', 'phone2', 'skypeUsername2','introVideoLink2','description2',1,'PROFESSIONAL_CONSULTANT', 'companyName2','linkedInUrl2', 'whatsapp2');
-- must use institution_id=1 for matching
insert into mentor values(6, 1, true, '1988-08-03', 'phone3', 'skypeUsername3','introVideoLink3','description3',2,'MENTEE_PAIRED', 'companyName3','linkedInUrl3', 'whatsapp3');
insert into mentor values(7, 4, false, '1988-08-04', 'phone4', 'skypeUsername4','introVideoLink4','description4',3,'PROFESSIONAL_CONSULTANT', 'companyName4','linkedInUrl4', 'whatsapp4');
-- must use institution_id=1 for matching
insert into mentor values(8, 1, true, '1988-08-05', 'phone5', 'skypeUsername5','introVideoLink5','description5',4,'MENTEE_PAIRED', 'companyName5','linkedInUrl5', 'whatsapp5');
insert into mentor values(9, 6, false, '1988-08-06', 'phone6', 'skypeUsername6','introVideoLink5','description6',5,'PROFESSIONAL_CONSULTANT', 'companyName6','linkedInUrl6', 'whatsapp6');

insert into mentor_professional_area values(3,1);
insert into mentor_professional_area values(3,2);

insert into professional_experience_data values(1,'position1', 'workLocation1', '2016-10-11','2016-10-31','description1',3);
insert into professional_experience_data values(2,'position2', 'workLocation2', '2016-11-11','2016-11-30','description2',3);

insert into weighted_personal_interest values(1,3,1,1);
insert into weighted_personal_interest values(2,3,2,2);
insert into weighted_personal_interest values(3,4,1,2);
insert into weighted_personal_interest values(4,4,2,3);
-- matching mentors not same personal_interest id but same parent category
insert into weighted_personal_interest values(5,7,3,2);
insert into weighted_personal_interest values(6,10,4,2);
-- matching mentors not same personal_interest id and same parent category and has bigger weight
insert into weighted_personal_interest values(7,5,3,3);
-- matching mentors  same personal_interest id
insert into weighted_personal_interest values(8,9,2,2);
insert into weighted_personal_interest values(9,10,2,2);

-- matching mentees not same personal_interest id but same parent category
insert into weighted_personal_interest values(10,3,3,2);
insert into weighted_personal_interest values(11,11,4,2);
-- matching mentees not same personal_interest id and same parent category and has bigger weight
insert into weighted_personal_interest values(12,13,4,3);



insert into weighted_professional_interest values(1,3,1,1);
insert into weighted_professional_interest values(2,3,2,2);
insert into weighted_professional_interest values(3,4,1,2);
insert into weighted_professional_interest values(4,4,2,3);

-- matching mentors not same professional_interest id but same parent category
insert into weighted_professional_interest values(5,6,3,2);
insert into weighted_professional_interest values(6,4,4,2);
-- matching mentors not same professional_interest id and same parent category and has bigger weight
insert into weighted_professional_interest values(7,7,3,3);
-- matching mentors same professional_interest id
insert into weighted_professional_interest values(8,8,2,2);

-- matching mentees not same professional_interest id but same parent category
insert into weighted_professional_interest values(9,5,3,2);
insert into weighted_professional_interest values(10,12,4,2);
-- matching mentees not same professional_interest id and same parent category and has bigger weight
insert into weighted_professional_interest values(11,14,4,3);

insert into institutional_program values (1, 'programName1', 'description1', '2016-10-11','2016-10-31',1,1,20, '2016-10-10','http://content.screencast.com/users/kinfkong/folders/Jing/media/eb51ede7-54e9-4b39-877c-cb8c0a5c74ad/00000052.png', '2016-10-10');
insert into institutional_program values (2, 'programName2', 'description2', '2016-10-12','2016-10-21',2,2,10, '2016-10-11','http://content.screencast.com/users/kinfkong/folders/Jing/media/eb51ede7-54e9-4b39-877c-cb8c0a5c74ad/00000052.png', '2016-10-11');
insert into institutional_program values (3, 'programName3', 'description3', '2016-10-13','2016-10-20',3,3,8, '2016-10-12','http://content.screencast.com/users/kinfkong/folders/Jing/media/eb51ede7-54e9-4b39-877c-cb8c0a5c74ad/00000052.png', '2016-10-12');
insert into institutional_program values (4, 'programName4', 'description4', '2016-10-14','2016-10-19',4,1,7, '2016-10-13','http://content.screencast.com/users/kinfkong/folders/Jing/media/eb51ede7-54e9-4b39-877c-cb8c0a5c74ad/00000052.png', '2016-10-13');
insert into institutional_program values (5, 'programName5', 'description5', '2016-10-15','2016-10-18',5,2,6, '2016-10-14','http://content.screencast.com/users/kinfkong/folders/Jing/media/eb51ede7-54e9-4b39-877c-cb8c0a5c74ad/00000052.png', '2016-10-14');
insert into institutional_program values (6, 'programName6', 'description6', '2016-10-16','2016-10-17',6,3,5, '2016-10-15','http://content.screencast.com/users/kinfkong/folders/Jing/media/eb51ede7-54e9-4b39-877c-cb8c0a5c74ad/00000052.png', '2016-10-15');

insert into institution_affiliation_code values(1, 'code1', 1, true);
insert into institution_affiliation_code values(2, 'code2', 2, true);
insert into institution_affiliation_code values(3, 'code3', 3, true);
insert into institution_affiliation_code values(4, 'code4', 4, true);
insert into institution_affiliation_code values(5, 'code5', 5, true);
insert into institution_affiliation_code values(6, 'code6', 6, true);

insert into parent_consent values(1, 'parentName1', 'signatureFilePath1', 'parentEmail1@test.com', null, 'token1');
insert into parent_consent values(2, 'parentName2', 'signatureFilePath2', 'parentEmail2@test.com', null, 'token2');


insert into mentee values(4, 1, true, '1988-08-01', 'phone1', 'skypeUsername1','introVideoLink1','description1',0,101.91,'school1',1,1,'facebookUrl1', null);
insert into mentee values(10, 2, false, '1988-08-02', 'phone2', 'skypeUsername2','introVideoLink2','description2',1,102.92,'school2',2,2,'facebookUrl2', null);
-- must use institution_id=1 for matching
insert into mentee values(11, 1, true, '1988-08-03', 'phone3', 'skypeUsername3','introVideoLink3','description3',2,103.93,'school3',3,NULL,'facebookUrl3', null);
insert into mentee values(12, 4, false, '1988-08-04', 'phone4', 'skypeUsername4','introVideoLink4','description4',3,104.94,'school4',4,NULL,'facebookUrl4', null);
-- must use institution_id=1 for matching
insert into mentee values(13, 1, true, '1988-08-05', 'phone5', 'skypeUsername5','introVideoLink5','description5',4,105.95,'school5',5,NULL,'facebookUrl5', null);
insert into mentee values(14, 6, false, '1988-08-06', 'phone6', 'skypeUsername6','introVideoLink6','description6',5,106.96,'school6',6,NULL,'facebookUrl6', null);

insert into mentor_feedback values(1, 12, 'mentor_feedback_comment1', '2016-12-01');

insert into mentee_feedback values(1, 12, 'mentee_feedback_comment1', '2016-12-02');

insert into mentee_mentor_program values(1, 4, 3, 1, 'APPROVED', 1, 1, '2016-12-01','2017-01-31',true,'2016-12-31');
insert into mentee_mentor_program values(2, 10, 5, 2, 'REJECTED', 1, 1, '2016-12-02','2017-01-30',false, NULL);
insert into mentee_mentor_program values(3, 11, 6, 3, 'REQUESTED_BY_MENTOR', 1, 1, '2016-12-03','2016-12-29',false, NULL);
insert into mentee_mentor_program values(4, 12, 7, 4, 'REQUESTED_BY_MENTEE', 1, 1, '2016-12-04','2016-12-28',false, NULL);
insert into mentee_mentor_program values(5, 13, 8, 5, 'APPROVED', 1, 1, '2016-12-05','2016-12-27',false, NULL);
insert into mentee_mentor_program values(6, 14, 9, 6, 'APPROVED', 1, 1, '2016-12-06','2016-12-26',false, NULL);

insert into goal values(1, 1, 'subject1','description1',1,1,1,true);
insert into goal values(2, 2, 'subject2','description2',2,2,2,false);
insert into goal values(3, 3, 'subject3','description3',3,3,3,true);
insert into goal values(4, 4, 'subject4','description4',1,4,4,false);
insert into goal values(5, 5, 'subject5','description5',2,5,5,true);
insert into goal values(6, 6, 'subject6','description6',3,6,6,false);

insert into mentee_mentor_goal values(1, 1, 1,true,'2016-12-31');
insert into mentee_mentor_goal values(2, 2, 2,false, NULL);
insert into mentee_mentor_goal values(3, 3, 3,false, NULL);
insert into mentee_mentor_goal values(4, 4, 4,false, NULL);
insert into mentee_mentor_goal values(5, 5, 5,false, NULL);
insert into mentee_mentor_goal values(6, 6, 2,false, NULL);

insert into task values(1, 'description1',1,true,true,true,1,1);
insert into task values(2, 'description2',2, false,true,false,2,2);
insert into task values(3, 'description3',3, true,false,true,3,3);
insert into task values(4, 'description4',4,false,true,true,4,4);
insert into task values(5, 'description5',5,true,true,false,5,5);
insert into task values(6, 'description6',2,true,false,true,6,6);

insert into mentee_mentor_task values(1, 1, true,'2016-12-31',1, '2016-12-01','2016-12-31');
insert into mentee_mentor_task values(2, 2, false,NULL,2, '2016-12-02','2016-12-30');
insert into mentee_mentor_task values(3, 3, false,NULL,3, '2016-12-03','2016-12-29');
insert into mentee_mentor_task values(4, 4, false,NULL,4, '2016-12-04','2016-12-28');
insert into mentee_mentor_task values(5, 5, false,NULL,5, '2016-12-05','2016-12-27');
insert into mentee_mentor_task values(6, 2, false,NULL,6, '2016-12-06','2016-12-26');



insert into event values(1, 1,'name1', 'description1', '2017-11-11','2017-10-31', 'eventLocation1', 'eventLocationAddress1','city1',1 ,'zip1',1,1,true);


insert into activity values(1, 1, 'GOAL_CREATED', 1, 'description1', 1, '2016-12-01',4, 3, true, 1, '2016-12-01');
insert into activity values(2, 2, 'GOAL_UPDATED', 2, 'description2', 2, '2016-12-02',10, 5, false, 2, '2016-12-02');
insert into activity values(3, 3, 'TASK_CREATED', 3, 'description3', 3, '2016-12-03',11, 6, true, 3, '2016-12-03');
insert into activity values(4, 4, 'TASK_UPDATED', 4, 'description4', 4, '2016-12-04',12, 7, false, 4, '2016-12-04');
insert into activity values(5, 5, 'EVENT_CREATED', 5, 'description5', 5, '2016-12-05',13, 8, true, 5, '2016-12-05');
insert into activity values(6, NULL , 'EVENT_UPDATED', 6, 'description6', 6, '2016-12-06',NULL, NULL, false, 6, '2016-12-06');


insert into institution_agreement values(1, 'agreementName1', 'agreementFilePath1', 1);
insert into institution_agreement values(2, 'agreementName2', 'agreementFilePath2', 2);
insert into institution_agreement values(3, 'agreementName3', 'agreementFilePath3', 3);
insert into institution_agreement values(4, 'agreementName4', 'agreementFilePath4', 4);
insert into institution_agreement values(5, 'agreementName5', 'agreementFilePath5', 5);
insert into institution_agreement values(6, 'agreementName6', 'agreementFilePath6', 6);

insert into institution_agreement_user_role values(1, 1);
insert into institution_agreement_user_role values(1, 2);

insert into document values(1,'name1', 'path1', 1, '2016-12-01', 1, '2016-12-01');
insert into document values(2,'name2', 'path2', 2, '2016-12-02', 2, '2016-12-02');
insert into document values(3,'name3', 'path3', 3, '2016-12-03', 3, '2016-12-03');
insert into document values(4,'name4', 'path4', 4, '2016-12-04', 4, '2016-12-04');
insert into document values(5,'name5', 'path5', 5, '2016-12-05', 5, '2016-12-05');
insert into document values(6,'name6', 'path6', 6, '2016-12-06', 6, '2016-12-06');

insert into institutional_program_document values(1,1);
insert into institutional_program_document values(1, 2);

insert into goal_document values(1,3);
insert into goal_document values(1,4);

insert into task_document values(1, 5);
insert into task_document values(1, 6);

insert into useful_link values(1, 'title1', 'address1', 1, '2016-01-03');
insert into useful_link values(2, 'title2', 'address2', 2, '2016-02-03');
insert into useful_link values(3, 'title3', 'address3', 3, '2016-03-18');
insert into useful_link values(4, 'title4', 'address4', 4, '2016-08-08');
insert into useful_link values(5, 'title5', 'address5', 5, '2016-09-09');
insert into useful_link values(6, 'title6', 'address6', 6, '2016-10-10');

insert into goal_useful_link values(1, 1);
insert into goal_useful_link values(1, 2);

insert into task_useful_link values(1, 3);
insert into task_useful_link values(1, 4);

insert into institutional_program_link values(1, 5);
insert into institutional_program_link values(1, 6);

insert into custom_assigned_goal_data values(1, 3, 4, 1);

insert into custom_assigned_task_data values(1,3,4,1);

insert into responsibility values(1, 1, 'title1', '2016-12-01', true, true, 1);
insert into responsibility values(2, 2, 'title2', '2016-12-02', false, true, 2);
insert into responsibility values(3, 3, 'title3', '2016-12-03', true, false, 3);
insert into responsibility values(4, 4, 'title4', '2016-12-04', false, true, 4);
insert into responsibility values(5, 5, 'title5', '2016-12-05', true, true, 5);
insert into responsibility values(6, 6, 'title6', '2016-12-06', false, false, 6);


insert into mentee_mentor_responsibility values(1, 1, 'title1', '2016-12-01', true, true, 1,1);
insert into mentee_mentor_responsibility values(2, 2, 'title2', '2016-12-02', false, true, 2,2);
insert into mentee_mentor_responsibility values(3, 3, 'title3', '2016-12-03', true, false, 3,3);
insert into mentee_mentor_responsibility values(4, 4, 'title4', '2016-12-04', false, true, 4,4);
insert into mentee_mentor_responsibility values(5, 5, 'title5', '2016-12-05', true, true, 5,5);
insert into mentee_mentor_responsibility values(6, 6, 'title6', '2016-12-06', false, false, 6,6);


insert into skill values(1, 'Leadership Training', 'Help you develop a truly engaging and responsive communication skills, leading to positive results for your career path.', 'http://pic.58pic.com/58pic/15/37/53/33H58PICXSr_1024.jpg');
insert into skill values(2, 'Management Skills', 'Help you develop a truly engaging and responsive communication skills, leading to positive results for your career path.', 'http://pic.58pic.com/58pic/15/37/53/33H58PICXSr_1024.jpg');
insert into skill values(3, 'Time Management', 'Help you develop a truly engaging and responsive communication skills, leading to positive results for your career path.', 'http://pic.58pic.com/58pic/15/37/53/33H58PICXSr_1024.jpg');
insert into skill values(4, 'Entrepreneurship', 'Help you develop a truly engaging and responsive communication skills, leading to positive results for your career path.', 'http://pic.58pic.com/58pic/15/37/53/33H58PICXSr_1024.jpg');

insert into mentee_skill values(1, 4, 1);
insert into mentee_skill values(2, 4, 3);

insert into program_skill values(1, 1, 1);
insert into program_skill values(2, 1, 2);
insert into program_skill values(3, 2, 2);
insert into program_skill values(4, 3, 3);
insert into program_skill values(5, 4, 4);
insert into program_skill values(6, 5, 1);
insert into program_skill values(7, 6, 2);

insert into mentee_mentor_program_request values(1, 3, 4, '2016-12-26', 'REQUESTED_BY_MENTEE', null);